// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_triage.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getBookingRequestByID = `-- name: GetBookingRequestByID :one
SELECT id, artist_id, open_book_id, type, flash_id, description, reference_image_keys, placement, approx_size_inches, client_availability, client_name, client_email, client_phone, status, deposit_status, waiver_status, session_duration_minutes, client_user_id, created_at, updated_at, decided_at, styles, custom_answers, color_type, location_id, flash_size_code, schedule_token, schedule_emailed_at, deposit_amount_cents, ai_status, ai_label, ai_summary, ai_signals, ai_red_flags, ai_reasoning, ai_value_cents, ai_session_count, ai_draft_reply, ai_updated_at FROM booking_requests WHERE id = $1
`

func (q *Queries) GetBookingRequestByID(ctx context.Context, id uuid.UUID) (BookingRequest, error) {
	row := q.db.QueryRow(ctx, getBookingRequestByID, id)
	var i BookingRequest
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.OpenBookID,
		&i.Type,
		&i.FlashID,
		&i.Description,
		&i.ReferenceImageKeys,
		&i.Placement,
		&i.ApproxSizeInches,
		&i.ClientAvailability,
		&i.ClientName,
		&i.ClientEmail,
		&i.ClientPhone,
		&i.Status,
		&i.DepositStatus,
		&i.WaiverStatus,
		&i.SessionDurationMinutes,
		&i.ClientUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DecidedAt,
		&i.Styles,
		&i.CustomAnswers,
		&i.ColorType,
		&i.LocationID,
		&i.FlashSizeCode,
		&i.ScheduleToken,
		&i.ScheduleEmailedAt,
		&i.DepositAmountCents,
		&i.AiStatus,
		&i.AiLabel,
		&i.AiSummary,
		&i.AiSignals,
		&i.AiRedFlags,
		&i.AiReasoning,
		&i.AiValueCents,
		&i.AiSessionCount,
		&i.AiDraftReply,
		&i.AiUpdatedAt,
	)
	return i, err
}

const setBookingRequestTriageStatus = `-- name: SetBookingRequestTriageStatus :exec
UPDATE booking_requests
SET ai_status     = $2,
    ai_updated_at = now()
WHERE id = $1
`

type SetBookingRequestTriageStatusParams struct {
	ID       uuid.UUID `json:"id"`
	AiStatus string    `json:"ai_status"`
}

func (q *Queries) SetBookingRequestTriageStatus(ctx context.Context, arg SetBookingRequestTriageStatusParams) error {
	_, err := q.db.Exec(ctx, setBookingRequestTriageStatus, arg.ID, arg.AiStatus)
	return err
}

const updateBookingRequestTriage = `-- name: UpdateBookingRequestTriage :exec
UPDATE booking_requests
SET ai_status       = 'ready',
    ai_label        = $2,
    ai_summary      = $3,
    ai_signals      = $4,
    ai_red_flags    = $5,
    ai_reasoning    = $6,
    ai_value_cents  = $7,
    ai_session_count = $8,
    ai_draft_reply  = $9,
    ai_updated_at   = now()
WHERE id = $1
`

type UpdateBookingRequestTriageParams struct {
	ID             uuid.UUID `json:"id"`
	AiLabel        *string   `json:"ai_label"`
	AiSummary      string    `json:"ai_summary"`
	AiSignals      []byte    `json:"ai_signals"`
	AiRedFlags     []byte    `json:"ai_red_flags"`
	AiReasoning    string    `json:"ai_reasoning"`
	AiValueCents   *int64    `json:"ai_value_cents"`
	AiSessionCount *int32    `json:"ai_session_count"`
	AiDraftReply   string    `json:"ai_draft_reply"`
}

func (q *Queries) UpdateBookingRequestTriage(ctx context.Context, arg UpdateBookingRequestTriageParams) error {
	_, err := q.db.Exec(ctx, updateBookingRequestTriage,
		arg.ID,
		arg.AiLabel,
		arg.AiSummary,
		arg.AiSignals,
		arg.AiRedFlags,
		arg.AiReasoning,
		arg.AiValueCents,
		arg.AiSessionCount,
		arg.AiDraftReply,
	)
	return err
}
