// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countOverlappingAppointments = `-- name: CountOverlappingAppointments :one
SELECT COUNT(*)
FROM appointments
WHERE artist_id = $1
  AND scheduled_start IS NOT NULL
  AND status NOT IN ('cancelled', 'no_show')
  AND booking_request_id <> $2
  AND tstzrange(scheduled_start, scheduled_start + duration_minutes * interval '1 minute')
      && tstzrange($3::timestamptz, $4::timestamptz)
`

type CountOverlappingAppointmentsParams struct {
	ArtistID         uuid.UUID          `json:"artist_id"`
	ExcludeRequestID uuid.UUID          `json:"exclude_request_id"`
	WindowStart      pgtype.Timestamptz `json:"window_start"`
	WindowEnd        pgtype.Timestamptz `json:"window_end"`
}

// Counts the artist's live, time-locked appointments whose [start, start+duration)
// window overlaps the proposed one — used to block double-booking. Proposed
// client-scheduled slots (NULL start) and cancelled/no-show slots never conflict.
func (q *Queries) CountOverlappingAppointments(ctx context.Context, arg CountOverlappingAppointmentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOverlappingAppointments,
		arg.ArtistID,
		arg.ExcludeRequestID,
		arg.WindowStart,
		arg.WindowEnd,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAppointment = `-- name: CreateAppointment :one
INSERT INTO appointments (
    artist_id, booking_request_id, type, status,
    scheduled_start, duration_minutes, format, scheduling_origin
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
RETURNING id, artist_id, booking_request_id, type, status, scheduled_start, duration_minutes, format, scheduling_origin, created_at, updated_at, google_calendar_event_id, reminder_sent_at
`

type CreateAppointmentParams struct {
	ArtistID         uuid.UUID          `json:"artist_id"`
	BookingRequestID uuid.UUID          `json:"booking_request_id"`
	Type             string             `json:"type"`
	Status           string             `json:"status"`
	ScheduledStart   pgtype.Timestamptz `json:"scheduled_start"`
	DurationMinutes  int32              `json:"duration_minutes"`
	Format           *string            `json:"format"`
	SchedulingOrigin string             `json:"scheduling_origin"`
}

func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, createAppointment,
		arg.ArtistID,
		arg.BookingRequestID,
		arg.Type,
		arg.Status,
		arg.ScheduledStart,
		arg.DurationMinutes,
		arg.Format,
		arg.SchedulingOrigin,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.BookingRequestID,
		&i.Type,
		&i.Status,
		&i.ScheduledStart,
		&i.DurationMinutes,
		&i.Format,
		&i.SchedulingOrigin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleCalendarEventID,
		&i.ReminderSentAt,
	)
	return i, err
}

const getLatestAppointmentByRequest = `-- name: GetLatestAppointmentByRequest :one
SELECT id, artist_id, booking_request_id, type, status, scheduled_start, duration_minutes, format, scheduling_origin, created_at, updated_at, google_calendar_event_id, reminder_sent_at
FROM appointments
WHERE booking_request_id = $1
ORDER BY (status IN ('scheduled', 'proposed')) DESC, created_at DESC
LIMIT 1
`

// The request's "current" appointment: a live (scheduled/proposed) one if any,
// otherwise the most recent overall (so cancelled ones still surface for history).
func (q *Queries) GetLatestAppointmentByRequest(ctx context.Context, bookingRequestID uuid.UUID) (Appointment, error) {
	row := q.db.QueryRow(ctx, getLatestAppointmentByRequest, bookingRequestID)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.BookingRequestID,
		&i.Type,
		&i.Status,
		&i.ScheduledStart,
		&i.DurationMinutes,
		&i.Format,
		&i.SchedulingOrigin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleCalendarEventID,
		&i.ReminderSentAt,
	)
	return i, err
}

const listAppointmentsByArtistInRange = `-- name: ListAppointmentsByArtistInRange :many
SELECT
    a.id,
    a.booking_request_id,
    a.type,
    a.status,
    a.scheduled_start,
    a.duration_minutes,
    a.format,
    br.client_name,
    COALESCE(loc.label, '')   AS location_label,
    COALESCE(loc.address, '') AS location_address,
    COALESCE(loc.city, '')    AS location_city
FROM appointments a
JOIN booking_requests br ON br.id = a.booking_request_id
LEFT JOIN artist_locations loc ON loc.id = br.location_id
WHERE a.artist_id = $1
  AND a.scheduled_start IS NOT NULL
  AND a.status NOT IN ('cancelled', 'no_show')
  AND a.scheduled_start >= $2::timestamptz
  AND a.scheduled_start <  $3::timestamptz
ORDER BY a.scheduled_start
`

type ListAppointmentsByArtistInRangeParams struct {
	ArtistID   uuid.UUID          `json:"artist_id"`
	RangeStart pgtype.Timestamptz `json:"range_start"`
	RangeEnd   pgtype.Timestamptz `json:"range_end"`
}

type ListAppointmentsByArtistInRangeRow struct {
	ID               uuid.UUID          `json:"id"`
	BookingRequestID uuid.UUID          `json:"booking_request_id"`
	Type             string             `json:"type"`
	Status           string             `json:"status"`
	ScheduledStart   pgtype.Timestamptz `json:"scheduled_start"`
	DurationMinutes  int32              `json:"duration_minutes"`
	Format           *string            `json:"format"`
	ClientName       string             `json:"client_name"`
	LocationLabel    string             `json:"location_label"`
	LocationAddress  string             `json:"location_address"`
	LocationCity     string             `json:"location_city"`
}

// Scheduled (time-locked) appointments for the calendar, joined with their
// booking request and studio location. Proposed (no start) and cancelled/no-show
// appointments are excluded — they have no place on a time grid.
func (q *Queries) ListAppointmentsByArtistInRange(ctx context.Context, arg ListAppointmentsByArtistInRangeParams) ([]ListAppointmentsByArtistInRangeRow, error) {
	rows, err := q.db.Query(ctx, listAppointmentsByArtistInRange, arg.ArtistID, arg.RangeStart, arg.RangeEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAppointmentsByArtistInRangeRow
	for rows.Next() {
		var i ListAppointmentsByArtistInRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.BookingRequestID,
			&i.Type,
			&i.Status,
			&i.ScheduledStart,
			&i.DurationMinutes,
			&i.Format,
			&i.ClientName,
			&i.LocationLabel,
			&i.LocationAddress,
			&i.LocationCity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestAppointmentsByArtist = `-- name: ListLatestAppointmentsByArtist :many
SELECT DISTINCT ON (booking_request_id) id, artist_id, booking_request_id, type, status, scheduled_start, duration_minutes, format, scheduling_origin, created_at, updated_at, google_calendar_event_id, reminder_sent_at
FROM appointments
WHERE artist_id = $1
ORDER BY booking_request_id, (status IN ('scheduled', 'proposed')) DESC, created_at DESC
`

// The current appointment per request (live if any, else most recent), so the
// inbox list can show the scheduled/proposed state without an N+1 lookup.
func (q *Queries) ListLatestAppointmentsByArtist(ctx context.Context, artistID uuid.UUID) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, listLatestAppointmentsByArtist, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.ArtistID,
			&i.BookingRequestID,
			&i.Type,
			&i.Status,
			&i.ScheduledStart,
			&i.DurationMinutes,
			&i.Format,
			&i.SchedulingOrigin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GoogleCalendarEventID,
			&i.ReminderSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveAppointmentsByRequest = `-- name: ListLiveAppointmentsByRequest :many
SELECT id, artist_id, booking_request_id, type, status, scheduled_start, duration_minutes, format, scheduling_origin, created_at, updated_at, google_calendar_event_id, reminder_sent_at
FROM appointments
WHERE booking_request_id = $1 AND status IN ('scheduled', 'proposed')
ORDER BY created_at
`

func (q *Queries) ListLiveAppointmentsByRequest(ctx context.Context, bookingRequestID uuid.UUID) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, listLiveAppointmentsByRequest, bookingRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.ArtistID,
			&i.BookingRequestID,
			&i.Type,
			&i.Status,
			&i.ScheduledStart,
			&i.DurationMinutes,
			&i.Format,
			&i.SchedulingOrigin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GoogleCalendarEventID,
			&i.ReminderSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAppointmentCalendarEvent = `-- name: SetAppointmentCalendarEvent :exec
UPDATE appointments
SET google_calendar_event_id = $1::text,
    updated_at               = now()
WHERE id = $2
`

type SetAppointmentCalendarEventParams struct {
	GoogleCalendarEventID *string   `json:"google_calendar_event_id"`
	ID                    uuid.UUID `json:"id"`
}

func (q *Queries) SetAppointmentCalendarEvent(ctx context.Context, arg SetAppointmentCalendarEventParams) error {
	_, err := q.db.Exec(ctx, setAppointmentCalendarEvent, arg.GoogleCalendarEventID, arg.ID)
	return err
}

const updateAppointmentSchedule = `-- name: UpdateAppointmentSchedule :one
UPDATE appointments
SET scheduled_start  = $1::timestamptz,
    duration_minutes = COALESCE($2::integer, duration_minutes),
    format           = COALESCE($3::text, format),
    status           = 'scheduled',
    updated_at       = now()
WHERE id = $4 AND artist_id = $5
RETURNING id, artist_id, booking_request_id, type, status, scheduled_start, duration_minutes, format, scheduling_origin, created_at, updated_at, google_calendar_event_id, reminder_sent_at
`

type UpdateAppointmentScheduleParams struct {
	ScheduledStart  pgtype.Timestamptz `json:"scheduled_start"`
	DurationMinutes *int32             `json:"duration_minutes"`
	Format          *string            `json:"format"`
	ID              uuid.UUID          `json:"id"`
	ArtistID        uuid.UUID          `json:"artist_id"`
}

func (q *Queries) UpdateAppointmentSchedule(ctx context.Context, arg UpdateAppointmentScheduleParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, updateAppointmentSchedule,
		arg.ScheduledStart,
		arg.DurationMinutes,
		arg.Format,
		arg.ID,
		arg.ArtistID,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.BookingRequestID,
		&i.Type,
		&i.Status,
		&i.ScheduledStart,
		&i.DurationMinutes,
		&i.Format,
		&i.SchedulingOrigin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleCalendarEventID,
		&i.ReminderSentAt,
	)
	return i, err
}

const updateAppointmentStatus = `-- name: UpdateAppointmentStatus :one
UPDATE appointments
SET status     = $1,
    updated_at = now()
WHERE id = $2 AND artist_id = $3
RETURNING id, artist_id, booking_request_id, type, status, scheduled_start, duration_minutes, format, scheduling_origin, created_at, updated_at, google_calendar_event_id, reminder_sent_at
`

type UpdateAppointmentStatusParams struct {
	Status   string    `json:"status"`
	ID       uuid.UUID `json:"id"`
	ArtistID uuid.UUID `json:"artist_id"`
}

func (q *Queries) UpdateAppointmentStatus(ctx context.Context, arg UpdateAppointmentStatusParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, updateAppointmentStatus, arg.Status, arg.ID, arg.ArtistID)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.BookingRequestID,
		&i.Type,
		&i.Status,
		&i.ScheduledStart,
		&i.DurationMinutes,
		&i.Format,
		&i.SchedulingOrigin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleCalendarEventID,
		&i.ReminderSentAt,
	)
	return i, err
}
