// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artists.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const ensureArtist = `-- name: EnsureArtist :exec
INSERT INTO artists (user_id)
VALUES ($1)
ON CONFLICT (user_id) DO NOTHING
`

func (q *Queries) EnsureArtist(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, ensureArtist, userID)
	return err
}

const getArtistByUserID = `-- name: GetArtistByUserID :one
SELECT id, user_id, created_at, updated_at, onboarded_at FROM artists WHERE user_id = $1
`

func (q *Queries) GetArtistByUserID(ctx context.Context, userID uuid.UUID) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtistByUserID, userID)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OnboardedAt,
	)
	return i, err
}

const getArtistOnboardedAt = `-- name: GetArtistOnboardedAt :one
SELECT onboarded_at FROM artists WHERE user_id = $1
`

func (q *Queries) GetArtistOnboardedAt(ctx context.Context, userID uuid.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getArtistOnboardedAt, userID)
	var onboarded_at pgtype.Timestamptz
	err := row.Scan(&onboarded_at)
	return onboarded_at, err
}

const setArtistOnboardedAt = `-- name: SetArtistOnboardedAt :exec
UPDATE artists
SET onboarded_at = now(),
    updated_at   = now()
WHERE id = $1
`

func (q *Queries) SetArtistOnboardedAt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setArtistOnboardedAt, id)
	return err
}
