// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (client_id, artist_id, notes, estimated_hours, deposit_amount_cents)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, client_id, artist_id, status, notes, estimated_hours, deposit_amount_cents, scheduled_for, created_at, updated_at
`

type CreateBookingParams struct {
	ClientID           uuid.UUID      `json:"client_id"`
	ArtistID           uuid.UUID      `json:"artist_id"`
	Notes              string         `json:"notes"`
	EstimatedHours     pgtype.Numeric `json:"estimated_hours"`
	DepositAmountCents int64          `json:"deposit_amount_cents"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.ClientID,
		arg.ArtistID,
		arg.Notes,
		arg.EstimatedHours,
		arg.DepositAmountCents,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ArtistID,
		&i.Status,
		&i.Notes,
		&i.EstimatedHours,
		&i.DepositAmountCents,
		&i.ScheduledFor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBooking = `-- name: DeleteBooking :exec
DELETE FROM bookings WHERE id = $1
`

func (q *Queries) DeleteBooking(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBooking, id)
	return err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT id, client_id, artist_id, status, notes, estimated_hours, deposit_amount_cents, scheduled_for, created_at, updated_at FROM bookings WHERE id = $1
`

func (q *Queries) GetBookingByID(ctx context.Context, id uuid.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByID, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ArtistID,
		&i.Status,
		&i.Notes,
		&i.EstimatedHours,
		&i.DepositAmountCents,
		&i.ScheduledFor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBookingStatusHistory = `-- name: InsertBookingStatusHistory :one
INSERT INTO booking_status_history (booking_id, from_status, to_status, changed_by, note)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, booking_id, from_status, to_status, changed_by, note, created_at
`

type InsertBookingStatusHistoryParams struct {
	BookingID  uuid.UUID   `json:"booking_id"`
	FromStatus *string     `json:"from_status"`
	ToStatus   string      `json:"to_status"`
	ChangedBy  pgtype.UUID `json:"changed_by"`
	Note       *string     `json:"note"`
}

func (q *Queries) InsertBookingStatusHistory(ctx context.Context, arg InsertBookingStatusHistoryParams) (BookingStatusHistory, error) {
	row := q.db.QueryRow(ctx, insertBookingStatusHistory,
		arg.BookingID,
		arg.FromStatus,
		arg.ToStatus,
		arg.ChangedBy,
		arg.Note,
	)
	var i BookingStatusHistory
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.FromStatus,
		&i.ToStatus,
		&i.ChangedBy,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listBookingStatusHistory = `-- name: ListBookingStatusHistory :many
SELECT id, booking_id, from_status, to_status, changed_by, note, created_at FROM booking_status_history
WHERE booking_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListBookingStatusHistory(ctx context.Context, bookingID uuid.UUID) ([]BookingStatusHistory, error) {
	rows, err := q.db.Query(ctx, listBookingStatusHistory, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookingStatusHistory
	for rows.Next() {
		var i BookingStatusHistory
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.FromStatus,
			&i.ToStatus,
			&i.ChangedBy,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByArtist = `-- name: ListBookingsByArtist :many
SELECT id, client_id, artist_id, status, notes, estimated_hours, deposit_amount_cents, scheduled_for, created_at, updated_at FROM bookings
WHERE artist_id = $1
  AND ($2::text IS NULL OR status = $2)
ORDER BY created_at DESC
LIMIT $4
OFFSET $3
`

type ListBookingsByArtistParams struct {
	ArtistID uuid.UUID `json:"artist_id"`
	Status   *string   `json:"status"`
	Off      int32     `json:"off"`
	Lim      int32     `json:"lim"`
}

func (q *Queries) ListBookingsByArtist(ctx context.Context, arg ListBookingsByArtistParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookingsByArtist,
		arg.ArtistID,
		arg.Status,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ArtistID,
			&i.Status,
			&i.Notes,
			&i.EstimatedHours,
			&i.DepositAmountCents,
			&i.ScheduledFor,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByClient = `-- name: ListBookingsByClient :many
SELECT id, client_id, artist_id, status, notes, estimated_hours, deposit_amount_cents, scheduled_for, created_at, updated_at FROM bookings
WHERE client_id = $1
  AND ($2::text IS NULL OR status = $2)
ORDER BY created_at DESC
LIMIT $4
OFFSET $3
`

type ListBookingsByClientParams struct {
	ClientID uuid.UUID `json:"client_id"`
	Status   *string   `json:"status"`
	Off      int32     `json:"off"`
	Lim      int32     `json:"lim"`
}

func (q *Queries) ListBookingsByClient(ctx context.Context, arg ListBookingsByClientParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookingsByClient,
		arg.ClientID,
		arg.Status,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ArtistID,
			&i.Status,
			&i.Notes,
			&i.EstimatedHours,
			&i.DepositAmountCents,
			&i.ScheduledFor,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookingNotes = `-- name: UpdateBookingNotes :one
UPDATE bookings
SET notes                = COALESCE($1::text, notes),
    estimated_hours      = COALESCE($2::numeric, estimated_hours),
    deposit_amount_cents = COALESCE($3::bigint, deposit_amount_cents),
    updated_at           = now()
WHERE id = $4
RETURNING id, client_id, artist_id, status, notes, estimated_hours, deposit_amount_cents, scheduled_for, created_at, updated_at
`

type UpdateBookingNotesParams struct {
	Notes              *string        `json:"notes"`
	EstimatedHours     pgtype.Numeric `json:"estimated_hours"`
	DepositAmountCents *int64         `json:"deposit_amount_cents"`
	ID                 uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateBookingNotes(ctx context.Context, arg UpdateBookingNotesParams) (Booking, error) {
	row := q.db.QueryRow(ctx, updateBookingNotes,
		arg.Notes,
		arg.EstimatedHours,
		arg.DepositAmountCents,
		arg.ID,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ArtistID,
		&i.Status,
		&i.Notes,
		&i.EstimatedHours,
		&i.DepositAmountCents,
		&i.ScheduledFor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBookingSchedule = `-- name: UpdateBookingSchedule :one
UPDATE bookings
SET scheduled_for = $2,
    updated_at    = now()
WHERE id = $1
RETURNING id, client_id, artist_id, status, notes, estimated_hours, deposit_amount_cents, scheduled_for, created_at, updated_at
`

type UpdateBookingScheduleParams struct {
	ID           uuid.UUID          `json:"id"`
	ScheduledFor pgtype.Timestamptz `json:"scheduled_for"`
}

func (q *Queries) UpdateBookingSchedule(ctx context.Context, arg UpdateBookingScheduleParams) (Booking, error) {
	row := q.db.QueryRow(ctx, updateBookingSchedule, arg.ID, arg.ScheduledFor)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ArtistID,
		&i.Status,
		&i.Notes,
		&i.EstimatedHours,
		&i.DepositAmountCents,
		&i.ScheduledFor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBookingStatus = `-- name: UpdateBookingStatus :one
UPDATE bookings
SET status     = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, client_id, artist_id, status, notes, estimated_hours, deposit_amount_cents, scheduled_for, created_at, updated_at
`

type UpdateBookingStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) (Booking, error) {
	row := q.db.QueryRow(ctx, updateBookingStatus, arg.ID, arg.Status)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ArtistID,
		&i.Status,
		&i.Notes,
		&i.EstimatedHours,
		&i.DepositAmountCents,
		&i.ScheduledFor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
