// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: booking_requests.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBookingRequest = `-- name: CreateBookingRequest :one
INSERT INTO booking_requests (
    artist_id, open_book_id, type, flash_id, description, reference_image_keys,
    placement, approx_size_inches, styles, client_availability, custom_answers,
    client_name, client_email, client_phone, status, deposit_status, waiver_status
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16, $17
)
RETURNING id, artist_id, open_book_id, type, flash_id, description, reference_image_keys, placement, approx_size_inches, client_availability, client_name, client_email, client_phone, status, deposit_status, waiver_status, session_duration_minutes, client_user_id, created_at, updated_at, decided_at, styles, custom_answers
`

type CreateBookingRequestParams struct {
	ArtistID           uuid.UUID   `json:"artist_id"`
	OpenBookID         uuid.UUID   `json:"open_book_id"`
	Type               string      `json:"type"`
	FlashID            pgtype.UUID `json:"flash_id"`
	Description        string      `json:"description"`
	ReferenceImageKeys []string    `json:"reference_image_keys"`
	Placement          string      `json:"placement"`
	ApproxSizeInches   *int32      `json:"approx_size_inches"`
	Styles             []string    `json:"styles"`
	ClientAvailability []byte      `json:"client_availability"`
	CustomAnswers      []byte      `json:"custom_answers"`
	ClientName         string      `json:"client_name"`
	ClientEmail        string      `json:"client_email"`
	ClientPhone        *string     `json:"client_phone"`
	Status             string      `json:"status"`
	DepositStatus      string      `json:"deposit_status"`
	WaiverStatus       string      `json:"waiver_status"`
}

func (q *Queries) CreateBookingRequest(ctx context.Context, arg CreateBookingRequestParams) (BookingRequest, error) {
	row := q.db.QueryRow(ctx, createBookingRequest,
		arg.ArtistID,
		arg.OpenBookID,
		arg.Type,
		arg.FlashID,
		arg.Description,
		arg.ReferenceImageKeys,
		arg.Placement,
		arg.ApproxSizeInches,
		arg.Styles,
		arg.ClientAvailability,
		arg.CustomAnswers,
		arg.ClientName,
		arg.ClientEmail,
		arg.ClientPhone,
		arg.Status,
		arg.DepositStatus,
		arg.WaiverStatus,
	)
	var i BookingRequest
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.OpenBookID,
		&i.Type,
		&i.FlashID,
		&i.Description,
		&i.ReferenceImageKeys,
		&i.Placement,
		&i.ApproxSizeInches,
		&i.ClientAvailability,
		&i.ClientName,
		&i.ClientEmail,
		&i.ClientPhone,
		&i.Status,
		&i.DepositStatus,
		&i.WaiverStatus,
		&i.SessionDurationMinutes,
		&i.ClientUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DecidedAt,
		&i.Styles,
		&i.CustomAnswers,
	)
	return i, err
}

const getBookingRequest = `-- name: GetBookingRequest :one
SELECT id, artist_id, open_book_id, type, flash_id, description, reference_image_keys, placement, approx_size_inches, client_availability, client_name, client_email, client_phone, status, deposit_status, waiver_status, session_duration_minutes, client_user_id, created_at, updated_at, decided_at, styles, custom_answers
FROM booking_requests
WHERE id = $1 AND artist_id = $2
`

type GetBookingRequestParams struct {
	ID       uuid.UUID `json:"id"`
	ArtistID uuid.UUID `json:"artist_id"`
}

func (q *Queries) GetBookingRequest(ctx context.Context, arg GetBookingRequestParams) (BookingRequest, error) {
	row := q.db.QueryRow(ctx, getBookingRequest, arg.ID, arg.ArtistID)
	var i BookingRequest
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.OpenBookID,
		&i.Type,
		&i.FlashID,
		&i.Description,
		&i.ReferenceImageKeys,
		&i.Placement,
		&i.ApproxSizeInches,
		&i.ClientAvailability,
		&i.ClientName,
		&i.ClientEmail,
		&i.ClientPhone,
		&i.Status,
		&i.DepositStatus,
		&i.WaiverStatus,
		&i.SessionDurationMinutes,
		&i.ClientUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DecidedAt,
		&i.Styles,
		&i.CustomAnswers,
	)
	return i, err
}

const getBookingStats = `-- name: GetBookingStats :one
SELECT
    COUNT(*) FILTER (WHERE status = 'pending')        AS new_inquiries,
    COUNT(*) FILTER (WHERE deposit_status = 'pending') AS awaiting_deposit,
    COUNT(*) FILTER (
        WHERE status IN ('accepted', 'converted')
          AND decided_at >= date_trunc('month', now())
    )                                                  AS booked_this_month
FROM booking_requests
WHERE artist_id = $1
`

type GetBookingStatsRow struct {
	NewInquiries    int64 `json:"new_inquiries"`
	AwaitingDeposit int64 `json:"awaiting_deposit"`
	BookedThisMonth int64 `json:"booked_this_month"`
}

// Counts that back the dashboard stat cards.
func (q *Queries) GetBookingStats(ctx context.Context, artistID uuid.UUID) (GetBookingStatsRow, error) {
	row := q.db.QueryRow(ctx, getBookingStats, artistID)
	var i GetBookingStatsRow
	err := row.Scan(&i.NewInquiries, &i.AwaitingDeposit, &i.BookedThisMonth)
	return i, err
}

const listBookingRequestsByArtist = `-- name: ListBookingRequestsByArtist :many
SELECT id, artist_id, open_book_id, type, flash_id, description, reference_image_keys, placement, approx_size_inches, client_availability, client_name, client_email, client_phone, status, deposit_status, waiver_status, session_duration_minutes, client_user_id, created_at, updated_at, decided_at, styles, custom_answers
FROM booking_requests
WHERE artist_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListBookingRequestsByArtist(ctx context.Context, artistID uuid.UUID) ([]BookingRequest, error) {
	rows, err := q.db.Query(ctx, listBookingRequestsByArtist, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookingRequest
	for rows.Next() {
		var i BookingRequest
		if err := rows.Scan(
			&i.ID,
			&i.ArtistID,
			&i.OpenBookID,
			&i.Type,
			&i.FlashID,
			&i.Description,
			&i.ReferenceImageKeys,
			&i.Placement,
			&i.ApproxSizeInches,
			&i.ClientAvailability,
			&i.ClientName,
			&i.ClientEmail,
			&i.ClientPhone,
			&i.Status,
			&i.DepositStatus,
			&i.WaiverStatus,
			&i.SessionDurationMinutes,
			&i.ClientUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DecidedAt,
			&i.Styles,
			&i.CustomAnswers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reopenBookingRequest = `-- name: ReopenBookingRequest :one
UPDATE booking_requests
SET status         = 'pending',
    deposit_status = 'not_required',
    decided_at     = NULL,
    updated_at     = now()
WHERE id = $1 AND artist_id = $2
RETURNING id, artist_id, open_book_id, type, flash_id, description, reference_image_keys, placement, approx_size_inches, client_availability, client_name, client_email, client_phone, status, deposit_status, waiver_status, session_duration_minutes, client_user_id, created_at, updated_at, decided_at, styles, custom_answers
`

type ReopenBookingRequestParams struct {
	ID       uuid.UUID `json:"id"`
	ArtistID uuid.UUID `json:"artist_id"`
}

// Undo a decision: return the request to the inbox as a fresh (pending) lead.
func (q *Queries) ReopenBookingRequest(ctx context.Context, arg ReopenBookingRequestParams) (BookingRequest, error) {
	row := q.db.QueryRow(ctx, reopenBookingRequest, arg.ID, arg.ArtistID)
	var i BookingRequest
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.OpenBookID,
		&i.Type,
		&i.FlashID,
		&i.Description,
		&i.ReferenceImageKeys,
		&i.Placement,
		&i.ApproxSizeInches,
		&i.ClientAvailability,
		&i.ClientName,
		&i.ClientEmail,
		&i.ClientPhone,
		&i.Status,
		&i.DepositStatus,
		&i.WaiverStatus,
		&i.SessionDurationMinutes,
		&i.ClientUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DecidedAt,
		&i.Styles,
		&i.CustomAnswers,
	)
	return i, err
}

const updateBookingRequestStatus = `-- name: UpdateBookingRequestStatus :one
UPDATE booking_requests
SET status                   = $1::text,
    session_duration_minutes = COALESCE($2::integer, session_duration_minutes),
    deposit_status           = COALESCE($3::text, deposit_status),
    decided_at               = now(),
    updated_at               = now()
WHERE id = $4 AND artist_id = $5
RETURNING id, artist_id, open_book_id, type, flash_id, description, reference_image_keys, placement, approx_size_inches, client_availability, client_name, client_email, client_phone, status, deposit_status, waiver_status, session_duration_minutes, client_user_id, created_at, updated_at, decided_at, styles, custom_answers
`

type UpdateBookingRequestStatusParams struct {
	Status                 string    `json:"status"`
	SessionDurationMinutes *int32    `json:"session_duration_minutes"`
	DepositStatus          *string   `json:"deposit_status"`
	ID                     uuid.UUID `json:"id"`
	ArtistID               uuid.UUID `json:"artist_id"`
}

func (q *Queries) UpdateBookingRequestStatus(ctx context.Context, arg UpdateBookingRequestStatusParams) (BookingRequest, error) {
	row := q.db.QueryRow(ctx, updateBookingRequestStatus,
		arg.Status,
		arg.SessionDurationMinutes,
		arg.DepositStatus,
		arg.ID,
		arg.ArtistID,
	)
	var i BookingRequest
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.OpenBookID,
		&i.Type,
		&i.FlashID,
		&i.Description,
		&i.ReferenceImageKeys,
		&i.Placement,
		&i.ApproxSizeInches,
		&i.ClientAvailability,
		&i.ClientName,
		&i.ClientEmail,
		&i.ClientPhone,
		&i.Status,
		&i.DepositStatus,
		&i.WaiverStatus,
		&i.SessionDurationMinutes,
		&i.ClientUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DecidedAt,
		&i.Styles,
		&i.CustomAnswers,
	)
	return i, err
}
