// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getArtistDisplayName = `-- name: GetArtistDisplayName :one
SELECT COALESCE(
    NULLIF(TRIM(COALESCE(u.first_name, '') || ' ' || COALESCE(u.last_name, '')), ''),
    u.username,
    ''
)::text AS display_name
FROM artists a
JOIN users u ON u.id = a.user_id
WHERE a.id = $1
`

func (q *Queries) GetArtistDisplayName(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getArtistDisplayName, id)
	var display_name string
	err := row.Scan(&display_name)
	return display_name, err
}

const getBookingRequestPhone = `-- name: GetBookingRequestPhone :one
SELECT client_phone FROM booking_requests WHERE id = $1
`

func (q *Queries) GetBookingRequestPhone(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getBookingRequestPhone, id)
	var client_phone string
	err := row.Scan(&client_phone)
	return client_phone, err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT id, artist_id, booking_request_id, client_name, client_email, client_access_token, status, last_message_at, artist_last_read_at, client_last_read_at, created_at, updated_at FROM conversations WHERE id = $1
`

func (q *Queries) GetConversationByID(ctx context.Context, id uuid.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationByID, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.BookingRequestID,
		&i.ClientName,
		&i.ClientEmail,
		&i.ClientAccessToken,
		&i.Status,
		&i.LastMessageAt,
		&i.ArtistLastReadAt,
		&i.ClientLastReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationByToken = `-- name: GetConversationByToken :one
SELECT id, artist_id, booking_request_id, client_name, client_email, client_access_token, status, last_message_at, artist_last_read_at, client_last_read_at, created_at, updated_at FROM conversations WHERE client_access_token = $1
`

func (q *Queries) GetConversationByToken(ctx context.Context, clientAccessToken string) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationByToken, clientAccessToken)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.BookingRequestID,
		&i.ClientName,
		&i.ClientEmail,
		&i.ClientAccessToken,
		&i.Status,
		&i.LastMessageAt,
		&i.ArtistLastReadAt,
		&i.ClientLastReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationForArtist = `-- name: GetConversationForArtist :one
SELECT id, artist_id, booking_request_id, client_name, client_email, client_access_token, status, last_message_at, artist_last_read_at, client_last_read_at, created_at, updated_at FROM conversations WHERE id = $1 AND artist_id = $2
`

type GetConversationForArtistParams struct {
	ID       uuid.UUID `json:"id"`
	ArtistID uuid.UUID `json:"artist_id"`
}

func (q *Queries) GetConversationForArtist(ctx context.Context, arg GetConversationForArtistParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationForArtist, arg.ID, arg.ArtistID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.BookingRequestID,
		&i.ClientName,
		&i.ClientEmail,
		&i.ClientAccessToken,
		&i.Status,
		&i.LastMessageAt,
		&i.ArtistLastReadAt,
		&i.ClientLastReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationForClient = `-- name: GetConversationForClient :one
SELECT id, artist_id, booking_request_id, client_name, client_email, client_access_token, status, last_message_at, artist_last_read_at, client_last_read_at, created_at, updated_at FROM conversations WHERE id = $1 AND client_email = $2
`

type GetConversationForClientParams struct {
	ID          uuid.UUID `json:"id"`
	ClientEmail string    `json:"client_email"`
}

func (q *Queries) GetConversationForClient(ctx context.Context, arg GetConversationForClientParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationForClient, arg.ID, arg.ClientEmail)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.BookingRequestID,
		&i.ClientName,
		&i.ClientEmail,
		&i.ClientAccessToken,
		&i.Status,
		&i.LastMessageAt,
		&i.ArtistLastReadAt,
		&i.ClientLastReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrCreateConversation = `-- name: GetOrCreateConversation :one
INSERT INTO conversations (artist_id, booking_request_id, client_name, client_email, client_access_token)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (artist_id, client_email)
DO UPDATE SET updated_at = conversations.updated_at
RETURNING id, artist_id, booking_request_id, client_name, client_email, client_access_token, status, last_message_at, artist_last_read_at, client_last_read_at, created_at, updated_at
`

type GetOrCreateConversationParams struct {
	ArtistID          uuid.UUID `json:"artist_id"`
	BookingRequestID  uuid.UUID `json:"booking_request_id"`
	ClientName        string    `json:"client_name"`
	ClientEmail       string    `json:"client_email"`
	ClientAccessToken string    `json:"client_access_token"`
}

func (q *Queries) GetOrCreateConversation(ctx context.Context, arg GetOrCreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getOrCreateConversation,
		arg.ArtistID,
		arg.BookingRequestID,
		arg.ClientName,
		arg.ClientEmail,
		arg.ClientAccessToken,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.BookingRequestID,
		&i.ClientName,
		&i.ClientEmail,
		&i.ClientAccessToken,
		&i.Status,
		&i.LastMessageAt,
		&i.ArtistLastReadAt,
		&i.ClientLastReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConversationFlagsForArtist = `-- name: ListConversationFlagsForArtist :many
SELECT
    c.id,
    c.client_email,
    EXISTS(
        SELECT 1 FROM messages m
        WHERE m.conversation_id = c.id AND m.sender_type = 'artist'
    )::boolean AS artist_replied
FROM conversations c
WHERE c.artist_id = $1
`

type ListConversationFlagsForArtistRow struct {
	ID            uuid.UUID `json:"id"`
	ClientEmail   string    `json:"client_email"`
	ArtistReplied bool      `json:"artist_replied"`
}

func (q *Queries) ListConversationFlagsForArtist(ctx context.Context, artistID uuid.UUID) ([]ListConversationFlagsForArtistRow, error) {
	rows, err := q.db.Query(ctx, listConversationFlagsForArtist, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationFlagsForArtistRow
	for rows.Next() {
		var i ListConversationFlagsForArtistRow
		if err := rows.Scan(&i.ID, &i.ClientEmail, &i.ArtistReplied); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationsForArtist = `-- name: ListConversationsForArtist :many
SELECT
    c.id, c.artist_id, c.booking_request_id, c.client_name, c.client_email, c.client_access_token, c.status, c.last_message_at, c.artist_last_read_at, c.client_last_read_at, c.created_at, c.updated_at,
    COALESCE((
        SELECT m.body FROM messages m
        WHERE m.conversation_id = c.id
        ORDER BY m.created_at DESC LIMIT 1
    ), '')::text AS last_message_body,
    COALESCE((
        SELECT m.sender_type = 'client'
               AND (c.artist_last_read_at IS NULL OR m.created_at > c.artist_last_read_at)
        FROM messages m
        WHERE m.conversation_id = c.id
        ORDER BY m.created_at DESC LIMIT 1
    ), false)::boolean AS has_unread
FROM conversations c
WHERE c.artist_id = $1
ORDER BY c.last_message_at DESC NULLS LAST, c.created_at DESC
`

type ListConversationsForArtistRow struct {
	ID                uuid.UUID          `json:"id"`
	ArtistID          uuid.UUID          `json:"artist_id"`
	BookingRequestID  uuid.UUID          `json:"booking_request_id"`
	ClientName        string             `json:"client_name"`
	ClientEmail       string             `json:"client_email"`
	ClientAccessToken string             `json:"client_access_token"`
	Status            string             `json:"status"`
	LastMessageAt     pgtype.Timestamptz `json:"last_message_at"`
	ArtistLastReadAt  pgtype.Timestamptz `json:"artist_last_read_at"`
	ClientLastReadAt  pgtype.Timestamptz `json:"client_last_read_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	LastMessageBody   string             `json:"last_message_body"`
	HasUnread         bool               `json:"has_unread"`
}

func (q *Queries) ListConversationsForArtist(ctx context.Context, artistID uuid.UUID) ([]ListConversationsForArtistRow, error) {
	rows, err := q.db.Query(ctx, listConversationsForArtist, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationsForArtistRow
	for rows.Next() {
		var i ListConversationsForArtistRow
		if err := rows.Scan(
			&i.ID,
			&i.ArtistID,
			&i.BookingRequestID,
			&i.ClientName,
			&i.ClientEmail,
			&i.ClientAccessToken,
			&i.Status,
			&i.LastMessageAt,
			&i.ArtistLastReadAt,
			&i.ClientLastReadAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastMessageBody,
			&i.HasUnread,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationsForClient = `-- name: ListConversationsForClient :many
SELECT
    c.id, c.artist_id, c.booking_request_id, c.client_name, c.client_email, c.client_access_token, c.status, c.last_message_at, c.artist_last_read_at, c.client_last_read_at, c.created_at, c.updated_at,
    COALESCE(
        NULLIF(TRIM(COALESCE(u.first_name, '') || ' ' || COALESCE(u.last_name, '')), ''),
        u.username,
        ''
    )::text AS artist_name,
    COALESCE((
        SELECT m.body FROM messages m
        WHERE m.conversation_id = c.id
        ORDER BY m.created_at DESC LIMIT 1
    ), '')::text AS last_message_body,
    COALESCE((
        SELECT m.sender_type = 'artist'
               AND (c.client_last_read_at IS NULL OR m.created_at > c.client_last_read_at)
        FROM messages m
        WHERE m.conversation_id = c.id
        ORDER BY m.created_at DESC LIMIT 1
    ), false)::boolean AS has_unread
FROM conversations c
JOIN artists a ON a.id = c.artist_id
JOIN users u ON u.id = a.user_id
WHERE c.client_email = $1
ORDER BY c.last_message_at DESC NULLS LAST, c.created_at DESC
`

type ListConversationsForClientRow struct {
	ID                uuid.UUID          `json:"id"`
	ArtistID          uuid.UUID          `json:"artist_id"`
	BookingRequestID  uuid.UUID          `json:"booking_request_id"`
	ClientName        string             `json:"client_name"`
	ClientEmail       string             `json:"client_email"`
	ClientAccessToken string             `json:"client_access_token"`
	Status            string             `json:"status"`
	LastMessageAt     pgtype.Timestamptz `json:"last_message_at"`
	ArtistLastReadAt  pgtype.Timestamptz `json:"artist_last_read_at"`
	ClientLastReadAt  pgtype.Timestamptz `json:"client_last_read_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ArtistName        string             `json:"artist_name"`
	LastMessageBody   string             `json:"last_message_body"`
	HasUnread         bool               `json:"has_unread"`
}

func (q *Queries) ListConversationsForClient(ctx context.Context, clientEmail string) ([]ListConversationsForClientRow, error) {
	rows, err := q.db.Query(ctx, listConversationsForClient, clientEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationsForClientRow
	for rows.Next() {
		var i ListConversationsForClientRow
		if err := rows.Scan(
			&i.ID,
			&i.ArtistID,
			&i.BookingRequestID,
			&i.ClientName,
			&i.ClientEmail,
			&i.ClientAccessToken,
			&i.Status,
			&i.LastMessageAt,
			&i.ArtistLastReadAt,
			&i.ClientLastReadAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArtistName,
			&i.LastMessageBody,
			&i.HasUnread,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markConversationReadByArtist = `-- name: MarkConversationReadByArtist :exec
UPDATE conversations
SET artist_last_read_at = now(), updated_at = now()
WHERE id = $1 AND artist_id = $2
`

type MarkConversationReadByArtistParams struct {
	ID       uuid.UUID `json:"id"`
	ArtistID uuid.UUID `json:"artist_id"`
}

func (q *Queries) MarkConversationReadByArtist(ctx context.Context, arg MarkConversationReadByArtistParams) error {
	_, err := q.db.Exec(ctx, markConversationReadByArtist, arg.ID, arg.ArtistID)
	return err
}

const markConversationReadByClient = `-- name: MarkConversationReadByClient :exec
UPDATE conversations
SET client_last_read_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkConversationReadByClient(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markConversationReadByClient, id)
	return err
}

const touchConversationAfterSend = `-- name: TouchConversationAfterSend :exec
UPDATE conversations
SET last_message_at     = now(),
    updated_at          = now(),
    artist_last_read_at = CASE WHEN $1::text = 'artist' THEN now() ELSE artist_last_read_at END,
    client_last_read_at = CASE WHEN $1::text = 'client' THEN now() ELSE client_last_read_at END
WHERE id = $2
`

type TouchConversationAfterSendParams struct {
	SenderType string    `json:"sender_type"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) TouchConversationAfterSend(ctx context.Context, arg TouchConversationAfterSendParams) error {
	_, err := q.db.Exec(ctx, touchConversationAfterSend, arg.SenderType, arg.ID)
	return err
}
