// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getBookingMixForRange = `-- name: GetBookingMixForRange :one
SELECT
    COUNT(*) FILTER (
        WHERE type = 'custom'
          AND status IN ('accepted', 'converted')
          AND decided_at >= $1
    )                                                   AS current_custom,
    COUNT(*) FILTER (
        WHERE type = 'flash'
          AND status IN ('accepted', 'converted')
          AND decided_at >= $1
    )                                                   AS current_flash,
    COUNT(*) FILTER (
        WHERE status IN ('accepted', 'converted')
          AND decided_at >= $2
          AND decided_at <  $1
    )                                                   AS prev_bookings
FROM booking_requests
WHERE artist_id = $3
`

type GetBookingMixForRangeParams struct {
	CurrentStart pgtype.Timestamptz `json:"current_start"`
	PrevStart    pgtype.Timestamptz `json:"prev_start"`
	ArtistID     uuid.UUID          `json:"artist_id"`
}

type GetBookingMixForRangeRow struct {
	CurrentCustom int64 `json:"current_custom"`
	CurrentFlash  int64 `json:"current_flash"`
	PrevBookings  int64 `json:"prev_bookings"`
}

func (q *Queries) GetBookingMixForRange(ctx context.Context, arg GetBookingMixForRangeParams) (GetBookingMixForRangeRow, error) {
	row := q.db.QueryRow(ctx, getBookingMixForRange, arg.CurrentStart, arg.PrevStart, arg.ArtistID)
	var i GetBookingMixForRangeRow
	err := row.Scan(&i.CurrentCustom, &i.CurrentFlash, &i.PrevBookings)
	return i, err
}

const getDashboardCounts = `-- name: GetDashboardCounts :one
SELECT
    COUNT(*) FILTER (WHERE status = 'pending')          AS new_inquiries,
    COUNT(*) FILTER (WHERE deposit_status = 'pending')  AS awaiting_deposit,
    COUNT(*) FILTER (WHERE status = 'accepted')         AS scheduled,
    COUNT(*) FILTER (
        WHERE created_at >= date_trunc('month', now())
    )                                                   AS leads_this_month,
    COUNT(*) FILTER (
        WHERE created_at >= date_trunc('month', now()) - interval '1 month'
          AND created_at <  date_trunc('month', now())
    )                                                   AS leads_last_month
FROM booking_requests
WHERE artist_id = $1
`

type GetDashboardCountsRow struct {
	NewInquiries    int64 `json:"new_inquiries"`
	AwaitingDeposit int64 `json:"awaiting_deposit"`
	Scheduled       int64 `json:"scheduled"`
	LeadsThisMonth  int64 `json:"leads_this_month"`
	LeadsLastMonth  int64 `json:"leads_last_month"`
}

func (q *Queries) GetDashboardCounts(ctx context.Context, artistID uuid.UUID) (GetDashboardCountsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardCounts, artistID)
	var i GetDashboardCountsRow
	err := row.Scan(
		&i.NewInquiries,
		&i.AwaitingDeposit,
		&i.Scheduled,
		&i.LeadsThisMonth,
		&i.LeadsLastMonth,
	)
	return i, err
}

const getMonthlyEarnings = `-- name: GetMonthlyEarnings :many
SELECT
    date_trunc('month', paid_at)::timestamptz                 AS month,
    COALESCE(SUM(client_charge_cents), 0)::bigint             AS collected_cents,
    COALESCE(SUM(client_charge_cents - platform_fee_cents), 0)::bigint AS net_cents
FROM payment_requests
WHERE artist_id = $1
  AND status = 'paid'
  AND paid_at >= $2
GROUP BY 1
ORDER BY 1
`

type GetMonthlyEarningsParams struct {
	ArtistID uuid.UUID          `json:"artist_id"`
	Since    pgtype.Timestamptz `json:"since"`
}

type GetMonthlyEarningsRow struct {
	Month          pgtype.Timestamptz `json:"month"`
	CollectedCents int64              `json:"collected_cents"`
	NetCents       int64              `json:"net_cents"`
}

func (q *Queries) GetMonthlyEarnings(ctx context.Context, arg GetMonthlyEarningsParams) ([]GetMonthlyEarningsRow, error) {
	rows, err := q.db.Query(ctx, getMonthlyEarnings, arg.ArtistID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMonthlyEarningsRow
	for rows.Next() {
		var i GetMonthlyEarningsRow
		if err := rows.Scan(&i.Month, &i.CollectedCents, &i.NetCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingAppointments = `-- name: ListUpcomingAppointments :many
SELECT
    a.id,
    a.type,
    a.scheduled_start,
    a.duration_minutes,
    br.client_name,
    br.client_email,
    br.type AS request_type
FROM appointments a
JOIN booking_requests br ON br.id = a.booking_request_id
WHERE a.artist_id = $1
  AND a.status = 'scheduled'
  AND a.scheduled_start >= now()
ORDER BY a.scheduled_start ASC
LIMIT 6
`

type ListUpcomingAppointmentsRow struct {
	ID              uuid.UUID          `json:"id"`
	Type            string             `json:"type"`
	ScheduledStart  pgtype.Timestamptz `json:"scheduled_start"`
	DurationMinutes int32              `json:"duration_minutes"`
	ClientName      string             `json:"client_name"`
	ClientEmail     string             `json:"client_email"`
	RequestType     string             `json:"request_type"`
}

func (q *Queries) ListUpcomingAppointments(ctx context.Context, artistID uuid.UUID) ([]ListUpcomingAppointmentsRow, error) {
	rows, err := q.db.Query(ctx, listUpcomingAppointments, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUpcomingAppointmentsRow
	for rows.Next() {
		var i ListUpcomingAppointmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.ScheduledStart,
			&i.DurationMinutes,
			&i.ClientName,
			&i.ClientEmail,
			&i.RequestType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
