// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: flashes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveFlash = `-- name: ArchiveFlash :one
UPDATE flashes
SET status      = 'archived',
    archived_at = now(),
    updated_at  = now()
WHERE id = $1
  AND status <> 'archived'
RETURNING id, artist_id, status, title, description, s3_key, reference_s3_key, color_type, styles, placements, pricing_mode, flat_price_cents, flat_duration_minutes, deposit_cents, repeatable, claimed_at, claimed_by_booking_id, archived_at, published_at, view_count, save_count, created_at, updated_at
`

func (q *Queries) ArchiveFlash(ctx context.Context, id uuid.UUID) (Flash, error) {
	row := q.db.QueryRow(ctx, archiveFlash, id)
	var i Flash
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.S3Key,
		&i.ReferenceS3Key,
		&i.ColorType,
		&i.Styles,
		&i.Placements,
		&i.PricingMode,
		&i.FlatPriceCents,
		&i.FlatDurationMinutes,
		&i.DepositCents,
		&i.Repeatable,
		&i.ClaimedAt,
		&i.ClaimedByBookingID,
		&i.ArchivedAt,
		&i.PublishedAt,
		&i.ViewCount,
		&i.SaveCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimFlash = `-- name: ClaimFlash :one
UPDATE flashes
SET status                = 'claimed',
    claimed_at            = now(),
    claimed_by_booking_id = $1,
    updated_at            = now()
WHERE id = $2
  AND status = 'available'
RETURNING id, artist_id, status, title, description, s3_key, reference_s3_key, color_type, styles, placements, pricing_mode, flat_price_cents, flat_duration_minutes, deposit_cents, repeatable, claimed_at, claimed_by_booking_id, archived_at, published_at, view_count, save_count, created_at, updated_at
`

type ClaimFlashParams struct {
	ClaimedByBookingID pgtype.UUID `json:"claimed_by_booking_id"`
	ID                 uuid.UUID   `json:"id"`
}

func (q *Queries) ClaimFlash(ctx context.Context, arg ClaimFlashParams) (Flash, error) {
	row := q.db.QueryRow(ctx, claimFlash, arg.ClaimedByBookingID, arg.ID)
	var i Flash
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.S3Key,
		&i.ReferenceS3Key,
		&i.ColorType,
		&i.Styles,
		&i.Placements,
		&i.PricingMode,
		&i.FlatPriceCents,
		&i.FlatDurationMinutes,
		&i.DepositCents,
		&i.Repeatable,
		&i.ClaimedAt,
		&i.ClaimedByBookingID,
		&i.ArchivedAt,
		&i.PublishedAt,
		&i.ViewCount,
		&i.SaveCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countFlashesByArtist = `-- name: CountFlashesByArtist :one
SELECT
    COUNT(*) FILTER (
        WHERE $1::text IS NULL OR status = $1
    )                                                     AS total,
    COUNT(*) FILTER (WHERE status = 'available')          AS available
FROM flashes
WHERE artist_id = $2
`

type CountFlashesByArtistParams struct {
	Status   *string   `json:"status"`
	ArtistID uuid.UUID `json:"artist_id"`
}

type CountFlashesByArtistRow struct {
	Total     int64 `json:"total"`
	Available int64 `json:"available"`
}

func (q *Queries) CountFlashesByArtist(ctx context.Context, arg CountFlashesByArtistParams) (CountFlashesByArtistRow, error) {
	row := q.db.QueryRow(ctx, countFlashesByArtist, arg.Status, arg.ArtistID)
	var i CountFlashesByArtistRow
	err := row.Scan(&i.Total, &i.Available)
	return i, err
}

const createFlash = `-- name: CreateFlash :one
INSERT INTO flashes (
    artist_id,
    status,
    title,
    description,
    s3_key,
    reference_s3_key,
    color_type,
    styles,
    placements,
    pricing_mode,
    flat_price_cents,
    flat_duration_minutes,
    deposit_cents,
    repeatable,
    published_at
)
VALUES (
    $1,
    $2,
    $3,
    $4::text,
    $5::text,
    $6::text,
    $7,
    $8::text[],
    $9::text[],
    $10,
    $11::bigint,
    $12::integer,
    $13::bigint,
    $14,
    $15::timestamptz
)
RETURNING id, artist_id, status, title, description, s3_key, reference_s3_key, color_type, styles, placements, pricing_mode, flat_price_cents, flat_duration_minutes, deposit_cents, repeatable, claimed_at, claimed_by_booking_id, archived_at, published_at, view_count, save_count, created_at, updated_at
`

type CreateFlashParams struct {
	ArtistID            uuid.UUID          `json:"artist_id"`
	Status              string             `json:"status"`
	Title               string             `json:"title"`
	Description         *string            `json:"description"`
	S3Key               *string            `json:"s3_key"`
	ReferenceS3Key      *string            `json:"reference_s3_key"`
	ColorType           string             `json:"color_type"`
	Styles              []string           `json:"styles"`
	Placements          []string           `json:"placements"`
	PricingMode         string             `json:"pricing_mode"`
	FlatPriceCents      *int64             `json:"flat_price_cents"`
	FlatDurationMinutes *int32             `json:"flat_duration_minutes"`
	DepositCents        *int64             `json:"deposit_cents"`
	Repeatable          bool               `json:"repeatable"`
	PublishedAt         pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) CreateFlash(ctx context.Context, arg CreateFlashParams) (Flash, error) {
	row := q.db.QueryRow(ctx, createFlash,
		arg.ArtistID,
		arg.Status,
		arg.Title,
		arg.Description,
		arg.S3Key,
		arg.ReferenceS3Key,
		arg.ColorType,
		arg.Styles,
		arg.Placements,
		arg.PricingMode,
		arg.FlatPriceCents,
		arg.FlatDurationMinutes,
		arg.DepositCents,
		arg.Repeatable,
		arg.PublishedAt,
	)
	var i Flash
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.S3Key,
		&i.ReferenceS3Key,
		&i.ColorType,
		&i.Styles,
		&i.Placements,
		&i.PricingMode,
		&i.FlatPriceCents,
		&i.FlatDurationMinutes,
		&i.DepositCents,
		&i.Repeatable,
		&i.ClaimedAt,
		&i.ClaimedByBookingID,
		&i.ArchivedAt,
		&i.PublishedAt,
		&i.ViewCount,
		&i.SaveCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllFlashPricingTiers = `-- name: DeleteAllFlashPricingTiers :exec
DELETE FROM flash_pricing_tiers WHERE flash_id = $1
`

func (q *Queries) DeleteAllFlashPricingTiers(ctx context.Context, flashID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllFlashPricingTiers, flashID)
	return err
}

const deleteFlash = `-- name: DeleteFlash :exec
DELETE FROM flashes WHERE id = $1
`

func (q *Queries) DeleteFlash(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFlash, id)
	return err
}

const deleteFlashPricingTier = `-- name: DeleteFlashPricingTier :exec
DELETE FROM flash_pricing_tiers
WHERE flash_id = $1 AND size_code = $2
`

type DeleteFlashPricingTierParams struct {
	FlashID  uuid.UUID `json:"flash_id"`
	SizeCode string    `json:"size_code"`
}

func (q *Queries) DeleteFlashPricingTier(ctx context.Context, arg DeleteFlashPricingTierParams) error {
	_, err := q.db.Exec(ctx, deleteFlashPricingTier, arg.FlashID, arg.SizeCode)
	return err
}

const getFlash = `-- name: GetFlash :one
SELECT id, artist_id, status, title, description, s3_key, reference_s3_key, color_type, styles, placements, pricing_mode, flat_price_cents, flat_duration_minutes, deposit_cents, repeatable, claimed_at, claimed_by_booking_id, archived_at, published_at, view_count, save_count, created_at, updated_at FROM flashes WHERE id = $1
`

func (q *Queries) GetFlash(ctx context.Context, id uuid.UUID) (Flash, error) {
	row := q.db.QueryRow(ctx, getFlash, id)
	var i Flash
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.S3Key,
		&i.ReferenceS3Key,
		&i.ColorType,
		&i.Styles,
		&i.Placements,
		&i.PricingMode,
		&i.FlatPriceCents,
		&i.FlatDurationMinutes,
		&i.DepositCents,
		&i.Repeatable,
		&i.ClaimedAt,
		&i.ClaimedByBookingID,
		&i.ArchivedAt,
		&i.PublishedAt,
		&i.ViewCount,
		&i.SaveCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementFlashViewCount = `-- name: IncrementFlashViewCount :exec
UPDATE flashes
SET view_count = view_count + 1
WHERE id = $1
`

func (q *Queries) IncrementFlashViewCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementFlashViewCount, id)
	return err
}

const listFlashPricingTiers = `-- name: ListFlashPricingTiers :many
SELECT flash_id, size_code, duration_minutes, price_cents
FROM flash_pricing_tiers
WHERE flash_id = $1
ORDER BY
    CASE size_code
        WHEN 'x_small' THEN 1
        WHEN 'small'   THEN 2
        WHEN 'medium'  THEN 3
        WHEN 'large'   THEN 4
        WHEN 'x_large' THEN 5
    END
`

func (q *Queries) ListFlashPricingTiers(ctx context.Context, flashID uuid.UUID) ([]FlashPricingTier, error) {
	rows, err := q.db.Query(ctx, listFlashPricingTiers, flashID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlashPricingTier
	for rows.Next() {
		var i FlashPricingTier
		if err := rows.Scan(
			&i.FlashID,
			&i.SizeCode,
			&i.DurationMinutes,
			&i.PriceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlashPricingTiersForFlashes = `-- name: ListFlashPricingTiersForFlashes :many
SELECT flash_id, size_code, duration_minutes, price_cents
FROM flash_pricing_tiers
WHERE flash_id = ANY($1::uuid[])
ORDER BY
    flash_id,
    CASE size_code
        WHEN 'x_small' THEN 1
        WHEN 'small'   THEN 2
        WHEN 'medium'  THEN 3
        WHEN 'large'   THEN 4
        WHEN 'x_large' THEN 5
    END
`

// Batched fetch for a page of flashes, avoiding an N+1 of ListFlashPricingTiers.
// Ordered by flash so callers can group sequentially, then by size.
func (q *Queries) ListFlashPricingTiersForFlashes(ctx context.Context, flashIds []uuid.UUID) ([]FlashPricingTier, error) {
	rows, err := q.db.Query(ctx, listFlashPricingTiersForFlashes, flashIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlashPricingTier
	for rows.Next() {
		var i FlashPricingTier
		if err := rows.Scan(
			&i.FlashID,
			&i.SizeCode,
			&i.DurationMinutes,
			&i.PriceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlashesByArtist = `-- name: ListFlashesByArtist :many
SELECT id, artist_id, status, title, description, s3_key, reference_s3_key, color_type, styles, placements, pricing_mode, flat_price_cents, flat_duration_minutes, deposit_cents, repeatable, claimed_at, claimed_by_booking_id, archived_at, published_at, view_count, save_count, created_at, updated_at
FROM flashes
WHERE artist_id = $1
  AND ($2::text IS NULL OR status = $2)
ORDER BY created_at DESC
LIMIT $4
OFFSET $3
`

type ListFlashesByArtistParams struct {
	ArtistID   uuid.UUID `json:"artist_id"`
	Status     *string   `json:"status"`
	PageOffset int32     `json:"page_offset"`
	PageLimit  int32     `json:"page_limit"`
}

func (q *Queries) ListFlashesByArtist(ctx context.Context, arg ListFlashesByArtistParams) ([]Flash, error) {
	rows, err := q.db.Query(ctx, listFlashesByArtist,
		arg.ArtistID,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flash
	for rows.Next() {
		var i Flash
		if err := rows.Scan(
			&i.ID,
			&i.ArtistID,
			&i.Status,
			&i.Title,
			&i.Description,
			&i.S3Key,
			&i.ReferenceS3Key,
			&i.ColorType,
			&i.Styles,
			&i.Placements,
			&i.PricingMode,
			&i.FlatPriceCents,
			&i.FlatDurationMinutes,
			&i.DepositCents,
			&i.Repeatable,
			&i.ClaimedAt,
			&i.ClaimedByBookingID,
			&i.ArchivedAt,
			&i.PublishedAt,
			&i.ViewCount,
			&i.SaveCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishFlash = `-- name: PublishFlash :one
UPDATE flashes
SET status       = 'available',
    published_at = COALESCE(published_at, now()),
    updated_at   = now()
WHERE id = $1
  AND status = 'draft'
RETURNING id, artist_id, status, title, description, s3_key, reference_s3_key, color_type, styles, placements, pricing_mode, flat_price_cents, flat_duration_minutes, deposit_cents, repeatable, claimed_at, claimed_by_booking_id, archived_at, published_at, view_count, save_count, created_at, updated_at
`

func (q *Queries) PublishFlash(ctx context.Context, id uuid.UUID) (Flash, error) {
	row := q.db.QueryRow(ctx, publishFlash, id)
	var i Flash
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.S3Key,
		&i.ReferenceS3Key,
		&i.ColorType,
		&i.Styles,
		&i.Placements,
		&i.PricingMode,
		&i.FlatPriceCents,
		&i.FlatDurationMinutes,
		&i.DepositCents,
		&i.Repeatable,
		&i.ClaimedAt,
		&i.ClaimedByBookingID,
		&i.ArchivedAt,
		&i.PublishedAt,
		&i.ViewCount,
		&i.SaveCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unarchiveFlash = `-- name: UnarchiveFlash :one
UPDATE flashes
SET status      = CASE
                      WHEN published_at IS NOT NULL THEN 'available'
                      ELSE 'draft'
                  END,
    archived_at = NULL,
    updated_at  = now()
WHERE id = $1
  AND status = 'archived'
RETURNING id, artist_id, status, title, description, s3_key, reference_s3_key, color_type, styles, placements, pricing_mode, flat_price_cents, flat_duration_minutes, deposit_cents, repeatable, claimed_at, claimed_by_booking_id, archived_at, published_at, view_count, save_count, created_at, updated_at
`

func (q *Queries) UnarchiveFlash(ctx context.Context, id uuid.UUID) (Flash, error) {
	row := q.db.QueryRow(ctx, unarchiveFlash, id)
	var i Flash
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.S3Key,
		&i.ReferenceS3Key,
		&i.ColorType,
		&i.Styles,
		&i.Placements,
		&i.PricingMode,
		&i.FlatPriceCents,
		&i.FlatDurationMinutes,
		&i.DepositCents,
		&i.Repeatable,
		&i.ClaimedAt,
		&i.ClaimedByBookingID,
		&i.ArchivedAt,
		&i.PublishedAt,
		&i.ViewCount,
		&i.SaveCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFlash = `-- name: UpdateFlash :one
UPDATE flashes
SET title                 = COALESCE($1::text,                          title),
    description           = COALESCE($2::text,                    description),
    s3_key                = COALESCE($3::text,                         s3_key),
    reference_s3_key      = CASE
                                WHEN $4::boolean THEN NULL
                                ELSE COALESCE($5::text, reference_s3_key)
                            END,
    color_type            = COALESCE($6::text,                     color_type),
    styles                = COALESCE($7::text[],                       styles),
    placements            = COALESCE($8::text[],                   placements),
    pricing_mode          = COALESCE($9::text,                   pricing_mode),
    flat_price_cents      = COALESCE($10::bigint,             flat_price_cents),
    flat_duration_minutes = COALESCE($11::integer,       flat_duration_minutes),
    deposit_cents         = COALESCE($12::bigint,                deposit_cents),
    repeatable            = COALESCE($13::boolean,                  repeatable),
    updated_at            = now()
WHERE id = $14
RETURNING id, artist_id, status, title, description, s3_key, reference_s3_key, color_type, styles, placements, pricing_mode, flat_price_cents, flat_duration_minutes, deposit_cents, repeatable, claimed_at, claimed_by_booking_id, archived_at, published_at, view_count, save_count, created_at, updated_at
`

type UpdateFlashParams struct {
	Title               *string   `json:"title"`
	Description         *string   `json:"description"`
	S3Key               *string   `json:"s3_key"`
	ClearReferenceS3Key bool      `json:"clear_reference_s3_key"`
	ReferenceS3Key      *string   `json:"reference_s3_key"`
	ColorType           *string   `json:"color_type"`
	Styles              []string  `json:"styles"`
	Placements          []string  `json:"placements"`
	PricingMode         *string   `json:"pricing_mode"`
	FlatPriceCents      *int64    `json:"flat_price_cents"`
	FlatDurationMinutes *int32    `json:"flat_duration_minutes"`
	DepositCents        *int64    `json:"deposit_cents"`
	Repeatable          *bool     `json:"repeatable"`
	ID                  uuid.UUID `json:"id"`
}

func (q *Queries) UpdateFlash(ctx context.Context, arg UpdateFlashParams) (Flash, error) {
	row := q.db.QueryRow(ctx, updateFlash,
		arg.Title,
		arg.Description,
		arg.S3Key,
		arg.ClearReferenceS3Key,
		arg.ReferenceS3Key,
		arg.ColorType,
		arg.Styles,
		arg.Placements,
		arg.PricingMode,
		arg.FlatPriceCents,
		arg.FlatDurationMinutes,
		arg.DepositCents,
		arg.Repeatable,
		arg.ID,
	)
	var i Flash
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.S3Key,
		&i.ReferenceS3Key,
		&i.ColorType,
		&i.Styles,
		&i.Placements,
		&i.PricingMode,
		&i.FlatPriceCents,
		&i.FlatDurationMinutes,
		&i.DepositCents,
		&i.Repeatable,
		&i.ClaimedAt,
		&i.ClaimedByBookingID,
		&i.ArchivedAt,
		&i.PublishedAt,
		&i.ViewCount,
		&i.SaveCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertFlashPricingTier = `-- name: UpsertFlashPricingTier :one
INSERT INTO flash_pricing_tiers (flash_id, size_code, duration_minutes, price_cents)
VALUES ($1, $2, $3, $4)
ON CONFLICT (flash_id, size_code) DO UPDATE
SET duration_minutes = EXCLUDED.duration_minutes,
    price_cents      = EXCLUDED.price_cents
RETURNING flash_id, size_code, duration_minutes, price_cents
`

type UpsertFlashPricingTierParams struct {
	FlashID         uuid.UUID `json:"flash_id"`
	SizeCode        string    `json:"size_code"`
	DurationMinutes int32     `json:"duration_minutes"`
	PriceCents      int64     `json:"price_cents"`
}

func (q *Queries) UpsertFlashPricingTier(ctx context.Context, arg UpsertFlashPricingTierParams) (FlashPricingTier, error) {
	row := q.db.QueryRow(ctx, upsertFlashPricingTier,
		arg.FlashID,
		arg.SizeCode,
		arg.DurationMinutes,
		arg.PriceCents,
	)
	var i FlashPricingTier
	err := row.Scan(
		&i.FlashID,
		&i.SizeCode,
		&i.DurationMinutes,
		&i.PriceCents,
	)
	return i, err
}
