// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const closeArtistLocation = `-- name: CloseArtistLocation :exec
UPDATE artist_locations
SET status     = 'closed',
    closed_at  = now(),
    updated_at = now()
WHERE id = $1 AND artist_id = $2 AND NOT is_primary AND status = 'active'
`

type CloseArtistLocationParams struct {
	ID       uuid.UUID `json:"id"`
	ArtistID uuid.UUID `json:"artist_id"`
}

// Soft-delete a guest spot: mark it closed but keep the row so booking
// requests retain their location. The home studio can't be closed.
func (q *Queries) CloseArtistLocation(ctx context.Context, arg CloseArtistLocationParams) error {
	_, err := q.db.Exec(ctx, closeArtistLocation, arg.ID, arg.ArtistID)
	return err
}

const createArtistLocation = `-- name: CreateArtistLocation :one
INSERT INTO artist_locations (
    artist_id, label, address, city, province, postal_code, country,
    timezone, is_primary, start_date, end_date
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11
)
RETURNING id, artist_id, label, address, city, province, postal_code, country, timezone, is_primary, start_date, end_date, created_at, updated_at, status, closed_at
`

type CreateArtistLocationParams struct {
	ArtistID   uuid.UUID   `json:"artist_id"`
	Label      string      `json:"label"`
	Address    string      `json:"address"`
	City       string      `json:"city"`
	Province   string      `json:"province"`
	PostalCode string      `json:"postal_code"`
	Country    string      `json:"country"`
	Timezone   string      `json:"timezone"`
	IsPrimary  bool        `json:"is_primary"`
	StartDate  pgtype.Date `json:"start_date"`
	EndDate    pgtype.Date `json:"end_date"`
}

func (q *Queries) CreateArtistLocation(ctx context.Context, arg CreateArtistLocationParams) (ArtistLocation, error) {
	row := q.db.QueryRow(ctx, createArtistLocation,
		arg.ArtistID,
		arg.Label,
		arg.Address,
		arg.City,
		arg.Province,
		arg.PostalCode,
		arg.Country,
		arg.Timezone,
		arg.IsPrimary,
		arg.StartDate,
		arg.EndDate,
	)
	var i ArtistLocation
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Label,
		&i.Address,
		&i.City,
		&i.Province,
		&i.PostalCode,
		&i.Country,
		&i.Timezone,
		&i.IsPrimary,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.ClosedAt,
	)
	return i, err
}

const getArtistLocation = `-- name: GetArtistLocation :one
SELECT id, artist_id, label, address, city, province, postal_code, country, timezone, is_primary, start_date, end_date, created_at, updated_at, status, closed_at
FROM artist_locations
WHERE id = $1 AND artist_id = $2
`

type GetArtistLocationParams struct {
	ID       uuid.UUID `json:"id"`
	ArtistID uuid.UUID `json:"artist_id"`
}

func (q *Queries) GetArtistLocation(ctx context.Context, arg GetArtistLocationParams) (ArtistLocation, error) {
	row := q.db.QueryRow(ctx, getArtistLocation, arg.ID, arg.ArtistID)
	var i ArtistLocation
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Label,
		&i.Address,
		&i.City,
		&i.Province,
		&i.PostalCode,
		&i.Country,
		&i.Timezone,
		&i.IsPrimary,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.ClosedAt,
	)
	return i, err
}

const getPrimaryLocation = `-- name: GetPrimaryLocation :one
SELECT id, artist_id, label, address, city, province, postal_code, country, timezone, is_primary, start_date, end_date, created_at, updated_at, status, closed_at
FROM artist_locations
WHERE artist_id = $1 AND is_primary
LIMIT 1
`

func (q *Queries) GetPrimaryLocation(ctx context.Context, artistID uuid.UUID) (ArtistLocation, error) {
	row := q.db.QueryRow(ctx, getPrimaryLocation, artistID)
	var i ArtistLocation
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Label,
		&i.Address,
		&i.City,
		&i.Province,
		&i.PostalCode,
		&i.Country,
		&i.Timezone,
		&i.IsPrimary,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.ClosedAt,
	)
	return i, err
}

const listAllArtistLocations = `-- name: ListAllArtistLocations :many
SELECT id, artist_id, label, address, city, province, postal_code, country, timezone, is_primary, start_date, end_date, created_at, updated_at, status, closed_at
FROM artist_locations
WHERE artist_id = $1
ORDER BY is_primary DESC, start_date ASC NULLS LAST, created_at
`

// Every location including closed ones, so a booking request can always
// resolve the spot it was tagged with even after the artist closes it.
func (q *Queries) ListAllArtistLocations(ctx context.Context, artistID uuid.UUID) ([]ArtistLocation, error) {
	rows, err := q.db.Query(ctx, listAllArtistLocations, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtistLocation
	for rows.Next() {
		var i ArtistLocation
		if err := rows.Scan(
			&i.ID,
			&i.ArtistID,
			&i.Label,
			&i.Address,
			&i.City,
			&i.Province,
			&i.PostalCode,
			&i.Country,
			&i.Timezone,
			&i.IsPrimary,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtistLocations = `-- name: ListArtistLocations :many
SELECT id, artist_id, label, address, city, province, postal_code, country, timezone, is_primary, start_date, end_date, created_at, updated_at, status, closed_at
FROM artist_locations
WHERE artist_id = $1 AND status = 'active'
ORDER BY is_primary DESC, start_date ASC NULLS LAST, created_at
`

// Active locations only — what the artist can currently work from and what
// clients can book. Closed guest spots are excluded.
func (q *Queries) ListArtistLocations(ctx context.Context, artistID uuid.UUID) ([]ArtistLocation, error) {
	rows, err := q.db.Query(ctx, listArtistLocations, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtistLocation
	for rows.Next() {
		var i ArtistLocation
		if err := rows.Scan(
			&i.ID,
			&i.ArtistID,
			&i.Label,
			&i.Address,
			&i.City,
			&i.Province,
			&i.PostalCode,
			&i.Country,
			&i.Timezone,
			&i.IsPrimary,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCurrentLocation = `-- name: SetCurrentLocation :exec
UPDATE artist_settings
SET current_location_id = $1::uuid,
    updated_at          = now()
WHERE artist_id = $2
`

type SetCurrentLocationParams struct {
	CurrentLocationID pgtype.UUID `json:"current_location_id"`
	ArtistID          uuid.UUID   `json:"artist_id"`
}

func (q *Queries) SetCurrentLocation(ctx context.Context, arg SetCurrentLocationParams) error {
	_, err := q.db.Exec(ctx, setCurrentLocation, arg.CurrentLocationID, arg.ArtistID)
	return err
}

const updateArtistLocation = `-- name: UpdateArtistLocation :one
UPDATE artist_locations
SET label       = COALESCE($1::text,       label),
    address     = COALESCE($2::text,     address),
    city        = COALESCE($3::text,        city),
    province    = COALESCE($4::text,    province),
    postal_code = COALESCE($5::text, postal_code),
    country     = COALESCE($6::text,     country),
    timezone    = COALESCE($7::text,    timezone),
    start_date  = CASE
                      WHEN $8::boolean THEN NULL
                      ELSE COALESCE($9::date, start_date)
                  END,
    end_date    = CASE
                      WHEN $8::boolean THEN NULL
                      ELSE COALESCE($10::date, end_date)
                  END,
    updated_at  = now()
WHERE id = $11 AND artist_id = $12
RETURNING id, artist_id, label, address, city, province, postal_code, country, timezone, is_primary, start_date, end_date, created_at, updated_at, status, closed_at
`

type UpdateArtistLocationParams struct {
	Label      *string     `json:"label"`
	Address    *string     `json:"address"`
	City       *string     `json:"city"`
	Province   *string     `json:"province"`
	PostalCode *string     `json:"postal_code"`
	Country    *string     `json:"country"`
	Timezone   *string     `json:"timezone"`
	ClearDates bool        `json:"clear_dates"`
	StartDate  pgtype.Date `json:"start_date"`
	EndDate    pgtype.Date `json:"end_date"`
	ID         uuid.UUID   `json:"id"`
	ArtistID   uuid.UUID   `json:"artist_id"`
}

func (q *Queries) UpdateArtistLocation(ctx context.Context, arg UpdateArtistLocationParams) (ArtistLocation, error) {
	row := q.db.QueryRow(ctx, updateArtistLocation,
		arg.Label,
		arg.Address,
		arg.City,
		arg.Province,
		arg.PostalCode,
		arg.Country,
		arg.Timezone,
		arg.ClearDates,
		arg.StartDate,
		arg.EndDate,
		arg.ID,
		arg.ArtistID,
	)
	var i ArtistLocation
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Label,
		&i.Address,
		&i.City,
		&i.Province,
		&i.PostalCode,
		&i.Country,
		&i.Timezone,
		&i.IsPrimary,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.ClosedAt,
	)
	return i, err
}
