// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matching.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMatchRequest = `-- name: CreateMatchRequest :one
INSERT INTO match_requests (
    client_id, description, reference_urls, styles, placement,
    size_inches, budget_min_cents, budget_max_cents, city, country, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, client_id, description, reference_urls, styles, placement, size_inches, budget_min_cents, budget_max_cents, city, country, status, expires_at, created_at
`

type CreateMatchRequestParams struct {
	ClientID       uuid.UUID          `json:"client_id"`
	Description    string             `json:"description"`
	ReferenceUrls  []string           `json:"reference_urls"`
	Styles         []string           `json:"styles"`
	Placement      *string            `json:"placement"`
	SizeInches     pgtype.Numeric     `json:"size_inches"`
	BudgetMinCents *int64             `json:"budget_min_cents"`
	BudgetMaxCents *int64             `json:"budget_max_cents"`
	City           *string            `json:"city"`
	Country        *string            `json:"country"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateMatchRequest(ctx context.Context, arg CreateMatchRequestParams) (MatchRequest, error) {
	row := q.db.QueryRow(ctx, createMatchRequest,
		arg.ClientID,
		arg.Description,
		arg.ReferenceUrls,
		arg.Styles,
		arg.Placement,
		arg.SizeInches,
		arg.BudgetMinCents,
		arg.BudgetMaxCents,
		arg.City,
		arg.Country,
		arg.ExpiresAt,
	)
	var i MatchRequest
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Description,
		&i.ReferenceUrls,
		&i.Styles,
		&i.Placement,
		&i.SizeInches,
		&i.BudgetMinCents,
		&i.BudgetMaxCents,
		&i.City,
		&i.Country,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const expireOpenMatchRequests = `-- name: ExpireOpenMatchRequests :execrows
UPDATE match_requests
SET status = 'expired'
WHERE status = 'open'
  AND expires_at IS NOT NULL
  AND expires_at < now()
`

func (q *Queries) ExpireOpenMatchRequests(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireOpenMatchRequests)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMatchByID = `-- name: GetMatchByID :one
SELECT id, request_id, artist_id, score, status, created_at, updated_at FROM matches WHERE id = $1
`

func (q *Queries) GetMatchByID(ctx context.Context, id uuid.UUID) (Match, error) {
	row := q.db.QueryRow(ctx, getMatchByID, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ArtistID,
		&i.Score,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMatchRequestByID = `-- name: GetMatchRequestByID :one
SELECT id, client_id, description, reference_urls, styles, placement, size_inches, budget_min_cents, budget_max_cents, city, country, status, expires_at, created_at FROM match_requests WHERE id = $1
`

func (q *Queries) GetMatchRequestByID(ctx context.Context, id uuid.UUID) (MatchRequest, error) {
	row := q.db.QueryRow(ctx, getMatchRequestByID, id)
	var i MatchRequest
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Description,
		&i.ReferenceUrls,
		&i.Styles,
		&i.Placement,
		&i.SizeInches,
		&i.BudgetMinCents,
		&i.BudgetMaxCents,
		&i.City,
		&i.Country,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertMatch = `-- name: InsertMatch :one
INSERT INTO matches (request_id, artist_id, score)
VALUES ($1, $2, $3)
ON CONFLICT (request_id, artist_id) DO UPDATE
SET score      = EXCLUDED.score,
    updated_at = now()
RETURNING id, request_id, artist_id, score, status, created_at, updated_at
`

type InsertMatchParams struct {
	RequestID uuid.UUID `json:"request_id"`
	ArtistID  uuid.UUID `json:"artist_id"`
	Score     float64   `json:"score"`
}

func (q *Queries) InsertMatch(ctx context.Context, arg InsertMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, insertMatch, arg.RequestID, arg.ArtistID, arg.Score)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ArtistID,
		&i.Score,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLeadsForArtist = `-- name: ListLeadsForArtist :many
SELECT
    matches.id, matches.request_id, matches.artist_id, matches.score, matches.status, matches.created_at, matches.updated_at,
    mr.client_id      AS request_client_id,
    mr.description    AS request_description,
    mr.styles         AS request_styles,
    mr.placement      AS request_placement,
    mr.budget_min_cents AS request_budget_min_cents,
    mr.budget_max_cents AS request_budget_max_cents,
    mr.city           AS request_city,
    mr.country        AS request_country
FROM matches
JOIN match_requests mr ON mr.id = matches.request_id
WHERE matches.artist_id = $1
  AND ($2::text IS NULL OR matches.status = $2)
ORDER BY matches.created_at DESC
LIMIT $4
OFFSET $3
`

type ListLeadsForArtistParams struct {
	ArtistID uuid.UUID `json:"artist_id"`
	Status   *string   `json:"status"`
	Off      int32     `json:"off"`
	Lim      int32     `json:"lim"`
}

type ListLeadsForArtistRow struct {
	Match                 Match     `json:"match"`
	RequestClientID       uuid.UUID `json:"request_client_id"`
	RequestDescription    string    `json:"request_description"`
	RequestStyles         []string  `json:"request_styles"`
	RequestPlacement      *string   `json:"request_placement"`
	RequestBudgetMinCents *int64    `json:"request_budget_min_cents"`
	RequestBudgetMaxCents *int64    `json:"request_budget_max_cents"`
	RequestCity           *string   `json:"request_city"`
	RequestCountry        *string   `json:"request_country"`
}

func (q *Queries) ListLeadsForArtist(ctx context.Context, arg ListLeadsForArtistParams) ([]ListLeadsForArtistRow, error) {
	rows, err := q.db.Query(ctx, listLeadsForArtist,
		arg.ArtistID,
		arg.Status,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLeadsForArtistRow
	for rows.Next() {
		var i ListLeadsForArtistRow
		if err := rows.Scan(
			&i.Match.ID,
			&i.Match.RequestID,
			&i.Match.ArtistID,
			&i.Match.Score,
			&i.Match.Status,
			&i.Match.CreatedAt,
			&i.Match.UpdatedAt,
			&i.RequestClientID,
			&i.RequestDescription,
			&i.RequestStyles,
			&i.RequestPlacement,
			&i.RequestBudgetMinCents,
			&i.RequestBudgetMaxCents,
			&i.RequestCity,
			&i.RequestCountry,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchRequestsByClient = `-- name: ListMatchRequestsByClient :many
SELECT id, client_id, description, reference_urls, styles, placement, size_inches, budget_min_cents, budget_max_cents, city, country, status, expires_at, created_at FROM match_requests
WHERE client_id = $1
  AND ($2::text IS NULL OR status = $2)
ORDER BY created_at DESC
LIMIT $4
OFFSET $3
`

type ListMatchRequestsByClientParams struct {
	ClientID uuid.UUID `json:"client_id"`
	Status   *string   `json:"status"`
	Off      int32     `json:"off"`
	Lim      int32     `json:"lim"`
}

func (q *Queries) ListMatchRequestsByClient(ctx context.Context, arg ListMatchRequestsByClientParams) ([]MatchRequest, error) {
	rows, err := q.db.Query(ctx, listMatchRequestsByClient,
		arg.ClientID,
		arg.Status,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MatchRequest
	for rows.Next() {
		var i MatchRequest
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Description,
			&i.ReferenceUrls,
			&i.Styles,
			&i.Placement,
			&i.SizeInches,
			&i.BudgetMinCents,
			&i.BudgetMaxCents,
			&i.City,
			&i.Country,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchesByRequest = `-- name: ListMatchesByRequest :many
SELECT id, request_id, artist_id, score, status, created_at, updated_at FROM matches
WHERE request_id = $1
ORDER BY score DESC, created_at ASC
`

func (q *Queries) ListMatchesByRequest(ctx context.Context, requestID uuid.UUID) ([]Match, error) {
	rows, err := q.db.Query(ctx, listMatchesByRequest, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Match
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.ArtistID,
			&i.Score,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMatchRequestStatus = `-- name: UpdateMatchRequestStatus :exec
UPDATE match_requests
SET status = $2
WHERE id = $1
`

type UpdateMatchRequestStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateMatchRequestStatus(ctx context.Context, arg UpdateMatchRequestStatusParams) error {
	_, err := q.db.Exec(ctx, updateMatchRequestStatus, arg.ID, arg.Status)
	return err
}

const updateMatchStatus = `-- name: UpdateMatchStatus :one
UPDATE matches
SET status     = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, request_id, artist_id, score, status, created_at, updated_at
`

type UpdateMatchStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateMatchStatus(ctx context.Context, arg UpdateMatchStatusParams) (Match, error) {
	row := q.db.QueryRow(ctx, updateMatchStatus, arg.ID, arg.Status)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ArtistID,
		&i.Score,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
