// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPriorUnreadFromSender = `-- name: CountPriorUnreadFromSender :one
SELECT COUNT(*)
FROM messages m
WHERE m.conversation_id = $1
  AND m.sender_type = $2
  AND ($3::timestamptz IS NULL OR m.created_at > $3)
  AND m.created_at < (SELECT t.created_at FROM messages t WHERE t.id = $4)
`

type CountPriorUnreadFromSenderParams struct {
	ConversationID    uuid.UUID          `json:"conversation_id"`
	SenderType        string             `json:"sender_type"`
	RecipientLastRead pgtype.Timestamptz `json:"recipient_last_read"`
	MessageID         uuid.UUID          `json:"message_id"`
}

func (q *Queries) CountPriorUnreadFromSender(ctx context.Context, arg CountPriorUnreadFromSenderParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPriorUnreadFromSender,
		arg.ConversationID,
		arg.SenderType,
		arg.RecipientLastRead,
		arg.MessageID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (conversation_id, sender_type, sender_user_id, body, ai_drafted)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, conversation_id, sender_type, sender_user_id, body, ai_drafted, created_at
`

type CreateMessageParams struct {
	ConversationID uuid.UUID   `json:"conversation_id"`
	SenderType     string      `json:"sender_type"`
	SenderUserID   pgtype.UUID `json:"sender_user_id"`
	Body           string      `json:"body"`
	AiDrafted      bool        `json:"ai_drafted"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ConversationID,
		arg.SenderType,
		arg.SenderUserID,
		arg.Body,
		arg.AiDrafted,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderType,
		&i.SenderUserID,
		&i.Body,
		&i.AiDrafted,
		&i.CreatedAt,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT id, conversation_id, sender_type, sender_user_id, body, ai_drafted, created_at FROM messages
WHERE conversation_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListMessages(ctx context.Context, conversationID uuid.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderType,
			&i.SenderUserID,
			&i.Body,
			&i.AiDrafted,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
