// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messaging.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (client_id, artist_id, booking_id)
VALUES ($1, $2, $3)
RETURNING id, client_id, artist_id, booking_id, last_message_at, created_at
`

type CreateConversationParams struct {
	ClientID  uuid.UUID   `json:"client_id"`
	ArtistID  uuid.UUID   `json:"artist_id"`
	BookingID pgtype.UUID `json:"booking_id"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.ClientID, arg.ArtistID, arg.BookingID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ArtistID,
		&i.BookingID,
		&i.LastMessageAt,
		&i.CreatedAt,
	)
	return i, err
}

const findConversationForPair = `-- name: FindConversationForPair :one
SELECT id, client_id, artist_id, booking_id, last_message_at, created_at FROM conversations
WHERE client_id = $1
  AND artist_id = $2
  AND (($3::uuid IS NULL AND booking_id IS NULL)
       OR booking_id = $3)
`

type FindConversationForPairParams struct {
	ClientID  uuid.UUID `json:"client_id"`
	ArtistID  uuid.UUID `json:"artist_id"`
	BookingID uuid.UUID `json:"booking_id"`
}

func (q *Queries) FindConversationForPair(ctx context.Context, arg FindConversationForPairParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, findConversationForPair, arg.ClientID, arg.ArtistID, arg.BookingID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ArtistID,
		&i.BookingID,
		&i.LastMessageAt,
		&i.CreatedAt,
	)
	return i, err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT id, client_id, artist_id, booking_id, last_message_at, created_at FROM conversations WHERE id = $1
`

func (q *Queries) GetConversationByID(ctx context.Context, id uuid.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationByID, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ArtistID,
		&i.BookingID,
		&i.LastMessageAt,
		&i.CreatedAt,
	)
	return i, err
}

const getReadCursor = `-- name: GetReadCursor :one
SELECT conversation_id, user_id, last_read_at FROM conversation_read_cursors
WHERE conversation_id = $1 AND user_id = $2
`

type GetReadCursorParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) GetReadCursor(ctx context.Context, arg GetReadCursorParams) (ConversationReadCursor, error) {
	row := q.db.QueryRow(ctx, getReadCursor, arg.ConversationID, arg.UserID)
	var i ConversationReadCursor
	err := row.Scan(&i.ConversationID, &i.UserID, &i.LastReadAt)
	return i, err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (conversation_id, sender_id, body, attachments)
VALUES ($1, $2, $3, $4)
RETURNING id, conversation_id, sender_id, body, attachments, created_at
`

type InsertMessageParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	SenderID       uuid.UUID `json:"sender_id"`
	Body           string    `json:"body"`
	Attachments    []string  `json:"attachments"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.ConversationID,
		arg.SenderID,
		arg.Body,
		arg.Attachments,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Body,
		&i.Attachments,
		&i.CreatedAt,
	)
	return i, err
}

const listConversationsForArtist = `-- name: ListConversationsForArtist :many
SELECT id, client_id, artist_id, booking_id, last_message_at, created_at FROM conversations
WHERE artist_id = $1
ORDER BY last_message_at DESC
LIMIT $2 OFFSET $3
`

type ListConversationsForArtistParams struct {
	ArtistID uuid.UUID `json:"artist_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListConversationsForArtist(ctx context.Context, arg ListConversationsForArtistParams) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversationsForArtist, arg.ArtistID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ArtistID,
			&i.BookingID,
			&i.LastMessageAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationsForClient = `-- name: ListConversationsForClient :many
SELECT id, client_id, artist_id, booking_id, last_message_at, created_at FROM conversations
WHERE client_id = $1
ORDER BY last_message_at DESC
LIMIT $2 OFFSET $3
`

type ListConversationsForClientParams struct {
	ClientID uuid.UUID `json:"client_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListConversationsForClient(ctx context.Context, arg ListConversationsForClientParams) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversationsForClient, arg.ClientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ArtistID,
			&i.BookingID,
			&i.LastMessageAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, conversation_id, sender_id, body, attachments, created_at FROM messages
WHERE conversation_id = $1
  AND ($2::timestamptz IS NULL OR created_at < $2)
ORDER BY created_at DESC
LIMIT $3
`

type ListMessagesParams struct {
	ConversationID uuid.UUID          `json:"conversation_id"`
	Before         pgtype.Timestamptz `json:"before"`
	Lim            int32              `json:"lim"`
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages, arg.ConversationID, arg.Before, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Body,
			&i.Attachments,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchConversationLastMessageAt = `-- name: TouchConversationLastMessageAt :exec
UPDATE conversations
SET last_message_at = now()
WHERE id = $1
`

func (q *Queries) TouchConversationLastMessageAt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchConversationLastMessageAt, id)
	return err
}

const upsertReadCursor = `-- name: UpsertReadCursor :one
INSERT INTO conversation_read_cursors (conversation_id, user_id, last_read_at)
VALUES ($1, $2, now())
ON CONFLICT (conversation_id, user_id) DO UPDATE
SET last_read_at = EXCLUDED.last_read_at
RETURNING conversation_id, user_id, last_read_at
`

type UpsertReadCursorParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) UpsertReadCursor(ctx context.Context, arg UpsertReadCursorParams) (ConversationReadCursor, error) {
	row := q.db.QueryRow(ctx, upsertReadCursor, arg.ConversationID, arg.UserID)
	var i ConversationReadCursor
	err := row.Scan(&i.ConversationID, &i.UserID, &i.LastReadAt)
	return i, err
}
