// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Artist struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	Handle      string             `json:"handle"`
	DisplayName string             `json:"display_name"`
	Bio         string             `json:"bio"`
	Styles      []string           `json:"styles"`
	City        *string            `json:"city"`
	Country     *string            `json:"country"`
	BookingLink *string            `json:"booking_link"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ArtistAvailability struct {
	ArtistID      uuid.UUID          `json:"artist_id"`
	AcceptingNew  bool               `json:"accepting_new"`
	WeeklyWindows []byte             `json:"weekly_windows"`
	WaitlistDays  int32              `json:"waitlist_days"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Flash struct {
	ID                  uuid.UUID          `json:"id"`
	ArtistID            uuid.UUID          `json:"artist_id"`
	Status              string             `json:"status"`
	Title               string             `json:"title"`
	Description         *string            `json:"description"`
	S3Key               *string            `json:"s3_key"`
	ReferenceS3Key      *string            `json:"reference_s3_key"`
	ColorType           string             `json:"color_type"`
	Styles              []string           `json:"styles"`
	Placements          []string           `json:"placements"`
	PricingMode         string             `json:"pricing_mode"`
	FlatPriceCents      *int64             `json:"flat_price_cents"`
	FlatDurationMinutes *int32             `json:"flat_duration_minutes"`
	DepositCents        *int64             `json:"deposit_cents"`
	Currency            string             `json:"currency"`
	Repeatable          bool               `json:"repeatable"`
	ClaimedAt           pgtype.Timestamptz `json:"claimed_at"`
	ClaimedByBookingID  pgtype.UUID        `json:"claimed_by_booking_id"`
	ArchivedAt          pgtype.Timestamptz `json:"archived_at"`
	PublishedAt         pgtype.Timestamptz `json:"published_at"`
	ViewCount           int64              `json:"view_count"`
	SaveCount           int64              `json:"save_count"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type FlashPricingTier struct {
	FlashID         uuid.UUID `json:"flash_id"`
	SizeCode        string    `json:"size_code"`
	DurationMinutes int32     `json:"duration_minutes"`
	PriceCents      int64     `json:"price_cents"`
}

type PhoneVerification struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Phone      string             `json:"phone"`
	CodeHash   string             `json:"code_hash"`
	Attempts   int32              `json:"attempts"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	UserAgent *string            `json:"user_agent"`
	IpAddress *netip.Addr        `json:"ip_address"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	Role            string             `json:"role"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	FirstName       *string            `json:"first_name"`
	LastName        *string            `json:"last_name"`
	Phone           *string            `json:"phone"`
	PhoneVerifiedAt pgtype.Timestamptz `json:"phone_verified_at"`
}
