// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Artist struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	Handle      string             `json:"handle"`
	DisplayName string             `json:"display_name"`
	Bio         string             `json:"bio"`
	Styles      []string           `json:"styles"`
	City        *string            `json:"city"`
	Country     *string            `json:"country"`
	BookingLink *string            `json:"booking_link"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ArtistAvailability struct {
	ArtistID      uuid.UUID          `json:"artist_id"`
	AcceptingNew  bool               `json:"accepting_new"`
	WeeklyWindows []byte             `json:"weekly_windows"`
	WaitlistDays  int32              `json:"waitlist_days"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Booking struct {
	ID                 uuid.UUID          `json:"id"`
	ClientID           uuid.UUID          `json:"client_id"`
	ArtistID           uuid.UUID          `json:"artist_id"`
	Status             string             `json:"status"`
	Notes              string             `json:"notes"`
	EstimatedHours     pgtype.Numeric     `json:"estimated_hours"`
	DepositAmountCents int64              `json:"deposit_amount_cents"`
	ScheduledFor       pgtype.Timestamptz `json:"scheduled_for"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type BookingStatusHistory struct {
	ID         uuid.UUID          `json:"id"`
	BookingID  uuid.UUID          `json:"booking_id"`
	FromStatus *string            `json:"from_status"`
	ToStatus   string             `json:"to_status"`
	ChangedBy  pgtype.UUID        `json:"changed_by"`
	Note       *string            `json:"note"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Conversation struct {
	ID            uuid.UUID          `json:"id"`
	ClientID      uuid.UUID          `json:"client_id"`
	ArtistID      uuid.UUID          `json:"artist_id"`
	BookingID     pgtype.UUID        `json:"booking_id"`
	LastMessageAt pgtype.Timestamptz `json:"last_message_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ConversationReadCursor struct {
	ConversationID uuid.UUID          `json:"conversation_id"`
	UserID         uuid.UUID          `json:"user_id"`
	LastReadAt     pgtype.Timestamptz `json:"last_read_at"`
}

type FlashDesign struct {
	ID            uuid.UUID          `json:"id"`
	ArtistID      uuid.UUID          `json:"artist_id"`
	Title         string             `json:"title"`
	Description   string             `json:"description"`
	ImageUrl      string             `json:"image_url"`
	Styles        []string           `json:"styles"`
	Placement     *string            `json:"placement"`
	SizeInches    pgtype.Numeric     `json:"size_inches"`
	PriceCents    int64              `json:"price_cents"`
	Currency      string             `json:"currency"`
	Repeatable    bool               `json:"repeatable"`
	Status        string             `json:"status"`
	ReservedBy    pgtype.UUID        `json:"reserved_by"`
	ReservedUntil pgtype.Timestamptz `json:"reserved_until"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Match struct {
	ID        uuid.UUID          `json:"id"`
	RequestID uuid.UUID          `json:"request_id"`
	ArtistID  uuid.UUID          `json:"artist_id"`
	Score     float64            `json:"score"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type MatchRequest struct {
	ID             uuid.UUID          `json:"id"`
	ClientID       uuid.UUID          `json:"client_id"`
	Description    string             `json:"description"`
	ReferenceUrls  []string           `json:"reference_urls"`
	Styles         []string           `json:"styles"`
	Placement      *string            `json:"placement"`
	SizeInches     pgtype.Numeric     `json:"size_inches"`
	BudgetMinCents *int64             `json:"budget_min_cents"`
	BudgetMaxCents *int64             `json:"budget_max_cents"`
	City           *string            `json:"city"`
	Country        *string            `json:"country"`
	Status         string             `json:"status"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Message struct {
	ID             uuid.UUID          `json:"id"`
	ConversationID uuid.UUID          `json:"conversation_id"`
	SenderID       uuid.UUID          `json:"sender_id"`
	Body           string             `json:"body"`
	Attachments    []string           `json:"attachments"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Notification struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Kind      string             `json:"kind"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	Data      []byte             `json:"data"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type NotificationDelivery struct {
	ID             uuid.UUID          `json:"id"`
	NotificationID uuid.UUID          `json:"notification_id"`
	Channel        string             `json:"channel"`
	Status         string             `json:"status"`
	Error          *string            `json:"error"`
	AttemptedAt    pgtype.Timestamptz `json:"attempted_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type NotificationPreference struct {
	UserID     uuid.UUID          `json:"user_id"`
	Enabled    []byte             `json:"enabled"`
	QuietHours []byte             `json:"quiet_hours"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Payment struct {
	ID               uuid.UUID          `json:"id"`
	BookingID        uuid.UUID          `json:"booking_id"`
	PayerID          uuid.UUID          `json:"payer_id"`
	PayeeID          uuid.UUID          `json:"payee_id"`
	Kind             string             `json:"kind"`
	AmountCents      int64              `json:"amount_cents"`
	Currency         string             `json:"currency"`
	Status           string             `json:"status"`
	Provider         string             `json:"provider"`
	ProviderIntentID string             `json:"provider_intent_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type PaymentWebhookEvent struct {
	ID         uuid.UUID          `json:"id"`
	Provider   string             `json:"provider"`
	EventID    string             `json:"event_id"`
	Payload    []byte             `json:"payload"`
	Processed  bool               `json:"processed"`
	ReceivedAt pgtype.Timestamptz `json:"received_at"`
}

type PhoneVerification struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Phone      string             `json:"phone"`
	CodeHash   string             `json:"code_hash"`
	Attempts   int32              `json:"attempts"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type PortfolioItem struct {
	ID          uuid.UUID          `json:"id"`
	ArtistID    uuid.UUID          `json:"artist_id"`
	ImageUrl    string             `json:"image_url"`
	Caption     string             `json:"caption"`
	Styles      []string           `json:"styles"`
	Placement   *string            `json:"placement"`
	HealedPhoto bool               `json:"healed_photo"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	UserAgent *string            `json:"user_agent"`
	IpAddress *netip.Addr        `json:"ip_address"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	Role            string             `json:"role"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	FirstName       *string            `json:"first_name"`
	LastName        *string            `json:"last_name"`
	Phone           *string            `json:"phone"`
	PhoneVerifiedAt pgtype.Timestamptz `json:"phone_verified_at"`
}
