// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Artist struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	OnboardedAt pgtype.Timestamptz `json:"onboarded_at"`
}

type ArtistAvailabilityWindow struct {
	ID          uuid.UUID `json:"id"`
	ArtistID    uuid.UUID `json:"artist_id"`
	Weekday     int32     `json:"weekday"`
	StartMinute int32     `json:"start_minute"`
	EndMinute   int32     `json:"end_minute"`
}

type ArtistBlocklist struct {
	ID        uuid.UUID          `json:"id"`
	ArtistID  uuid.UUID          `json:"artist_id"`
	Email     *string            `json:"email"`
	Phone     *string            `json:"phone"`
	Note      string             `json:"note"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ArtistDaysOff struct {
	ArtistID uuid.UUID   `json:"artist_id"`
	Day      pgtype.Date `json:"day"`
}

type ArtistSessionPreset struct {
	ID                    uuid.UUID          `json:"id"`
	ArtistID              uuid.UUID          `json:"artist_id"`
	Name                  string             `json:"name"`
	Description           string             `json:"description"`
	ApproxDurationMinutes int32              `json:"approx_duration_minutes"`
	Position              int32              `json:"position"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type ArtistSetting struct {
	ArtistID                   uuid.UUID          `json:"artist_id"`
	StudioName                 string             `json:"studio_name"`
	StudioAddress              string             `json:"studio_address"`
	StudioCity                 string             `json:"studio_city"`
	StudioProvince             string             `json:"studio_province"`
	StudioPostalCode           string             `json:"studio_postal_code"`
	StudioCountry              string             `json:"studio_country"`
	StripeAccountID            *string            `json:"stripe_account_id"`
	PayoutFrequency            string             `json:"payout_frequency"`
	Currency                   string             `json:"currency"`
	DepositFlatFeeCents        *int64             `json:"deposit_flat_fee_cents"`
	PlatformFeePayer           string             `json:"platform_fee_payer"`
	AcceptingBookings          bool               `json:"accepting_bookings"`
	Timezone                   string             `json:"timezone"`
	GoogleCalendarEmail        *string            `json:"google_calendar_email"`
	SlotIntervalMinutes        int32              `json:"slot_interval_minutes"`
	BufferMinutes              int32              `json:"buffer_minutes"`
	MinNoticeMinutes           int32              `json:"min_notice_minutes"`
	MaxAdvanceDays             *int32             `json:"max_advance_days"`
	TermsText                  string             `json:"terms_text"`
	TermsShowOnBooking         bool               `json:"terms_show_on_booking"`
	TermsShowAtDeposit         bool               `json:"terms_show_at_deposit"`
	WaiverFileUrl              *string            `json:"waiver_file_url"`
	WaiverRequired             bool               `json:"waiver_required"`
	NotifyByEmail              bool               `json:"notify_by_email"`
	NotifyBySms                bool               `json:"notify_by_sms"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	GoogleCalendarAccessToken  *string            `json:"google_calendar_access_token"`
	GoogleCalendarRefreshToken *string            `json:"google_calendar_refresh_token"`
	GoogleCalendarTokenExpiry  pgtype.Timestamptz `json:"google_calendar_token_expiry"`
	StripeChargesEnabled       bool               `json:"stripe_charges_enabled"`
	StripePayoutsEnabled       bool               `json:"stripe_payouts_enabled"`
	StripeDetailsSubmitted     bool               `json:"stripe_details_submitted"`
	DepositRefundPolicy        string             `json:"deposit_refund_policy"`
	CancellationNoticeHours    *int32             `json:"cancellation_notice_hours"`
}

type Flash struct {
	ID                  uuid.UUID          `json:"id"`
	ArtistID            uuid.UUID          `json:"artist_id"`
	Status              string             `json:"status"`
	Title               string             `json:"title"`
	Description         *string            `json:"description"`
	S3Key               *string            `json:"s3_key"`
	ReferenceS3Key      *string            `json:"reference_s3_key"`
	ColorType           string             `json:"color_type"`
	Styles              []string           `json:"styles"`
	Placements          []string           `json:"placements"`
	PricingMode         string             `json:"pricing_mode"`
	FlatPriceCents      *int64             `json:"flat_price_cents"`
	FlatDurationMinutes *int32             `json:"flat_duration_minutes"`
	DepositCents        *int64             `json:"deposit_cents"`
	Repeatable          bool               `json:"repeatable"`
	ClaimedAt           pgtype.Timestamptz `json:"claimed_at"`
	ClaimedByBookingID  pgtype.UUID        `json:"claimed_by_booking_id"`
	ArchivedAt          pgtype.Timestamptz `json:"archived_at"`
	PublishedAt         pgtype.Timestamptz `json:"published_at"`
	ViewCount           int64              `json:"view_count"`
	SaveCount           int64              `json:"save_count"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type FlashPricingTier struct {
	FlashID         uuid.UUID `json:"flash_id"`
	SizeCode        string    `json:"size_code"`
	DurationMinutes int32     `json:"duration_minutes"`
	PriceCents      int64     `json:"price_cents"`
}

type OpenBook struct {
	ID             uuid.UUID          `json:"id"`
	ArtistID       uuid.UUID          `json:"artist_id"`
	Slug           string             `json:"slug"`
	SchedulingMode string             `json:"scheduling_mode"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type PhoneVerification struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Phone      string             `json:"phone"`
	CodeHash   string             `json:"code_hash"`
	Attempts   int32              `json:"attempts"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	UserAgent *string            `json:"user_agent"`
	IpAddress *netip.Addr        `json:"ip_address"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	Role            string             `json:"role"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	FirstName       *string            `json:"first_name"`
	LastName        *string            `json:"last_name"`
	Phone           *string            `json:"phone"`
	PhoneVerifiedAt pgtype.Timestamptz `json:"phone_verified_at"`
	Username        *string            `json:"username"`
	AvatarUrl       *string            `json:"avatar_url"`
	InstagramUrl    *string            `json:"instagram_url"`
}
