// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*)::bigint FROM notifications
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, user_id, kind, title, body, data, read_at, created_at FROM notifications WHERE id = $1
`

func (q *Queries) GetNotificationByID(ctx context.Context, id uuid.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByID, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.Data,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const getNotificationPreferences = `-- name: GetNotificationPreferences :one
SELECT user_id, enabled, quiet_hours, updated_at FROM notification_preferences WHERE user_id = $1
`

func (q *Queries) GetNotificationPreferences(ctx context.Context, userID uuid.UUID) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, getNotificationPreferences, userID)
	var i NotificationPreference
	err := row.Scan(
		&i.UserID,
		&i.Enabled,
		&i.QuietHours,
		&i.UpdatedAt,
	)
	return i, err
}

const insertNotification = `-- name: InsertNotification :one
INSERT INTO notifications (user_id, kind, title, body, data)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, kind, title, body, data, read_at, created_at
`

type InsertNotificationParams struct {
	UserID uuid.UUID `json:"user_id"`
	Kind   string    `json:"kind"`
	Title  string    `json:"title"`
	Body   string    `json:"body"`
	Data   []byte    `json:"data"`
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, insertNotification,
		arg.UserID,
		arg.Kind,
		arg.Title,
		arg.Body,
		arg.Data,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.Data,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertNotificationDelivery = `-- name: InsertNotificationDelivery :one
INSERT INTO notification_deliveries (notification_id, channel)
VALUES ($1, $2)
RETURNING id, notification_id, channel, status, error, attempted_at, created_at
`

type InsertNotificationDeliveryParams struct {
	NotificationID uuid.UUID `json:"notification_id"`
	Channel        string    `json:"channel"`
}

func (q *Queries) InsertNotificationDelivery(ctx context.Context, arg InsertNotificationDeliveryParams) (NotificationDelivery, error) {
	row := q.db.QueryRow(ctx, insertNotificationDelivery, arg.NotificationID, arg.Channel)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.Channel,
		&i.Status,
		&i.Error,
		&i.AttemptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNotificationsForUser = `-- name: ListNotificationsForUser :many
SELECT id, user_id, kind, title, body, data, read_at, created_at FROM notifications
WHERE user_id = $1
  AND ($2::boolean = false OR read_at IS NULL)
ORDER BY created_at DESC
LIMIT $4
OFFSET $3
`

type ListNotificationsForUserParams struct {
	UserID     uuid.UUID `json:"user_id"`
	UnreadOnly bool      `json:"unread_only"`
	Off        int32     `json:"off"`
	Lim        int32     `json:"lim"`
}

func (q *Queries) ListNotificationsForUser(ctx context.Context, arg ListNotificationsForUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsForUser,
		arg.UserID,
		arg.UnreadOnly,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.Data,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingDeliveries = `-- name: ListPendingDeliveries :many
SELECT id, notification_id, channel, status, error, attempted_at, created_at FROM notification_deliveries
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListPendingDeliveries(ctx context.Context, limit int32) ([]NotificationDelivery, error) {
	rows, err := q.db.Query(ctx, listPendingDeliveries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationDelivery
	for rows.Next() {
		var i NotificationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.Channel,
			&i.Status,
			&i.Error,
			&i.AttemptedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :execrows
UPDATE notifications
SET read_at = now()
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications
SET read_at = now()
WHERE id = $1 AND read_at IS NULL
`

func (q *Queries) MarkNotificationRead(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markNotificationRead, id)
	return err
}

const updateDeliveryStatus = `-- name: UpdateDeliveryStatus :exec
UPDATE notification_deliveries
SET status       = $2,
    error        = $3,
    attempted_at = now()
WHERE id = $1
`

type UpdateDeliveryStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
	Error  *string   `json:"error"`
}

func (q *Queries) UpdateDeliveryStatus(ctx context.Context, arg UpdateDeliveryStatusParams) error {
	_, err := q.db.Exec(ctx, updateDeliveryStatus, arg.ID, arg.Status, arg.Error)
	return err
}

const upsertNotificationPreferences = `-- name: UpsertNotificationPreferences :one
INSERT INTO notification_preferences (user_id, enabled, quiet_hours)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE
SET enabled     = EXCLUDED.enabled,
    quiet_hours = EXCLUDED.quiet_hours,
    updated_at  = now()
RETURNING user_id, enabled, quiet_hours, updated_at
`

type UpsertNotificationPreferencesParams struct {
	UserID     uuid.UUID `json:"user_id"`
	Enabled    []byte    `json:"enabled"`
	QuietHours []byte    `json:"quiet_hours"`
}

func (q *Queries) UpsertNotificationPreferences(ctx context.Context, arg UpsertNotificationPreferencesParams) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, upsertNotificationPreferences, arg.UserID, arg.Enabled, arg.QuietHours)
	var i NotificationPreference
	err := row.Scan(
		&i.UserID,
		&i.Enabled,
		&i.QuietHours,
		&i.UpdatedAt,
	)
	return i, err
}
