// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: open_books.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createOpenBook = `-- name: CreateOpenBook :one
INSERT INTO open_books (artist_id, slug, scheduling_mode)
VALUES ($1, $2, $3)
RETURNING id, artist_id, slug, scheduling_mode, created_at, updated_at, custom_questions, theme
`

type CreateOpenBookParams struct {
	ArtistID       uuid.UUID `json:"artist_id"`
	Slug           string    `json:"slug"`
	SchedulingMode string    `json:"scheduling_mode"`
}

func (q *Queries) CreateOpenBook(ctx context.Context, arg CreateOpenBookParams) (OpenBook, error) {
	row := q.db.QueryRow(ctx, createOpenBook, arg.ArtistID, arg.Slug, arg.SchedulingMode)
	var i OpenBook
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Slug,
		&i.SchedulingMode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomQuestions,
		&i.Theme,
	)
	return i, err
}

const getOpenBookByArtist = `-- name: GetOpenBookByArtist :one
SELECT id, artist_id, slug, scheduling_mode, created_at, updated_at, custom_questions, theme FROM open_books WHERE artist_id = $1
`

func (q *Queries) GetOpenBookByArtist(ctx context.Context, artistID uuid.UUID) (OpenBook, error) {
	row := q.db.QueryRow(ctx, getOpenBookByArtist, artistID)
	var i OpenBook
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Slug,
		&i.SchedulingMode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomQuestions,
		&i.Theme,
	)
	return i, err
}

const getOpenBookBySlug = `-- name: GetOpenBookBySlug :one
SELECT id, artist_id, slug, scheduling_mode, created_at, updated_at, custom_questions, theme FROM open_books WHERE slug = $1
`

func (q *Queries) GetOpenBookBySlug(ctx context.Context, slug string) (OpenBook, error) {
	row := q.db.QueryRow(ctx, getOpenBookBySlug, slug)
	var i OpenBook
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Slug,
		&i.SchedulingMode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomQuestions,
		&i.Theme,
	)
	return i, err
}

const updateOpenBook = `-- name: UpdateOpenBook :one
UPDATE open_books
SET slug             = COALESCE($1::citext, slug),
    scheduling_mode  = COALESCE($2::text, scheduling_mode),
    custom_questions = COALESCE($3::jsonb, custom_questions),
    theme            = COALESCE($4::text, theme),
    updated_at       = now()
WHERE artist_id = $5
RETURNING id, artist_id, slug, scheduling_mode, created_at, updated_at, custom_questions, theme
`

type UpdateOpenBookParams struct {
	Slug            *string   `json:"slug"`
	SchedulingMode  *string   `json:"scheduling_mode"`
	CustomQuestions []byte    `json:"custom_questions"`
	Theme           *string   `json:"theme"`
	ArtistID        uuid.UUID `json:"artist_id"`
}

func (q *Queries) UpdateOpenBook(ctx context.Context, arg UpdateOpenBookParams) (OpenBook, error) {
	row := q.db.QueryRow(ctx, updateOpenBook,
		arg.Slug,
		arg.SchedulingMode,
		arg.CustomQuestions,
		arg.Theme,
		arg.ArtistID,
	)
	var i OpenBook
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Slug,
		&i.SchedulingMode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomQuestions,
		&i.Theme,
	)
	return i, err
}
