// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: open_books.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createOpenBook = `-- name: CreateOpenBook :one
INSERT INTO open_books (artist_id, slug, scheduling_mode)
VALUES ($1, $2, $3)
RETURNING id, artist_id, slug, scheduling_mode, created_at, updated_at
`

type CreateOpenBookParams struct {
	ArtistID       uuid.UUID `json:"artist_id"`
	Slug           string    `json:"slug"`
	SchedulingMode string    `json:"scheduling_mode"`
}

func (q *Queries) CreateOpenBook(ctx context.Context, arg CreateOpenBookParams) (OpenBook, error) {
	row := q.db.QueryRow(ctx, createOpenBook, arg.ArtistID, arg.Slug, arg.SchedulingMode)
	var i OpenBook
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Slug,
		&i.SchedulingMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOpenBookByArtist = `-- name: GetOpenBookByArtist :one
SELECT id, artist_id, slug, scheduling_mode, created_at, updated_at FROM open_books WHERE artist_id = $1
`

func (q *Queries) GetOpenBookByArtist(ctx context.Context, artistID uuid.UUID) (OpenBook, error) {
	row := q.db.QueryRow(ctx, getOpenBookByArtist, artistID)
	var i OpenBook
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Slug,
		&i.SchedulingMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOpenBookBySlug = `-- name: GetOpenBookBySlug :one
SELECT id, artist_id, slug, scheduling_mode, created_at, updated_at FROM open_books WHERE slug = $1
`

func (q *Queries) GetOpenBookBySlug(ctx context.Context, slug string) (OpenBook, error) {
	row := q.db.QueryRow(ctx, getOpenBookBySlug, slug)
	var i OpenBook
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Slug,
		&i.SchedulingMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
