// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    booking_id, payer_id, payee_id, kind, amount_cents, currency,
    provider, provider_intent_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, booking_id, payer_id, payee_id, kind, amount_cents, currency, status, provider, provider_intent_id, created_at, updated_at
`

type CreatePaymentParams struct {
	BookingID        uuid.UUID `json:"booking_id"`
	PayerID          uuid.UUID `json:"payer_id"`
	PayeeID          uuid.UUID `json:"payee_id"`
	Kind             string    `json:"kind"`
	AmountCents      int64     `json:"amount_cents"`
	Currency         string    `json:"currency"`
	Provider         string    `json:"provider"`
	ProviderIntentID string    `json:"provider_intent_id"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.BookingID,
		arg.PayerID,
		arg.PayeeID,
		arg.Kind,
		arg.AmountCents,
		arg.Currency,
		arg.Provider,
		arg.ProviderIntentID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.PayerID,
		&i.PayeeID,
		&i.Kind,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.ProviderIntentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, booking_id, payer_id, payee_id, kind, amount_cents, currency, status, provider, provider_intent_id, created_at, updated_at FROM payments WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.PayerID,
		&i.PayeeID,
		&i.Kind,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.ProviderIntentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByProviderIntent = `-- name: GetPaymentByProviderIntent :one
SELECT id, booking_id, payer_id, payee_id, kind, amount_cents, currency, status, provider, provider_intent_id, created_at, updated_at FROM payments
WHERE provider = $1 AND provider_intent_id = $2
`

type GetPaymentByProviderIntentParams struct {
	Provider         string `json:"provider"`
	ProviderIntentID string `json:"provider_intent_id"`
}

func (q *Queries) GetPaymentByProviderIntent(ctx context.Context, arg GetPaymentByProviderIntentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByProviderIntent, arg.Provider, arg.ProviderIntentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.PayerID,
		&i.PayeeID,
		&i.Kind,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.ProviderIntentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWebhookEvent = `-- name: InsertWebhookEvent :one
INSERT INTO payment_webhook_events (provider, event_id, payload)
VALUES ($1, $2, $3)
ON CONFLICT (provider, event_id) DO NOTHING
RETURNING id, provider, event_id, payload, processed, received_at
`

type InsertWebhookEventParams struct {
	Provider string `json:"provider"`
	EventID  string `json:"event_id"`
	Payload  []byte `json:"payload"`
}

func (q *Queries) InsertWebhookEvent(ctx context.Context, arg InsertWebhookEventParams) (PaymentWebhookEvent, error) {
	row := q.db.QueryRow(ctx, insertWebhookEvent, arg.Provider, arg.EventID, arg.Payload)
	var i PaymentWebhookEvent
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.EventID,
		&i.Payload,
		&i.Processed,
		&i.ReceivedAt,
	)
	return i, err
}

const listPaymentsByBooking = `-- name: ListPaymentsByBooking :many
SELECT id, booking_id, payer_id, payee_id, kind, amount_cents, currency, status, provider, provider_intent_id, created_at, updated_at FROM payments
WHERE booking_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPaymentsByBooking(ctx context.Context, bookingID uuid.UUID) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByBooking, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.PayerID,
			&i.PayeeID,
			&i.Kind,
			&i.AmountCents,
			&i.Currency,
			&i.Status,
			&i.Provider,
			&i.ProviderIntentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByPayee = `-- name: ListPaymentsByPayee :many
SELECT id, booking_id, payer_id, payee_id, kind, amount_cents, currency, status, provider, provider_intent_id, created_at, updated_at FROM payments
WHERE payee_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPaymentsByPayeeParams struct {
	PayeeID uuid.UUID `json:"payee_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) ListPaymentsByPayee(ctx context.Context, arg ListPaymentsByPayeeParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByPayee, arg.PayeeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.PayerID,
			&i.PayeeID,
			&i.Kind,
			&i.AmountCents,
			&i.Currency,
			&i.Status,
			&i.Provider,
			&i.ProviderIntentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByPayer = `-- name: ListPaymentsByPayer :many
SELECT id, booking_id, payer_id, payee_id, kind, amount_cents, currency, status, provider, provider_intent_id, created_at, updated_at FROM payments
WHERE payer_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPaymentsByPayerParams struct {
	PayerID uuid.UUID `json:"payer_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) ListPaymentsByPayer(ctx context.Context, arg ListPaymentsByPayerParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByPayer, arg.PayerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.PayerID,
			&i.PayeeID,
			&i.Kind,
			&i.AmountCents,
			&i.Currency,
			&i.Status,
			&i.Provider,
			&i.ProviderIntentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnprocessedWebhookEvents = `-- name: ListUnprocessedWebhookEvents :many
SELECT id, provider, event_id, payload, processed, received_at FROM payment_webhook_events
WHERE processed = false
ORDER BY received_at ASC
LIMIT $1
`

func (q *Queries) ListUnprocessedWebhookEvents(ctx context.Context, limit int32) ([]PaymentWebhookEvent, error) {
	rows, err := q.db.Query(ctx, listUnprocessedWebhookEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentWebhookEvent
	for rows.Next() {
		var i PaymentWebhookEvent
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.EventID,
			&i.Payload,
			&i.Processed,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookProcessed = `-- name: MarkWebhookProcessed :exec
UPDATE payment_webhook_events
SET processed = true
WHERE id = $1
`

func (q *Queries) MarkWebhookProcessed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markWebhookProcessed, id)
	return err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments
SET status     = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, booking_id, payer_id, payee_id, kind, amount_cents, currency, status, provider, provider_intent_id, created_at, updated_at
`

type UpdatePaymentStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatus, arg.ID, arg.Status)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.PayerID,
		&i.PayeeID,
		&i.Kind,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.ProviderIntentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
