// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_requests.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const attachCheckoutSession = `-- name: AttachCheckoutSession :one
UPDATE payment_requests
SET stripe_checkout_session_id = $1,
    stripe_payment_intent_id   = $2,
    status                     = 'processing',
    updated_at                 = now()
WHERE id = $3
RETURNING id, artist_id, booking_request_id, type, status, currency, amount_cents, platform_fee_cents, client_charge_cents, fee_payer, amount_refunded_cents, client_email, client_name, description, public_token, stripe_checkout_session_id, stripe_payment_intent_id, expires_at, paid_at, canceled_at, created_at, updated_at, last_emailed_at
`

type AttachCheckoutSessionParams struct {
	StripeCheckoutSessionID *string   `json:"stripe_checkout_session_id"`
	StripePaymentIntentID   *string   `json:"stripe_payment_intent_id"`
	ID                      uuid.UUID `json:"id"`
}

func (q *Queries) AttachCheckoutSession(ctx context.Context, arg AttachCheckoutSessionParams) (PaymentRequest, error) {
	row := q.db.QueryRow(ctx, attachCheckoutSession, arg.StripeCheckoutSessionID, arg.StripePaymentIntentID, arg.ID)
	var i PaymentRequest
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.BookingRequestID,
		&i.Type,
		&i.Status,
		&i.Currency,
		&i.AmountCents,
		&i.PlatformFeeCents,
		&i.ClientChargeCents,
		&i.FeePayer,
		&i.AmountRefundedCents,
		&i.ClientEmail,
		&i.ClientName,
		&i.Description,
		&i.PublicToken,
		&i.StripeCheckoutSessionID,
		&i.StripePaymentIntentID,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastEmailedAt,
	)
	return i, err
}

const cancelPaymentRequest = `-- name: CancelPaymentRequest :one
UPDATE payment_requests
SET status      = 'canceled',
    canceled_at = now(),
    updated_at  = now()
WHERE id = $1 AND artist_id = $2
  AND status IN ('requested', 'processing')
RETURNING id, artist_id, booking_request_id, type, status, currency, amount_cents, platform_fee_cents, client_charge_cents, fee_payer, amount_refunded_cents, client_email, client_name, description, public_token, stripe_checkout_session_id, stripe_payment_intent_id, expires_at, paid_at, canceled_at, created_at, updated_at, last_emailed_at
`

type CancelPaymentRequestParams struct {
	ID       uuid.UUID `json:"id"`
	ArtistID uuid.UUID `json:"artist_id"`
}

func (q *Queries) CancelPaymentRequest(ctx context.Context, arg CancelPaymentRequestParams) (PaymentRequest, error) {
	row := q.db.QueryRow(ctx, cancelPaymentRequest, arg.ID, arg.ArtistID)
	var i PaymentRequest
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.BookingRequestID,
		&i.Type,
		&i.Status,
		&i.Currency,
		&i.AmountCents,
		&i.PlatformFeeCents,
		&i.ClientChargeCents,
		&i.FeePayer,
		&i.AmountRefundedCents,
		&i.ClientEmail,
		&i.ClientName,
		&i.Description,
		&i.PublicToken,
		&i.StripeCheckoutSessionID,
		&i.StripePaymentIntentID,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastEmailedAt,
	)
	return i, err
}

const countLivePaymentRequests = `-- name: CountLivePaymentRequests :one
SELECT COUNT(*) FROM payment_requests
WHERE booking_request_id = $1
  AND type = $2
  AND status IN ('requested', 'processing', 'paid')
`

type CountLivePaymentRequestsParams struct {
	BookingRequestID uuid.UUID `json:"booking_request_id"`
	Type             string    `json:"type"`
}

func (q *Queries) CountLivePaymentRequests(ctx context.Context, arg CountLivePaymentRequestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLivePaymentRequests, arg.BookingRequestID, arg.Type)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPaymentRequest = `-- name: CreatePaymentRequest :one
INSERT INTO payment_requests (
    artist_id, booking_request_id, type, currency,
    amount_cents, platform_fee_cents, client_charge_cents, fee_payer,
    client_email, client_name, description, public_token, expires_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11, $12, $13
)
RETURNING id, artist_id, booking_request_id, type, status, currency, amount_cents, platform_fee_cents, client_charge_cents, fee_payer, amount_refunded_cents, client_email, client_name, description, public_token, stripe_checkout_session_id, stripe_payment_intent_id, expires_at, paid_at, canceled_at, created_at, updated_at, last_emailed_at
`

type CreatePaymentRequestParams struct {
	ArtistID          uuid.UUID          `json:"artist_id"`
	BookingRequestID  uuid.UUID          `json:"booking_request_id"`
	Type              string             `json:"type"`
	Currency          string             `json:"currency"`
	AmountCents       int64              `json:"amount_cents"`
	PlatformFeeCents  int64              `json:"platform_fee_cents"`
	ClientChargeCents int64              `json:"client_charge_cents"`
	FeePayer          string             `json:"fee_payer"`
	ClientEmail       string             `json:"client_email"`
	ClientName        string             `json:"client_name"`
	Description       string             `json:"description"`
	PublicToken       string             `json:"public_token"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePaymentRequest(ctx context.Context, arg CreatePaymentRequestParams) (PaymentRequest, error) {
	row := q.db.QueryRow(ctx, createPaymentRequest,
		arg.ArtistID,
		arg.BookingRequestID,
		arg.Type,
		arg.Currency,
		arg.AmountCents,
		arg.PlatformFeeCents,
		arg.ClientChargeCents,
		arg.FeePayer,
		arg.ClientEmail,
		arg.ClientName,
		arg.Description,
		arg.PublicToken,
		arg.ExpiresAt,
	)
	var i PaymentRequest
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.BookingRequestID,
		&i.Type,
		&i.Status,
		&i.Currency,
		&i.AmountCents,
		&i.PlatformFeeCents,
		&i.ClientChargeCents,
		&i.FeePayer,
		&i.AmountRefundedCents,
		&i.ClientEmail,
		&i.ClientName,
		&i.Description,
		&i.PublicToken,
		&i.StripeCheckoutSessionID,
		&i.StripePaymentIntentID,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastEmailedAt,
	)
	return i, err
}

const getPaymentRequestByPaymentIntent = `-- name: GetPaymentRequestByPaymentIntent :one
SELECT id, artist_id, booking_request_id, type, status, currency, amount_cents, platform_fee_cents, client_charge_cents, fee_payer, amount_refunded_cents, client_email, client_name, description, public_token, stripe_checkout_session_id, stripe_payment_intent_id, expires_at, paid_at, canceled_at, created_at, updated_at, last_emailed_at FROM payment_requests WHERE stripe_payment_intent_id = $1
`

func (q *Queries) GetPaymentRequestByPaymentIntent(ctx context.Context, stripePaymentIntentID *string) (PaymentRequest, error) {
	row := q.db.QueryRow(ctx, getPaymentRequestByPaymentIntent, stripePaymentIntentID)
	var i PaymentRequest
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.BookingRequestID,
		&i.Type,
		&i.Status,
		&i.Currency,
		&i.AmountCents,
		&i.PlatformFeeCents,
		&i.ClientChargeCents,
		&i.FeePayer,
		&i.AmountRefundedCents,
		&i.ClientEmail,
		&i.ClientName,
		&i.Description,
		&i.PublicToken,
		&i.StripeCheckoutSessionID,
		&i.StripePaymentIntentID,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastEmailedAt,
	)
	return i, err
}

const getPaymentRequestByToken = `-- name: GetPaymentRequestByToken :one
SELECT id, artist_id, booking_request_id, type, status, currency, amount_cents, platform_fee_cents, client_charge_cents, fee_payer, amount_refunded_cents, client_email, client_name, description, public_token, stripe_checkout_session_id, stripe_payment_intent_id, expires_at, paid_at, canceled_at, created_at, updated_at, last_emailed_at FROM payment_requests WHERE public_token = $1
`

func (q *Queries) GetPaymentRequestByToken(ctx context.Context, publicToken string) (PaymentRequest, error) {
	row := q.db.QueryRow(ctx, getPaymentRequestByToken, publicToken)
	var i PaymentRequest
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.BookingRequestID,
		&i.Type,
		&i.Status,
		&i.Currency,
		&i.AmountCents,
		&i.PlatformFeeCents,
		&i.ClientChargeCents,
		&i.FeePayer,
		&i.AmountRefundedCents,
		&i.ClientEmail,
		&i.ClientName,
		&i.Description,
		&i.PublicToken,
		&i.StripeCheckoutSessionID,
		&i.StripePaymentIntentID,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastEmailedAt,
	)
	return i, err
}

const getPaymentRequestForArtist = `-- name: GetPaymentRequestForArtist :one
SELECT id, artist_id, booking_request_id, type, status, currency, amount_cents, platform_fee_cents, client_charge_cents, fee_payer, amount_refunded_cents, client_email, client_name, description, public_token, stripe_checkout_session_id, stripe_payment_intent_id, expires_at, paid_at, canceled_at, created_at, updated_at, last_emailed_at FROM payment_requests WHERE id = $1 AND artist_id = $2
`

type GetPaymentRequestForArtistParams struct {
	ID       uuid.UUID `json:"id"`
	ArtistID uuid.UUID `json:"artist_id"`
}

func (q *Queries) GetPaymentRequestForArtist(ctx context.Context, arg GetPaymentRequestForArtistParams) (PaymentRequest, error) {
	row := q.db.QueryRow(ctx, getPaymentRequestForArtist, arg.ID, arg.ArtistID)
	var i PaymentRequest
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.BookingRequestID,
		&i.Type,
		&i.Status,
		&i.Currency,
		&i.AmountCents,
		&i.PlatformFeeCents,
		&i.ClientChargeCents,
		&i.FeePayer,
		&i.AmountRefundedCents,
		&i.ClientEmail,
		&i.ClientName,
		&i.Description,
		&i.PublicToken,
		&i.StripeCheckoutSessionID,
		&i.StripePaymentIntentID,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastEmailedAt,
	)
	return i, err
}

const listPaymentRequestsByArtist = `-- name: ListPaymentRequestsByArtist :many
SELECT id, artist_id, booking_request_id, type, status, currency, amount_cents, platform_fee_cents, client_charge_cents, fee_payer, amount_refunded_cents, client_email, client_name, description, public_token, stripe_checkout_session_id, stripe_payment_intent_id, expires_at, paid_at, canceled_at, created_at, updated_at, last_emailed_at FROM payment_requests
WHERE artist_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPaymentRequestsByArtist(ctx context.Context, artistID uuid.UUID) ([]PaymentRequest, error) {
	rows, err := q.db.Query(ctx, listPaymentRequestsByArtist, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentRequest
	for rows.Next() {
		var i PaymentRequest
		if err := rows.Scan(
			&i.ID,
			&i.ArtistID,
			&i.BookingRequestID,
			&i.Type,
			&i.Status,
			&i.Currency,
			&i.AmountCents,
			&i.PlatformFeeCents,
			&i.ClientChargeCents,
			&i.FeePayer,
			&i.AmountRefundedCents,
			&i.ClientEmail,
			&i.ClientName,
			&i.Description,
			&i.PublicToken,
			&i.StripeCheckoutSessionID,
			&i.StripePaymentIntentID,
			&i.ExpiresAt,
			&i.PaidAt,
			&i.CanceledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastEmailedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentRequestsByBooking = `-- name: ListPaymentRequestsByBooking :many
SELECT id, artist_id, booking_request_id, type, status, currency, amount_cents, platform_fee_cents, client_charge_cents, fee_payer, amount_refunded_cents, client_email, client_name, description, public_token, stripe_checkout_session_id, stripe_payment_intent_id, expires_at, paid_at, canceled_at, created_at, updated_at, last_emailed_at FROM payment_requests
WHERE booking_request_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPaymentRequestsByBooking(ctx context.Context, bookingRequestID uuid.UUID) ([]PaymentRequest, error) {
	rows, err := q.db.Query(ctx, listPaymentRequestsByBooking, bookingRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentRequest
	for rows.Next() {
		var i PaymentRequest
		if err := rows.Scan(
			&i.ID,
			&i.ArtistID,
			&i.BookingRequestID,
			&i.Type,
			&i.Status,
			&i.Currency,
			&i.AmountCents,
			&i.PlatformFeeCents,
			&i.ClientChargeCents,
			&i.FeePayer,
			&i.AmountRefundedCents,
			&i.ClientEmail,
			&i.ClientName,
			&i.Description,
			&i.PublicToken,
			&i.StripeCheckoutSessionID,
			&i.StripePaymentIntentID,
			&i.ExpiresAt,
			&i.PaidAt,
			&i.CanceledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastEmailedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentRequestEmailed = `-- name: MarkPaymentRequestEmailed :one
UPDATE payment_requests
SET last_emailed_at = now(),
    updated_at      = now()
WHERE id = $1 AND artist_id = $2
RETURNING id, artist_id, booking_request_id, type, status, currency, amount_cents, platform_fee_cents, client_charge_cents, fee_payer, amount_refunded_cents, client_email, client_name, description, public_token, stripe_checkout_session_id, stripe_payment_intent_id, expires_at, paid_at, canceled_at, created_at, updated_at, last_emailed_at
`

type MarkPaymentRequestEmailedParams struct {
	ID       uuid.UUID `json:"id"`
	ArtistID uuid.UUID `json:"artist_id"`
}

func (q *Queries) MarkPaymentRequestEmailed(ctx context.Context, arg MarkPaymentRequestEmailedParams) (PaymentRequest, error) {
	row := q.db.QueryRow(ctx, markPaymentRequestEmailed, arg.ID, arg.ArtistID)
	var i PaymentRequest
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.BookingRequestID,
		&i.Type,
		&i.Status,
		&i.Currency,
		&i.AmountCents,
		&i.PlatformFeeCents,
		&i.ClientChargeCents,
		&i.FeePayer,
		&i.AmountRefundedCents,
		&i.ClientEmail,
		&i.ClientName,
		&i.Description,
		&i.PublicToken,
		&i.StripeCheckoutSessionID,
		&i.StripePaymentIntentID,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastEmailedAt,
	)
	return i, err
}

const markPaymentRequestExpiredBySession = `-- name: MarkPaymentRequestExpiredBySession :one
UPDATE payment_requests
SET status     = 'expired',
    updated_at = now()
WHERE stripe_checkout_session_id = $1
  AND status IN ('requested', 'processing')
RETURNING id, artist_id, booking_request_id, type, status, currency, amount_cents, platform_fee_cents, client_charge_cents, fee_payer, amount_refunded_cents, client_email, client_name, description, public_token, stripe_checkout_session_id, stripe_payment_intent_id, expires_at, paid_at, canceled_at, created_at, updated_at, last_emailed_at
`

func (q *Queries) MarkPaymentRequestExpiredBySession(ctx context.Context, stripeCheckoutSessionID *string) (PaymentRequest, error) {
	row := q.db.QueryRow(ctx, markPaymentRequestExpiredBySession, stripeCheckoutSessionID)
	var i PaymentRequest
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.BookingRequestID,
		&i.Type,
		&i.Status,
		&i.Currency,
		&i.AmountCents,
		&i.PlatformFeeCents,
		&i.ClientChargeCents,
		&i.FeePayer,
		&i.AmountRefundedCents,
		&i.ClientEmail,
		&i.ClientName,
		&i.Description,
		&i.PublicToken,
		&i.StripeCheckoutSessionID,
		&i.StripePaymentIntentID,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastEmailedAt,
	)
	return i, err
}

const markPaymentRequestFailedByPaymentIntent = `-- name: MarkPaymentRequestFailedByPaymentIntent :one
UPDATE payment_requests
SET status     = 'failed',
    updated_at = now()
WHERE stripe_payment_intent_id = $1
  AND status NOT IN ('paid', 'refunded')
RETURNING id, artist_id, booking_request_id, type, status, currency, amount_cents, platform_fee_cents, client_charge_cents, fee_payer, amount_refunded_cents, client_email, client_name, description, public_token, stripe_checkout_session_id, stripe_payment_intent_id, expires_at, paid_at, canceled_at, created_at, updated_at, last_emailed_at
`

func (q *Queries) MarkPaymentRequestFailedByPaymentIntent(ctx context.Context, stripePaymentIntentID *string) (PaymentRequest, error) {
	row := q.db.QueryRow(ctx, markPaymentRequestFailedByPaymentIntent, stripePaymentIntentID)
	var i PaymentRequest
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.BookingRequestID,
		&i.Type,
		&i.Status,
		&i.Currency,
		&i.AmountCents,
		&i.PlatformFeeCents,
		&i.ClientChargeCents,
		&i.FeePayer,
		&i.AmountRefundedCents,
		&i.ClientEmail,
		&i.ClientName,
		&i.Description,
		&i.PublicToken,
		&i.StripeCheckoutSessionID,
		&i.StripePaymentIntentID,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastEmailedAt,
	)
	return i, err
}

const markPaymentRequestPaidByPaymentIntent = `-- name: MarkPaymentRequestPaidByPaymentIntent :one
UPDATE payment_requests
SET status     = 'paid',
    paid_at    = now(),
    updated_at = now()
WHERE stripe_payment_intent_id = $1
  AND status NOT IN ('paid', 'refunded')
RETURNING id, artist_id, booking_request_id, type, status, currency, amount_cents, platform_fee_cents, client_charge_cents, fee_payer, amount_refunded_cents, client_email, client_name, description, public_token, stripe_checkout_session_id, stripe_payment_intent_id, expires_at, paid_at, canceled_at, created_at, updated_at, last_emailed_at
`

func (q *Queries) MarkPaymentRequestPaidByPaymentIntent(ctx context.Context, stripePaymentIntentID *string) (PaymentRequest, error) {
	row := q.db.QueryRow(ctx, markPaymentRequestPaidByPaymentIntent, stripePaymentIntentID)
	var i PaymentRequest
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.BookingRequestID,
		&i.Type,
		&i.Status,
		&i.Currency,
		&i.AmountCents,
		&i.PlatformFeeCents,
		&i.ClientChargeCents,
		&i.FeePayer,
		&i.AmountRefundedCents,
		&i.ClientEmail,
		&i.ClientName,
		&i.Description,
		&i.PublicToken,
		&i.StripeCheckoutSessionID,
		&i.StripePaymentIntentID,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastEmailedAt,
	)
	return i, err
}

const markPaymentRequestPaidBySession = `-- name: MarkPaymentRequestPaidBySession :one
UPDATE payment_requests
SET status                   = 'paid',
    stripe_payment_intent_id = COALESCE($1, stripe_payment_intent_id),
    paid_at                  = now(),
    updated_at               = now()
WHERE stripe_checkout_session_id = $2
  AND status NOT IN ('paid', 'refunded')
RETURNING id, artist_id, booking_request_id, type, status, currency, amount_cents, platform_fee_cents, client_charge_cents, fee_payer, amount_refunded_cents, client_email, client_name, description, public_token, stripe_checkout_session_id, stripe_payment_intent_id, expires_at, paid_at, canceled_at, created_at, updated_at, last_emailed_at
`

type MarkPaymentRequestPaidBySessionParams struct {
	StripePaymentIntentID   *string `json:"stripe_payment_intent_id"`
	StripeCheckoutSessionID *string `json:"stripe_checkout_session_id"`
}

func (q *Queries) MarkPaymentRequestPaidBySession(ctx context.Context, arg MarkPaymentRequestPaidBySessionParams) (PaymentRequest, error) {
	row := q.db.QueryRow(ctx, markPaymentRequestPaidBySession, arg.StripePaymentIntentID, arg.StripeCheckoutSessionID)
	var i PaymentRequest
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.BookingRequestID,
		&i.Type,
		&i.Status,
		&i.Currency,
		&i.AmountCents,
		&i.PlatformFeeCents,
		&i.ClientChargeCents,
		&i.FeePayer,
		&i.AmountRefundedCents,
		&i.ClientEmail,
		&i.ClientName,
		&i.Description,
		&i.PublicToken,
		&i.StripeCheckoutSessionID,
		&i.StripePaymentIntentID,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastEmailedAt,
	)
	return i, err
}

const refundPaymentRequestByPaymentIntent = `-- name: RefundPaymentRequestByPaymentIntent :one
UPDATE payment_requests
SET status                = 'refunded',
    amount_refunded_cents = $1,
    updated_at            = now()
WHERE stripe_payment_intent_id = $2
RETURNING id, artist_id, booking_request_id, type, status, currency, amount_cents, platform_fee_cents, client_charge_cents, fee_payer, amount_refunded_cents, client_email, client_name, description, public_token, stripe_checkout_session_id, stripe_payment_intent_id, expires_at, paid_at, canceled_at, created_at, updated_at, last_emailed_at
`

type RefundPaymentRequestByPaymentIntentParams struct {
	AmountRefundedCents   int64   `json:"amount_refunded_cents"`
	StripePaymentIntentID *string `json:"stripe_payment_intent_id"`
}

func (q *Queries) RefundPaymentRequestByPaymentIntent(ctx context.Context, arg RefundPaymentRequestByPaymentIntentParams) (PaymentRequest, error) {
	row := q.db.QueryRow(ctx, refundPaymentRequestByPaymentIntent, arg.AmountRefundedCents, arg.StripePaymentIntentID)
	var i PaymentRequest
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.BookingRequestID,
		&i.Type,
		&i.Status,
		&i.Currency,
		&i.AmountCents,
		&i.PlatformFeeCents,
		&i.ClientChargeCents,
		&i.FeePayer,
		&i.AmountRefundedCents,
		&i.ClientEmail,
		&i.ClientName,
		&i.Description,
		&i.PublicToken,
		&i.StripeCheckoutSessionID,
		&i.StripePaymentIntentID,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastEmailedAt,
	)
	return i, err
}

const setBookingDepositStatus = `-- name: SetBookingDepositStatus :exec
UPDATE booking_requests
SET deposit_status = $1::text,
    updated_at     = now()
WHERE id = $2
`

type SetBookingDepositStatusParams struct {
	DepositStatus    string    `json:"deposit_status"`
	BookingRequestID uuid.UUID `json:"booking_request_id"`
}

func (q *Queries) SetBookingDepositStatus(ctx context.Context, arg SetBookingDepositStatusParams) error {
	_, err := q.db.Exec(ctx, setBookingDepositStatus, arg.DepositStatus, arg.BookingRequestID)
	return err
}
