// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: phone_verifications.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumePhoneVerification = `-- name: ConsumePhoneVerification :exec
UPDATE phone_verifications
SET consumed_at = now()
WHERE id = $1 AND consumed_at IS NULL
`

func (q *Queries) ConsumePhoneVerification(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumePhoneVerification, id)
	return err
}

const createPhoneVerification = `-- name: CreatePhoneVerification :one
INSERT INTO phone_verifications (user_id, phone, code_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, phone, code_hash, attempts, expires_at, consumed_at, created_at
`

type CreatePhoneVerificationParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	Phone     string             `json:"phone"`
	CodeHash  string             `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePhoneVerification(ctx context.Context, arg CreatePhoneVerificationParams) (PhoneVerification, error) {
	row := q.db.QueryRow(ctx, createPhoneVerification,
		arg.UserID,
		arg.Phone,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	var i PhoneVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Phone,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredPhoneVerifications = `-- name: DeleteExpiredPhoneVerifications :execrows
DELETE FROM phone_verifications
WHERE expires_at < now() - INTERVAL '24 hours'
`

func (q *Queries) DeleteExpiredPhoneVerifications(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredPhoneVerifications)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActivePhoneVerification = `-- name: GetActivePhoneVerification :one
SELECT id, user_id, phone, code_hash, attempts, expires_at, consumed_at, created_at FROM phone_verifications
WHERE id = $1
  AND consumed_at IS NULL
  AND expires_at > now()
`

func (q *Queries) GetActivePhoneVerification(ctx context.Context, id uuid.UUID) (PhoneVerification, error) {
	row := q.db.QueryRow(ctx, getActivePhoneVerification, id)
	var i PhoneVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Phone,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementPhoneVerificationAttempts = `-- name: IncrementPhoneVerificationAttempts :exec
UPDATE phone_verifications
SET attempts = attempts + 1
WHERE id = $1
`

func (q *Queries) IncrementPhoneVerificationAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementPhoneVerificationAttempts, id)
	return err
}

const refreshPhoneVerificationCode = `-- name: RefreshPhoneVerificationCode :exec
UPDATE phone_verifications
SET code_hash = $2,
    expires_at = $3,
    attempts = 0
WHERE id = $1 AND consumed_at IS NULL
`

type RefreshPhoneVerificationCodeParams struct {
	ID        uuid.UUID          `json:"id"`
	CodeHash  string             `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Used when the user requests a resend. Rotates the code on the same
// verification record (preserving its id, so the frontend's stored
// verificationId keeps working) and resets the attempt counter.
func (q *Queries) RefreshPhoneVerificationCode(ctx context.Context, arg RefreshPhoneVerificationCodeParams) error {
	_, err := q.db.Exec(ctx, refreshPhoneVerificationCode, arg.ID, arg.CodeHash, arg.ExpiresAt)
	return err
}

const revokeActivePhoneVerificationsForUser = `-- name: RevokeActivePhoneVerificationsForUser :exec
UPDATE phone_verifications
SET consumed_at = now()
WHERE user_id = $1 AND consumed_at IS NULL
`

func (q *Queries) RevokeActivePhoneVerificationsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeActivePhoneVerificationsForUser, userID)
	return err
}
