// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: portfolio_items.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archivePortfolioItem = `-- name: ArchivePortfolioItem :one
UPDATE portfolio_items
SET status      = 'archived',
    archived_at = now(),
    updated_at  = now()
WHERE id = $1
  AND status <> 'archived'
RETURNING id, artist_id, status, title, description, completion_date, image_keys, styles, placement, color_type, approx_size_inches, healed, session_count, total_minutes, archived_at, published_at, created_at, updated_at
`

func (q *Queries) ArchivePortfolioItem(ctx context.Context, id uuid.UUID) (PortfolioItem, error) {
	row := q.db.QueryRow(ctx, archivePortfolioItem, id)
	var i PortfolioItem
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.CompletionDate,
		&i.ImageKeys,
		&i.Styles,
		&i.Placement,
		&i.ColorType,
		&i.ApproxSizeInches,
		&i.Healed,
		&i.SessionCount,
		&i.TotalMinutes,
		&i.ArchivedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countPortfolioItemsByArtist = `-- name: CountPortfolioItemsByArtist :one
SELECT
    COUNT(*) FILTER (
        WHERE $1::text IS NULL OR status = $1
    )                                              AS total,
    COUNT(*) FILTER (WHERE status = 'published')   AS published
FROM portfolio_items
WHERE artist_id = $2
`

type CountPortfolioItemsByArtistParams struct {
	Status   *string   `json:"status"`
	ArtistID uuid.UUID `json:"artist_id"`
}

type CountPortfolioItemsByArtistRow struct {
	Total     int64 `json:"total"`
	Published int64 `json:"published"`
}

func (q *Queries) CountPortfolioItemsByArtist(ctx context.Context, arg CountPortfolioItemsByArtistParams) (CountPortfolioItemsByArtistRow, error) {
	row := q.db.QueryRow(ctx, countPortfolioItemsByArtist, arg.Status, arg.ArtistID)
	var i CountPortfolioItemsByArtistRow
	err := row.Scan(&i.Total, &i.Published)
	return i, err
}

const createPortfolioItem = `-- name: CreatePortfolioItem :one
INSERT INTO portfolio_items (
    artist_id,
    status,
    title,
    description,
    completion_date,
    image_keys,
    styles,
    placement,
    color_type,
    approx_size_inches,
    healed,
    session_count,
    total_minutes,
    published_at
)
VALUES (
    $1,
    $2,
    $3,
    $4::text,
    $5::date,
    $6::text[],
    $7::text[],
    $8::text,
    $9::text,
    $10::integer,
    $11,
    $12::integer,
    $13::integer,
    $14::timestamptz
)
RETURNING id, artist_id, status, title, description, completion_date, image_keys, styles, placement, color_type, approx_size_inches, healed, session_count, total_minutes, archived_at, published_at, created_at, updated_at
`

type CreatePortfolioItemParams struct {
	ArtistID         uuid.UUID          `json:"artist_id"`
	Status           string             `json:"status"`
	Title            string             `json:"title"`
	Description      *string            `json:"description"`
	CompletionDate   pgtype.Date        `json:"completion_date"`
	ImageKeys        []string           `json:"image_keys"`
	Styles           []string           `json:"styles"`
	Placement        *string            `json:"placement"`
	ColorType        *string            `json:"color_type"`
	ApproxSizeInches *int32             `json:"approx_size_inches"`
	Healed           bool               `json:"healed"`
	SessionCount     *int32             `json:"session_count"`
	TotalMinutes     *int32             `json:"total_minutes"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) CreatePortfolioItem(ctx context.Context, arg CreatePortfolioItemParams) (PortfolioItem, error) {
	row := q.db.QueryRow(ctx, createPortfolioItem,
		arg.ArtistID,
		arg.Status,
		arg.Title,
		arg.Description,
		arg.CompletionDate,
		arg.ImageKeys,
		arg.Styles,
		arg.Placement,
		arg.ColorType,
		arg.ApproxSizeInches,
		arg.Healed,
		arg.SessionCount,
		arg.TotalMinutes,
		arg.PublishedAt,
	)
	var i PortfolioItem
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.CompletionDate,
		&i.ImageKeys,
		&i.Styles,
		&i.Placement,
		&i.ColorType,
		&i.ApproxSizeInches,
		&i.Healed,
		&i.SessionCount,
		&i.TotalMinutes,
		&i.ArchivedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePortfolioItem = `-- name: DeletePortfolioItem :exec
DELETE FROM portfolio_items WHERE id = $1
`

func (q *Queries) DeletePortfolioItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePortfolioItem, id)
	return err
}

const getPortfolioItem = `-- name: GetPortfolioItem :one
SELECT id, artist_id, status, title, description, completion_date, image_keys, styles, placement, color_type, approx_size_inches, healed, session_count, total_minutes, archived_at, published_at, created_at, updated_at FROM portfolio_items WHERE id = $1
`

func (q *Queries) GetPortfolioItem(ctx context.Context, id uuid.UUID) (PortfolioItem, error) {
	row := q.db.QueryRow(ctx, getPortfolioItem, id)
	var i PortfolioItem
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.CompletionDate,
		&i.ImageKeys,
		&i.Styles,
		&i.Placement,
		&i.ColorType,
		&i.ApproxSizeInches,
		&i.Healed,
		&i.SessionCount,
		&i.TotalMinutes,
		&i.ArchivedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPortfolioItemsByArtist = `-- name: ListPortfolioItemsByArtist :many
SELECT id, artist_id, status, title, description, completion_date, image_keys, styles, placement, color_type, approx_size_inches, healed, session_count, total_minutes, archived_at, published_at, created_at, updated_at
FROM portfolio_items
WHERE artist_id = $1
  AND ($2::text IS NULL OR status = $2)
ORDER BY created_at DESC
LIMIT $4
OFFSET $3
`

type ListPortfolioItemsByArtistParams struct {
	ArtistID uuid.UUID `json:"artist_id"`
	Status   *string   `json:"status"`
	Off      int32     `json:"off"`
	Lim      int32     `json:"lim"`
}

func (q *Queries) ListPortfolioItemsByArtist(ctx context.Context, arg ListPortfolioItemsByArtistParams) ([]PortfolioItem, error) {
	rows, err := q.db.Query(ctx, listPortfolioItemsByArtist,
		arg.ArtistID,
		arg.Status,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PortfolioItem
	for rows.Next() {
		var i PortfolioItem
		if err := rows.Scan(
			&i.ID,
			&i.ArtistID,
			&i.Status,
			&i.Title,
			&i.Description,
			&i.CompletionDate,
			&i.ImageKeys,
			&i.Styles,
			&i.Placement,
			&i.ColorType,
			&i.ApproxSizeInches,
			&i.Healed,
			&i.SessionCount,
			&i.TotalMinutes,
			&i.ArchivedAt,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishPortfolioItem = `-- name: PublishPortfolioItem :one
UPDATE portfolio_items
SET status       = 'published',
    published_at = COALESCE(published_at, now()),
    updated_at   = now()
WHERE id = $1
  AND status = 'draft'
RETURNING id, artist_id, status, title, description, completion_date, image_keys, styles, placement, color_type, approx_size_inches, healed, session_count, total_minutes, archived_at, published_at, created_at, updated_at
`

func (q *Queries) PublishPortfolioItem(ctx context.Context, id uuid.UUID) (PortfolioItem, error) {
	row := q.db.QueryRow(ctx, publishPortfolioItem, id)
	var i PortfolioItem
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.CompletionDate,
		&i.ImageKeys,
		&i.Styles,
		&i.Placement,
		&i.ColorType,
		&i.ApproxSizeInches,
		&i.Healed,
		&i.SessionCount,
		&i.TotalMinutes,
		&i.ArchivedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unarchivePortfolioItem = `-- name: UnarchivePortfolioItem :one
UPDATE portfolio_items
SET status      = CASE
                      WHEN published_at IS NOT NULL THEN 'published'
                      ELSE 'draft'
                  END,
    archived_at = NULL,
    updated_at  = now()
WHERE id = $1
  AND status = 'archived'
RETURNING id, artist_id, status, title, description, completion_date, image_keys, styles, placement, color_type, approx_size_inches, healed, session_count, total_minutes, archived_at, published_at, created_at, updated_at
`

func (q *Queries) UnarchivePortfolioItem(ctx context.Context, id uuid.UUID) (PortfolioItem, error) {
	row := q.db.QueryRow(ctx, unarchivePortfolioItem, id)
	var i PortfolioItem
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.CompletionDate,
		&i.ImageKeys,
		&i.Styles,
		&i.Placement,
		&i.ColorType,
		&i.ApproxSizeInches,
		&i.Healed,
		&i.SessionCount,
		&i.TotalMinutes,
		&i.ArchivedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePortfolioItem = `-- name: UpdatePortfolioItem :one
UPDATE portfolio_items
SET title              = $1,
    description        = $2::text,
    completion_date    = $3::date,
    image_keys         = $4::text[],
    styles             = $5::text[],
    placement          = $6::text,
    color_type         = $7::text,
    approx_size_inches = $8::integer,
    healed             = $9,
    session_count      = $10::integer,
    total_minutes      = $11::integer,
    updated_at         = now()
WHERE id = $12
RETURNING id, artist_id, status, title, description, completion_date, image_keys, styles, placement, color_type, approx_size_inches, healed, session_count, total_minutes, archived_at, published_at, created_at, updated_at
`

type UpdatePortfolioItemParams struct {
	Title            string      `json:"title"`
	Description      *string     `json:"description"`
	CompletionDate   pgtype.Date `json:"completion_date"`
	ImageKeys        []string    `json:"image_keys"`
	Styles           []string    `json:"styles"`
	Placement        *string     `json:"placement"`
	ColorType        *string     `json:"color_type"`
	ApproxSizeInches *int32      `json:"approx_size_inches"`
	Healed           bool        `json:"healed"`
	SessionCount     *int32      `json:"session_count"`
	TotalMinutes     *int32      `json:"total_minutes"`
	ID               uuid.UUID   `json:"id"`
}

func (q *Queries) UpdatePortfolioItem(ctx context.Context, arg UpdatePortfolioItemParams) (PortfolioItem, error) {
	row := q.db.QueryRow(ctx, updatePortfolioItem,
		arg.Title,
		arg.Description,
		arg.CompletionDate,
		arg.ImageKeys,
		arg.Styles,
		arg.Placement,
		arg.ColorType,
		arg.ApproxSizeInches,
		arg.Healed,
		arg.SessionCount,
		arg.TotalMinutes,
		arg.ID,
	)
	var i PortfolioItem
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.CompletionDate,
		&i.ImageKeys,
		&i.Styles,
		&i.Placement,
		&i.ColorType,
		&i.ApproxSizeInches,
		&i.Healed,
		&i.SessionCount,
		&i.TotalMinutes,
		&i.ArchivedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
