// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: portfolios.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimFlashDesign = `-- name: ClaimFlashDesign :one
UPDATE flash_designs
SET status     = 'claimed',
    updated_at = now()
WHERE id = $1
  AND status IN ('available', 'reserved')
RETURNING id, artist_id, title, description, image_url, styles, placement, size_inches, price_cents, currency, repeatable, status, reserved_by, reserved_until, created_at, updated_at
`

func (q *Queries) ClaimFlashDesign(ctx context.Context, id uuid.UUID) (FlashDesign, error) {
	row := q.db.QueryRow(ctx, claimFlashDesign, id)
	var i FlashDesign
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Title,
		&i.Description,
		&i.ImageUrl,
		&i.Styles,
		&i.Placement,
		&i.SizeInches,
		&i.PriceCents,
		&i.Currency,
		&i.Repeatable,
		&i.Status,
		&i.ReservedBy,
		&i.ReservedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFlashDesign = `-- name: CreateFlashDesign :one
INSERT INTO flash_designs (
    artist_id, title, description, image_url, styles, placement,
    size_inches, price_cents, currency, repeatable
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, artist_id, title, description, image_url, styles, placement, size_inches, price_cents, currency, repeatable, status, reserved_by, reserved_until, created_at, updated_at
`

type CreateFlashDesignParams struct {
	ArtistID    uuid.UUID      `json:"artist_id"`
	Title       string         `json:"title"`
	Description string         `json:"description"`
	ImageUrl    string         `json:"image_url"`
	Styles      []string       `json:"styles"`
	Placement   *string        `json:"placement"`
	SizeInches  pgtype.Numeric `json:"size_inches"`
	PriceCents  int64          `json:"price_cents"`
	Currency    string         `json:"currency"`
	Repeatable  bool           `json:"repeatable"`
}

func (q *Queries) CreateFlashDesign(ctx context.Context, arg CreateFlashDesignParams) (FlashDesign, error) {
	row := q.db.QueryRow(ctx, createFlashDesign,
		arg.ArtistID,
		arg.Title,
		arg.Description,
		arg.ImageUrl,
		arg.Styles,
		arg.Placement,
		arg.SizeInches,
		arg.PriceCents,
		arg.Currency,
		arg.Repeatable,
	)
	var i FlashDesign
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Title,
		&i.Description,
		&i.ImageUrl,
		&i.Styles,
		&i.Placement,
		&i.SizeInches,
		&i.PriceCents,
		&i.Currency,
		&i.Repeatable,
		&i.Status,
		&i.ReservedBy,
		&i.ReservedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPortfolioItem = `-- name: CreatePortfolioItem :one
INSERT INTO portfolio_items (artist_id, image_url, caption, styles, placement, healed_photo)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, artist_id, image_url, caption, styles, placement, healed_photo, created_at
`

type CreatePortfolioItemParams struct {
	ArtistID    uuid.UUID `json:"artist_id"`
	ImageUrl    string    `json:"image_url"`
	Caption     string    `json:"caption"`
	Styles      []string  `json:"styles"`
	Placement   *string   `json:"placement"`
	HealedPhoto bool      `json:"healed_photo"`
}

func (q *Queries) CreatePortfolioItem(ctx context.Context, arg CreatePortfolioItemParams) (PortfolioItem, error) {
	row := q.db.QueryRow(ctx, createPortfolioItem,
		arg.ArtistID,
		arg.ImageUrl,
		arg.Caption,
		arg.Styles,
		arg.Placement,
		arg.HealedPhoto,
	)
	var i PortfolioItem
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.ImageUrl,
		&i.Caption,
		&i.Styles,
		&i.Placement,
		&i.HealedPhoto,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFlashDesign = `-- name: DeleteFlashDesign :exec
DELETE FROM flash_designs WHERE id = $1
`

func (q *Queries) DeleteFlashDesign(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFlashDesign, id)
	return err
}

const deletePortfolioItem = `-- name: DeletePortfolioItem :exec
DELETE FROM portfolio_items WHERE id = $1
`

func (q *Queries) DeletePortfolioItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePortfolioItem, id)
	return err
}

const getFlashDesign = `-- name: GetFlashDesign :one
SELECT id, artist_id, title, description, image_url, styles, placement, size_inches, price_cents, currency, repeatable, status, reserved_by, reserved_until, created_at, updated_at FROM flash_designs WHERE id = $1
`

func (q *Queries) GetFlashDesign(ctx context.Context, id uuid.UUID) (FlashDesign, error) {
	row := q.db.QueryRow(ctx, getFlashDesign, id)
	var i FlashDesign
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Title,
		&i.Description,
		&i.ImageUrl,
		&i.Styles,
		&i.Placement,
		&i.SizeInches,
		&i.PriceCents,
		&i.Currency,
		&i.Repeatable,
		&i.Status,
		&i.ReservedBy,
		&i.ReservedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPortfolioItem = `-- name: GetPortfolioItem :one
SELECT id, artist_id, image_url, caption, styles, placement, healed_photo, created_at FROM portfolio_items WHERE id = $1
`

func (q *Queries) GetPortfolioItem(ctx context.Context, id uuid.UUID) (PortfolioItem, error) {
	row := q.db.QueryRow(ctx, getPortfolioItem, id)
	var i PortfolioItem
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.ImageUrl,
		&i.Caption,
		&i.Styles,
		&i.Placement,
		&i.HealedPhoto,
		&i.CreatedAt,
	)
	return i, err
}

const listFlashDesigns = `-- name: ListFlashDesigns :many
SELECT id, artist_id, title, description, image_url, styles, placement, size_inches, price_cents, currency, repeatable, status, reserved_by, reserved_until, created_at, updated_at FROM flash_designs
WHERE ($1::text IS NULL OR status = $1)
  AND (cardinality($2::text[]) = 0 OR styles && $2::text[])
  AND ($3::uuid IS NULL OR artist_id = $3)
ORDER BY created_at DESC
LIMIT $5
OFFSET $4
`

type ListFlashDesignsParams struct {
	Status   *string     `json:"status"`
	Styles   []string    `json:"styles"`
	ArtistID pgtype.UUID `json:"artist_id"`
	Off      int32       `json:"off"`
	Lim      int32       `json:"lim"`
}

func (q *Queries) ListFlashDesigns(ctx context.Context, arg ListFlashDesignsParams) ([]FlashDesign, error) {
	rows, err := q.db.Query(ctx, listFlashDesigns,
		arg.Status,
		arg.Styles,
		arg.ArtistID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlashDesign
	for rows.Next() {
		var i FlashDesign
		if err := rows.Scan(
			&i.ID,
			&i.ArtistID,
			&i.Title,
			&i.Description,
			&i.ImageUrl,
			&i.Styles,
			&i.Placement,
			&i.SizeInches,
			&i.PriceCents,
			&i.Currency,
			&i.Repeatable,
			&i.Status,
			&i.ReservedBy,
			&i.ReservedUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPortfolioItemsByArtist = `-- name: ListPortfolioItemsByArtist :many
SELECT id, artist_id, image_url, caption, styles, placement, healed_photo, created_at FROM portfolio_items
WHERE artist_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPortfolioItemsByArtistParams struct {
	ArtistID uuid.UUID `json:"artist_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListPortfolioItemsByArtist(ctx context.Context, arg ListPortfolioItemsByArtistParams) ([]PortfolioItem, error) {
	rows, err := q.db.Query(ctx, listPortfolioItemsByArtist, arg.ArtistID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PortfolioItem
	for rows.Next() {
		var i PortfolioItem
		if err := rows.Scan(
			&i.ID,
			&i.ArtistID,
			&i.ImageUrl,
			&i.Caption,
			&i.Styles,
			&i.Placement,
			&i.HealedPhoto,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseFlashReservation = `-- name: ReleaseFlashReservation :one
UPDATE flash_designs
SET status         = 'available',
    reserved_by    = NULL,
    reserved_until = NULL,
    updated_at     = now()
WHERE id = $1
  AND status = 'reserved'
RETURNING id, artist_id, title, description, image_url, styles, placement, size_inches, price_cents, currency, repeatable, status, reserved_by, reserved_until, created_at, updated_at
`

func (q *Queries) ReleaseFlashReservation(ctx context.Context, id uuid.UUID) (FlashDesign, error) {
	row := q.db.QueryRow(ctx, releaseFlashReservation, id)
	var i FlashDesign
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Title,
		&i.Description,
		&i.ImageUrl,
		&i.Styles,
		&i.Placement,
		&i.SizeInches,
		&i.PriceCents,
		&i.Currency,
		&i.Repeatable,
		&i.Status,
		&i.ReservedBy,
		&i.ReservedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reserveFlashDesign = `-- name: ReserveFlashDesign :one
UPDATE flash_designs
SET status         = 'reserved',
    reserved_by    = $1,
    reserved_until = $2,
    updated_at     = now()
WHERE id = $3
  AND status = 'available'
RETURNING id, artist_id, title, description, image_url, styles, placement, size_inches, price_cents, currency, repeatable, status, reserved_by, reserved_until, created_at, updated_at
`

type ReserveFlashDesignParams struct {
	UserID        pgtype.UUID        `json:"user_id"`
	ReservedUntil pgtype.Timestamptz `json:"reserved_until"`
	ID            uuid.UUID          `json:"id"`
}

func (q *Queries) ReserveFlashDesign(ctx context.Context, arg ReserveFlashDesignParams) (FlashDesign, error) {
	row := q.db.QueryRow(ctx, reserveFlashDesign, arg.UserID, arg.ReservedUntil, arg.ID)
	var i FlashDesign
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Title,
		&i.Description,
		&i.ImageUrl,
		&i.Styles,
		&i.Placement,
		&i.SizeInches,
		&i.PriceCents,
		&i.Currency,
		&i.Repeatable,
		&i.Status,
		&i.ReservedBy,
		&i.ReservedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFlashDesign = `-- name: UpdateFlashDesign :one
UPDATE flash_designs
SET title       = COALESCE($1::text, title),
    description = COALESCE($2::text, description),
    image_url   = COALESCE($3::text, image_url),
    styles      = COALESCE($4::text[], styles),
    placement   = COALESCE($5::text, placement),
    size_inches = COALESCE($6::numeric, size_inches),
    price_cents = COALESCE($7::bigint, price_cents),
    currency    = COALESCE($8::text, currency),
    repeatable  = COALESCE($9::boolean, repeatable),
    updated_at  = now()
WHERE id = $10
RETURNING id, artist_id, title, description, image_url, styles, placement, size_inches, price_cents, currency, repeatable, status, reserved_by, reserved_until, created_at, updated_at
`

type UpdateFlashDesignParams struct {
	Title       *string        `json:"title"`
	Description *string        `json:"description"`
	ImageUrl    *string        `json:"image_url"`
	Styles      []string       `json:"styles"`
	Placement   *string        `json:"placement"`
	SizeInches  pgtype.Numeric `json:"size_inches"`
	PriceCents  *int64         `json:"price_cents"`
	Currency    *string        `json:"currency"`
	Repeatable  *bool          `json:"repeatable"`
	ID          uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateFlashDesign(ctx context.Context, arg UpdateFlashDesignParams) (FlashDesign, error) {
	row := q.db.QueryRow(ctx, updateFlashDesign,
		arg.Title,
		arg.Description,
		arg.ImageUrl,
		arg.Styles,
		arg.Placement,
		arg.SizeInches,
		arg.PriceCents,
		arg.Currency,
		arg.Repeatable,
		arg.ID,
	)
	var i FlashDesign
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Title,
		&i.Description,
		&i.ImageUrl,
		&i.Styles,
		&i.Placement,
		&i.SizeInches,
		&i.PriceCents,
		&i.Currency,
		&i.Repeatable,
		&i.Status,
		&i.ReservedBy,
		&i.ReservedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePortfolioItem = `-- name: UpdatePortfolioItem :one
UPDATE portfolio_items
SET caption      = COALESCE($1::text, caption),
    styles       = COALESCE($2::text[], styles),
    placement    = COALESCE($3::text, placement),
    healed_photo = COALESCE($4::boolean, healed_photo)
WHERE id = $5
RETURNING id, artist_id, image_url, caption, styles, placement, healed_photo, created_at
`

type UpdatePortfolioItemParams struct {
	Caption     *string   `json:"caption"`
	Styles      []string  `json:"styles"`
	Placement   *string   `json:"placement"`
	HealedPhoto *bool     `json:"healed_photo"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdatePortfolioItem(ctx context.Context, arg UpdatePortfolioItemParams) (PortfolioItem, error) {
	row := q.db.QueryRow(ctx, updatePortfolioItem,
		arg.Caption,
		arg.Styles,
		arg.Placement,
		arg.HealedPhoto,
		arg.ID,
	)
	var i PortfolioItem
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.ImageUrl,
		&i.Caption,
		&i.Styles,
		&i.Placement,
		&i.HealedPhoto,
		&i.CreatedAt,
	)
	return i, err
}
