// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ClaimFlashDesign(ctx context.Context, id uuid.UUID) (FlashDesign, error)
	ConsumePhoneVerification(ctx context.Context, id uuid.UUID) error
	CreateArtist(ctx context.Context, arg CreateArtistParams) (Artist, error)
	CreateFlashDesign(ctx context.Context, arg CreateFlashDesignParams) (FlashDesign, error)
	CreatePhoneVerification(ctx context.Context, arg CreatePhoneVerificationParams) (PhoneVerification, error)
	CreatePortfolioItem(ctx context.Context, arg CreatePortfolioItemParams) (PortfolioItem, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteArtist(ctx context.Context, id uuid.UUID) error
	DeleteExpiredPhoneVerifications(ctx context.Context) (int64, error)
	DeleteExpiredRefreshTokens(ctx context.Context) (int64, error)
	DeleteFlashDesign(ctx context.Context, id uuid.UUID) error
	DeletePortfolioItem(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetActivePhoneVerification(ctx context.Context, id uuid.UUID) (PhoneVerification, error)
	GetActiveRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetArtistAvailability(ctx context.Context, artistID uuid.UUID) (ArtistAvailability, error)
	GetArtistByHandle(ctx context.Context, handle string) (Artist, error)
	GetArtistByID(ctx context.Context, id uuid.UUID) (Artist, error)
	GetArtistByUserID(ctx context.Context, userID uuid.UUID) (Artist, error)
	GetFlashDesign(ctx context.Context, id uuid.UUID) (FlashDesign, error)
	GetPortfolioItem(ctx context.Context, id uuid.UUID) (PortfolioItem, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByPhone(ctx context.Context, phone *string) (User, error)
	IncrementPhoneVerificationAttempts(ctx context.Context, id uuid.UUID) error
	ListArtists(ctx context.Context, arg ListArtistsParams) ([]Artist, error)
	ListFlashDesigns(ctx context.Context, arg ListFlashDesignsParams) ([]FlashDesign, error)
	ListPortfolioItemsByArtist(ctx context.Context, arg ListPortfolioItemsByArtistParams) ([]PortfolioItem, error)
	MarkEmailVerified(ctx context.Context, id uuid.UUID) error
	MarkPhoneVerified(ctx context.Context, id uuid.UUID) error
	// Used when the user requests a resend. Rotates the code on the same
	// verification record (preserving its id, so the frontend's stored
	// verificationId keeps working) and resets the attempt counter.
	RefreshPhoneVerificationCode(ctx context.Context, arg RefreshPhoneVerificationCodeParams) error
	ReleaseFlashReservation(ctx context.Context, id uuid.UUID) (FlashDesign, error)
	ReserveFlashDesign(ctx context.Context, arg ReserveFlashDesignParams) (FlashDesign, error)
	RevokeActivePhoneVerificationsForUser(ctx context.Context, userID uuid.UUID) error
	RevokeAllRefreshTokensForUser(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, tokenHash string) error
	UpdateArtist(ctx context.Context, arg UpdateArtistParams) (Artist, error)
	UpdateFlashDesign(ctx context.Context, arg UpdateFlashDesignParams) (FlashDesign, error)
	UpdatePortfolioItem(ctx context.Context, arg UpdatePortfolioItemParams) (PortfolioItem, error)
	// Used when an in-progress signup re-submits with corrected data
	// (e.g. typo'd phone number). Only updates rows where the phone has
	// not yet been verified.
	UpdateUnverifiedUser(ctx context.Context, arg UpdateUnverifiedUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpsertArtistAvailability(ctx context.Context, arg UpsertArtistAvailabilityParams) (ArtistAvailability, error)
}

var _ Querier = (*Queries)(nil)
