// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reminders.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimDuePaymentReminders = `-- name: ClaimDuePaymentReminders :many
UPDATE payment_requests
SET reminder_sent_at = now(),
    updated_at       = now()
WHERE status = 'requested'
  AND reminder_sent_at IS NULL
  AND created_at <= $1
  AND expires_at > now()
RETURNING id, artist_id, type, currency, client_charge_cents,
          client_name, client_email, public_token
`

type ClaimDuePaymentRemindersRow struct {
	ID                uuid.UUID `json:"id"`
	ArtistID          uuid.UUID `json:"artist_id"`
	Type              string    `json:"type"`
	Currency          string    `json:"currency"`
	ClientChargeCents int64     `json:"client_charge_cents"`
	ClientName        string    `json:"client_name"`
	ClientEmail       string    `json:"client_email"`
	PublicToken       string    `json:"public_token"`
}

func (q *Queries) ClaimDuePaymentReminders(ctx context.Context, cutoff pgtype.Timestamptz) ([]ClaimDuePaymentRemindersRow, error) {
	rows, err := q.db.Query(ctx, claimDuePaymentReminders, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimDuePaymentRemindersRow
	for rows.Next() {
		var i ClaimDuePaymentRemindersRow
		if err := rows.Scan(
			&i.ID,
			&i.ArtistID,
			&i.Type,
			&i.Currency,
			&i.ClientChargeCents,
			&i.ClientName,
			&i.ClientEmail,
			&i.PublicToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimDueSessionReminders = `-- name: ClaimDueSessionReminders :many
UPDATE appointments a
SET reminder_sent_at = now(),
    updated_at       = now()
FROM booking_requests br
WHERE a.booking_request_id = br.id
  AND a.status = 'scheduled'
  AND a.type IN ('consultation', 'session')
  AND a.reminder_sent_at IS NULL
  AND a.scheduled_start >= now()
  AND a.scheduled_start <= $1
  AND br.client_phone <> ''
RETURNING a.id, a.artist_id, a.type, a.scheduled_start,
          br.client_name, br.client_phone
`

type ClaimDueSessionRemindersRow struct {
	ID             uuid.UUID          `json:"id"`
	ArtistID       uuid.UUID          `json:"artist_id"`
	Type           string             `json:"type"`
	ScheduledStart pgtype.Timestamptz `json:"scheduled_start"`
	ClientName     string             `json:"client_name"`
	ClientPhone    string             `json:"client_phone"`
}

func (q *Queries) ClaimDueSessionReminders(ctx context.Context, windowEnd pgtype.Timestamptz) ([]ClaimDueSessionRemindersRow, error) {
	rows, err := q.db.Query(ctx, claimDueSessionReminders, windowEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimDueSessionRemindersRow
	for rows.Next() {
		var i ClaimDueSessionRemindersRow
		if err := rows.Scan(
			&i.ID,
			&i.ArtistID,
			&i.Type,
			&i.ScheduledStart,
			&i.ClientName,
			&i.ClientPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtistContact = `-- name: GetArtistContact :one
SELECT u.first_name, u.last_name, u.username, s.timezone
FROM artists ar
JOIN users u ON u.id = ar.user_id
LEFT JOIN artist_settings s ON s.artist_id = ar.id
WHERE ar.id = $1
`

type GetArtistContactRow struct {
	FirstName *string `json:"first_name"`
	LastName  *string `json:"last_name"`
	Username  *string `json:"username"`
	Timezone  *string `json:"timezone"`
}

func (q *Queries) GetArtistContact(ctx context.Context, id uuid.UUID) (GetArtistContactRow, error) {
	row := q.db.QueryRow(ctx, getArtistContact, id)
	var i GetArtistContactRow
	err := row.Scan(
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.Timezone,
	)
	return i, err
}
