// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addBlocklistEntry = `-- name: AddBlocklistEntry :one
INSERT INTO artist_blocklist (artist_id, email, phone, note)
VALUES ($1, $2::citext, $3::text, $4)
RETURNING id, artist_id, email, phone, note, created_at
`

type AddBlocklistEntryParams struct {
	ArtistID uuid.UUID `json:"artist_id"`
	Email    *string   `json:"email"`
	Phone    *string   `json:"phone"`
	Note     string    `json:"note"`
}

func (q *Queries) AddBlocklistEntry(ctx context.Context, arg AddBlocklistEntryParams) (ArtistBlocklist, error) {
	row := q.db.QueryRow(ctx, addBlocklistEntry,
		arg.ArtistID,
		arg.Email,
		arg.Phone,
		arg.Note,
	)
	var i ArtistBlocklist
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Email,
		&i.Phone,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const addDayOff = `-- name: AddDayOff :exec
INSERT INTO artist_days_off (artist_id, day)
VALUES ($1, $2)
ON CONFLICT (artist_id, day) DO NOTHING
`

type AddDayOffParams struct {
	ArtistID uuid.UUID   `json:"artist_id"`
	Day      pgtype.Date `json:"day"`
}

func (q *Queries) AddDayOff(ctx context.Context, arg AddDayOffParams) error {
	_, err := q.db.Exec(ctx, addDayOff, arg.ArtistID, arg.Day)
	return err
}

const createSessionPreset = `-- name: CreateSessionPreset :one
INSERT INTO artist_session_presets (artist_id, name, description, approx_duration_minutes, position)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, artist_id, name, description, approx_duration_minutes, position, created_at
`

type CreateSessionPresetParams struct {
	ArtistID              uuid.UUID `json:"artist_id"`
	Name                  string    `json:"name"`
	Description           string    `json:"description"`
	ApproxDurationMinutes int32     `json:"approx_duration_minutes"`
	Position              int32     `json:"position"`
}

func (q *Queries) CreateSessionPreset(ctx context.Context, arg CreateSessionPresetParams) (ArtistSessionPreset, error) {
	row := q.db.QueryRow(ctx, createSessionPreset,
		arg.ArtistID,
		arg.Name,
		arg.Description,
		arg.ApproxDurationMinutes,
		arg.Position,
	)
	var i ArtistSessionPreset
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Name,
		&i.Description,
		&i.ApproxDurationMinutes,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAvailabilityWindows = `-- name: DeleteAvailabilityWindows :exec
DELETE FROM artist_availability_windows WHERE artist_id = $1
`

func (q *Queries) DeleteAvailabilityWindows(ctx context.Context, artistID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAvailabilityWindows, artistID)
	return err
}

const deleteSessionPreset = `-- name: DeleteSessionPreset :exec
DELETE FROM artist_session_presets
WHERE id = $1 AND artist_id = $2
`

type DeleteSessionPresetParams struct {
	ID       uuid.UUID `json:"id"`
	ArtistID uuid.UUID `json:"artist_id"`
}

func (q *Queries) DeleteSessionPreset(ctx context.Context, arg DeleteSessionPresetParams) error {
	_, err := q.db.Exec(ctx, deleteSessionPreset, arg.ID, arg.ArtistID)
	return err
}

const ensureArtistSettings = `-- name: EnsureArtistSettings :exec

INSERT INTO artist_settings (artist_id)
VALUES ($1)
ON CONFLICT (artist_id) DO NOTHING
`


func (q *Queries) EnsureArtistSettings(ctx context.Context, artistID uuid.UUID) error {
	_, err := q.db.Exec(ctx, ensureArtistSettings, artistID)
	return err
}

const getArtistSettings = `-- name: GetArtistSettings :one
SELECT artist_id, studio_name, studio_address, studio_city, studio_province, studio_postal_code, studio_country, stripe_account_id, payout_frequency, currency, deposit_flat_fee_cents, platform_fee_payer, accepting_bookings, timezone, google_calendar_email, slot_interval_minutes, buffer_minutes, min_notice_minutes, max_advance_days, terms_text, terms_show_on_booking, terms_show_at_deposit, waiver_file_url, waiver_required, notify_by_email, notify_by_sms, created_at, updated_at FROM artist_settings WHERE artist_id = $1
`

func (q *Queries) GetArtistSettings(ctx context.Context, artistID uuid.UUID) (ArtistSetting, error) {
	row := q.db.QueryRow(ctx, getArtistSettings, artistID)
	var i ArtistSetting
	err := row.Scan(
		&i.ArtistID,
		&i.StudioName,
		&i.StudioAddress,
		&i.StudioCity,
		&i.StudioProvince,
		&i.StudioPostalCode,
		&i.StudioCountry,
		&i.StripeAccountID,
		&i.PayoutFrequency,
		&i.Currency,
		&i.DepositFlatFeeCents,
		&i.PlatformFeePayer,
		&i.AcceptingBookings,
		&i.Timezone,
		&i.GoogleCalendarEmail,
		&i.SlotIntervalMinutes,
		&i.BufferMinutes,
		&i.MinNoticeMinutes,
		&i.MaxAdvanceDays,
		&i.TermsText,
		&i.TermsShowOnBooking,
		&i.TermsShowAtDeposit,
		&i.WaiverFileUrl,
		&i.WaiverRequired,
		&i.NotifyByEmail,
		&i.NotifyBySms,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one

SELECT id, email, password_hash, role, email_verified_at, created_at, updated_at, first_name, last_name, phone, phone_verified_at, username, avatar_url, instagram_url FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.PhoneVerifiedAt,
		&i.Username,
		&i.AvatarUrl,
		&i.InstagramUrl,
	)
	return i, err
}

const insertAvailabilityWindow = `-- name: InsertAvailabilityWindow :one
INSERT INTO artist_availability_windows (artist_id, weekday, start_minute, end_minute)
VALUES ($1, $2, $3, $4)
RETURNING id, artist_id, weekday, start_minute, end_minute
`

type InsertAvailabilityWindowParams struct {
	ArtistID    uuid.UUID `json:"artist_id"`
	Weekday     int32     `json:"weekday"`
	StartMinute int32     `json:"start_minute"`
	EndMinute   int32     `json:"end_minute"`
}

func (q *Queries) InsertAvailabilityWindow(ctx context.Context, arg InsertAvailabilityWindowParams) (ArtistAvailabilityWindow, error) {
	row := q.db.QueryRow(ctx, insertAvailabilityWindow,
		arg.ArtistID,
		arg.Weekday,
		arg.StartMinute,
		arg.EndMinute,
	)
	var i ArtistAvailabilityWindow
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Weekday,
		&i.StartMinute,
		&i.EndMinute,
	)
	return i, err
}

const listAvailabilityWindows = `-- name: ListAvailabilityWindows :many

SELECT id, artist_id, weekday, start_minute, end_minute
FROM artist_availability_windows
WHERE artist_id = $1
ORDER BY weekday, start_minute
`

func (q *Queries) ListAvailabilityWindows(ctx context.Context, artistID uuid.UUID) ([]ArtistAvailabilityWindow, error) {
	rows, err := q.db.Query(ctx, listAvailabilityWindows, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtistAvailabilityWindow
	for rows.Next() {
		var i ArtistAvailabilityWindow
		if err := rows.Scan(
			&i.ID,
			&i.ArtistID,
			&i.Weekday,
			&i.StartMinute,
			&i.EndMinute,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlocklist = `-- name: ListBlocklist :many

SELECT id, artist_id, email, phone, note, created_at
FROM artist_blocklist
WHERE artist_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListBlocklist(ctx context.Context, artistID uuid.UUID) ([]ArtistBlocklist, error) {
	rows, err := q.db.Query(ctx, listBlocklist, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtistBlocklist
	for rows.Next() {
		var i ArtistBlocklist
		if err := rows.Scan(
			&i.ID,
			&i.ArtistID,
			&i.Email,
			&i.Phone,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDaysOff = `-- name: ListDaysOff :many

SELECT artist_id, day
FROM artist_days_off
WHERE artist_id = $1
ORDER BY day
`

func (q *Queries) ListDaysOff(ctx context.Context, artistID uuid.UUID) ([]ArtistDaysOff, error) {
	rows, err := q.db.Query(ctx, listDaysOff, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtistDaysOff
	for rows.Next() {
		var i ArtistDaysOff
		if err := rows.Scan(&i.ArtistID, &i.Day); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionPresets = `-- name: ListSessionPresets :many

SELECT id, artist_id, name, description, approx_duration_minutes, position, created_at
FROM artist_session_presets
WHERE artist_id = $1
ORDER BY position, created_at
`

func (q *Queries) ListSessionPresets(ctx context.Context, artistID uuid.UUID) ([]ArtistSessionPreset, error) {
	rows, err := q.db.Query(ctx, listSessionPresets, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtistSessionPreset
	for rows.Next() {
		var i ArtistSessionPreset
		if err := rows.Scan(
			&i.ID,
			&i.ArtistID,
			&i.Name,
			&i.Description,
			&i.ApproxDurationMinutes,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeBlocklistEntry = `-- name: RemoveBlocklistEntry :exec
DELETE FROM artist_blocklist
WHERE id = $1 AND artist_id = $2
`

type RemoveBlocklistEntryParams struct {
	ID       uuid.UUID `json:"id"`
	ArtistID uuid.UUID `json:"artist_id"`
}

func (q *Queries) RemoveBlocklistEntry(ctx context.Context, arg RemoveBlocklistEntryParams) error {
	_, err := q.db.Exec(ctx, removeBlocklistEntry, arg.ID, arg.ArtistID)
	return err
}

const removeDayOff = `-- name: RemoveDayOff :exec
DELETE FROM artist_days_off
WHERE artist_id = $1 AND day = $2
`

type RemoveDayOffParams struct {
	ArtistID uuid.UUID   `json:"artist_id"`
	Day      pgtype.Date `json:"day"`
}

func (q *Queries) RemoveDayOff(ctx context.Context, arg RemoveDayOffParams) error {
	_, err := q.db.Exec(ctx, removeDayOff, arg.ArtistID, arg.Day)
	return err
}

const updateArtistSettings = `-- name: UpdateArtistSettings :one
UPDATE artist_settings
SET studio_name            = COALESCE($1::text,            studio_name),
    studio_address         = COALESCE($2::text,         studio_address),
    studio_city            = COALESCE($3::text,            studio_city),
    studio_province        = COALESCE($4::text,        studio_province),
    studio_postal_code     = COALESCE($5::text,     studio_postal_code),
    studio_country         = COALESCE($6::text,         studio_country),
    payout_frequency       = COALESCE($7::text,       payout_frequency),
    currency               = COALESCE($8::char(3),            currency),
    platform_fee_payer     = COALESCE($9::text,     platform_fee_payer),
    accepting_bookings     = COALESCE($10::boolean,  accepting_bookings),
    timezone               = COALESCE($11::text,               timezone),
    slot_interval_minutes  = COALESCE($12::integer, slot_interval_minutes),
    buffer_minutes         = COALESCE($13::integer,      buffer_minutes),
    min_notice_minutes     = COALESCE($14::integer,  min_notice_minutes),
    terms_text             = COALESCE($15::text,             terms_text),
    terms_show_on_booking  = COALESCE($16::boolean,  terms_show_on_booking),
    terms_show_at_deposit  = COALESCE($17::boolean,  terms_show_at_deposit),
    waiver_required        = COALESCE($18::boolean,     waiver_required),
    notify_by_email        = COALESCE($19::boolean,     notify_by_email),
    notify_by_sms          = COALESCE($20::boolean,       notify_by_sms),

    -- Nullable fields support explicit clearing via a paired boolean.
    deposit_flat_fee_cents = CASE
                                 WHEN $21::boolean THEN NULL
                                 ELSE COALESCE($22::bigint, deposit_flat_fee_cents)
                             END,
    max_advance_days       = CASE
                                 WHEN $23::boolean THEN NULL
                                 ELSE COALESCE($24::integer, max_advance_days)
                             END,
    stripe_account_id      = CASE
                                 WHEN $25::boolean THEN NULL
                                 ELSE COALESCE($26::text, stripe_account_id)
                             END,
    google_calendar_email  = CASE
                                 WHEN $27::boolean THEN NULL
                                 ELSE COALESCE($28::text, google_calendar_email)
                             END,
    waiver_file_url        = CASE
                                 WHEN $29::boolean THEN NULL
                                 ELSE COALESCE($30::text, waiver_file_url)
                             END,
    updated_at             = now()
WHERE artist_id = $31
RETURNING artist_id, studio_name, studio_address, studio_city, studio_province, studio_postal_code, studio_country, stripe_account_id, payout_frequency, currency, deposit_flat_fee_cents, platform_fee_payer, accepting_bookings, timezone, google_calendar_email, slot_interval_minutes, buffer_minutes, min_notice_minutes, max_advance_days, terms_text, terms_show_on_booking, terms_show_at_deposit, waiver_file_url, waiver_required, notify_by_email, notify_by_sms, created_at, updated_at
`

type UpdateArtistSettingsParams struct {
	StudioName          *string   `json:"studio_name"`
	StudioAddress       *string   `json:"studio_address"`
	StudioCity          *string   `json:"studio_city"`
	StudioProvince      *string   `json:"studio_province"`
	StudioPostalCode    *string   `json:"studio_postal_code"`
	StudioCountry       *string   `json:"studio_country"`
	PayoutFrequency     *string   `json:"payout_frequency"`
	Currency            *string   `json:"currency"`
	PlatformFeePayer    *string   `json:"platform_fee_payer"`
	AcceptingBookings   *bool     `json:"accepting_bookings"`
	Timezone            *string   `json:"timezone"`
	SlotIntervalMinutes *int32    `json:"slot_interval_minutes"`
	BufferMinutes       *int32    `json:"buffer_minutes"`
	MinNoticeMinutes    *int32    `json:"min_notice_minutes"`
	TermsText           *string   `json:"terms_text"`
	TermsShowOnBooking  *bool     `json:"terms_show_on_booking"`
	TermsShowAtDeposit  *bool     `json:"terms_show_at_deposit"`
	WaiverRequired      *bool     `json:"waiver_required"`
	NotifyByEmail       *bool     `json:"notify_by_email"`
	NotifyBySms         *bool     `json:"notify_by_sms"`
	ClearDepositFlatFee bool      `json:"clear_deposit_flat_fee"`
	DepositFlatFeeCents *int64    `json:"deposit_flat_fee_cents"`
	ClearMaxAdvance     bool      `json:"clear_max_advance"`
	MaxAdvanceDays      *int32    `json:"max_advance_days"`
	ClearStripeAccount  bool      `json:"clear_stripe_account"`
	StripeAccountID     *string   `json:"stripe_account_id"`
	ClearGoogleCalendar bool      `json:"clear_google_calendar"`
	GoogleCalendarEmail *string   `json:"google_calendar_email"`
	ClearWaiverFile     bool      `json:"clear_waiver_file"`
	WaiverFileUrl       *string   `json:"waiver_file_url"`
	ArtistID            uuid.UUID `json:"artist_id"`
}

func (q *Queries) UpdateArtistSettings(ctx context.Context, arg UpdateArtistSettingsParams) (ArtistSetting, error) {
	row := q.db.QueryRow(ctx, updateArtistSettings,
		arg.StudioName,
		arg.StudioAddress,
		arg.StudioCity,
		arg.StudioProvince,
		arg.StudioPostalCode,
		arg.StudioCountry,
		arg.PayoutFrequency,
		arg.Currency,
		arg.PlatformFeePayer,
		arg.AcceptingBookings,
		arg.Timezone,
		arg.SlotIntervalMinutes,
		arg.BufferMinutes,
		arg.MinNoticeMinutes,
		arg.TermsText,
		arg.TermsShowOnBooking,
		arg.TermsShowAtDeposit,
		arg.WaiverRequired,
		arg.NotifyByEmail,
		arg.NotifyBySms,
		arg.ClearDepositFlatFee,
		arg.DepositFlatFeeCents,
		arg.ClearMaxAdvance,
		arg.MaxAdvanceDays,
		arg.ClearStripeAccount,
		arg.StripeAccountID,
		arg.ClearGoogleCalendar,
		arg.GoogleCalendarEmail,
		arg.ClearWaiverFile,
		arg.WaiverFileUrl,
		arg.ArtistID,
	)
	var i ArtistSetting
	err := row.Scan(
		&i.ArtistID,
		&i.StudioName,
		&i.StudioAddress,
		&i.StudioCity,
		&i.StudioProvince,
		&i.StudioPostalCode,
		&i.StudioCountry,
		&i.StripeAccountID,
		&i.PayoutFrequency,
		&i.Currency,
		&i.DepositFlatFeeCents,
		&i.PlatformFeePayer,
		&i.AcceptingBookings,
		&i.Timezone,
		&i.GoogleCalendarEmail,
		&i.SlotIntervalMinutes,
		&i.BufferMinutes,
		&i.MinNoticeMinutes,
		&i.MaxAdvanceDays,
		&i.TermsText,
		&i.TermsShowOnBooking,
		&i.TermsShowAtDeposit,
		&i.WaiverFileUrl,
		&i.WaiverRequired,
		&i.NotifyByEmail,
		&i.NotifyBySms,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSessionPreset = `-- name: UpdateSessionPreset :one
UPDATE artist_session_presets
SET name                    = COALESCE($1::text,                  name),
    description             = COALESCE($2::text,           description),
    approx_duration_minutes = COALESCE($3::integer, approx_duration_minutes),
    position                = COALESCE($4::integer,           position)
WHERE id = $5 AND artist_id = $6
RETURNING id, artist_id, name, description, approx_duration_minutes, position, created_at
`

type UpdateSessionPresetParams struct {
	Name                  *string   `json:"name"`
	Description           *string   `json:"description"`
	ApproxDurationMinutes *int32    `json:"approx_duration_minutes"`
	Position              *int32    `json:"position"`
	ID                    uuid.UUID `json:"id"`
	ArtistID              uuid.UUID `json:"artist_id"`
}

func (q *Queries) UpdateSessionPreset(ctx context.Context, arg UpdateSessionPresetParams) (ArtistSessionPreset, error) {
	row := q.db.QueryRow(ctx, updateSessionPreset,
		arg.Name,
		arg.Description,
		arg.ApproxDurationMinutes,
		arg.Position,
		arg.ID,
		arg.ArtistID,
	)
	var i ArtistSessionPreset
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Name,
		&i.Description,
		&i.ApproxDurationMinutes,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserEmail = `-- name: UpdateUserEmail :one
UPDATE users
SET email      = $1,
    updated_at = now()
WHERE id = $2
RETURNING id, email, password_hash, role, email_verified_at, created_at, updated_at, first_name, last_name, phone, phone_verified_at, username, avatar_url, instagram_url
`

type UpdateUserEmailParams struct {
	Email string    `json:"email"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserEmail, arg.Email, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.PhoneVerifiedAt,
		&i.Username,
		&i.AvatarUrl,
		&i.InstagramUrl,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET first_name    = COALESCE($1::text,    first_name),
    last_name     = COALESCE($2::text,     last_name),
    username      = COALESCE($3::citext,    username),
    phone         = COALESCE($4::text,         phone),
    avatar_url    = COALESCE($5::text,    avatar_url),
    instagram_url = COALESCE($6::text, instagram_url),
    updated_at    = now()
WHERE id = $7
RETURNING id, email, password_hash, role, email_verified_at, created_at, updated_at, first_name, last_name, phone, phone_verified_at, username, avatar_url, instagram_url
`

type UpdateUserProfileParams struct {
	FirstName    *string   `json:"first_name"`
	LastName     *string   `json:"last_name"`
	Username     *string   `json:"username"`
	Phone        *string   `json:"phone"`
	AvatarUrl    *string   `json:"avatar_url"`
	InstagramUrl *string   `json:"instagram_url"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.FirstName,
		arg.LastName,
		arg.Username,
		arg.Phone,
		arg.AvatarUrl,
		arg.InstagramUrl,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.PhoneVerifiedAt,
		&i.Username,
		&i.AvatarUrl,
		&i.InstagramUrl,
	)
	return i, err
}
