// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addBlocklistEntry = `-- name: AddBlocklistEntry :one
INSERT INTO artist_blocklist (artist_id, email, phone, note)
VALUES ($1, $2::citext, $3::text, $4)
RETURNING id, artist_id, email, phone, note, created_at
`

type AddBlocklistEntryParams struct {
	ArtistID uuid.UUID `json:"artist_id"`
	Email    *string   `json:"email"`
	Phone    *string   `json:"phone"`
	Note     string    `json:"note"`
}

func (q *Queries) AddBlocklistEntry(ctx context.Context, arg AddBlocklistEntryParams) (ArtistBlocklist, error) {
	row := q.db.QueryRow(ctx, addBlocklistEntry,
		arg.ArtistID,
		arg.Email,
		arg.Phone,
		arg.Note,
	)
	var i ArtistBlocklist
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Email,
		&i.Phone,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const addDayOff = `-- name: AddDayOff :exec
INSERT INTO artist_days_off (artist_id, day)
VALUES ($1, $2)
ON CONFLICT (artist_id, day) DO NOTHING
`

type AddDayOffParams struct {
	ArtistID uuid.UUID   `json:"artist_id"`
	Day      pgtype.Date `json:"day"`
}

func (q *Queries) AddDayOff(ctx context.Context, arg AddDayOffParams) error {
	_, err := q.db.Exec(ctx, addDayOff, arg.ArtistID, arg.Day)
	return err
}

const clearGoogleCalendarConnection = `-- name: ClearGoogleCalendarConnection :one
UPDATE artist_settings
SET google_calendar_email         = NULL,
    google_calendar_access_token  = NULL,
    google_calendar_refresh_token = NULL,
    google_calendar_token_expiry  = NULL,
    updated_at                    = now()
WHERE artist_id = $1
RETURNING artist_id, stripe_account_id, payout_frequency, currency, deposit_flat_fee_cents, platform_fee_payer, accepting_bookings, timezone, google_calendar_email, slot_interval_minutes, buffer_minutes, min_notice_minutes, max_advance_days, terms_text, terms_show_on_booking, terms_show_at_deposit, waiver_file_url, waiver_required, notify_by_email, notify_by_sms, created_at, updated_at, google_calendar_access_token, google_calendar_refresh_token, google_calendar_token_expiry, stripe_charges_enabled, stripe_payouts_enabled, stripe_details_submitted, deposit_refund_policy, cancellation_notice_hours, styles, aftercare, faqs, current_location_id, monthly_booking_goal
`

func (q *Queries) ClearGoogleCalendarConnection(ctx context.Context, artistID uuid.UUID) (ArtistSetting, error) {
	row := q.db.QueryRow(ctx, clearGoogleCalendarConnection, artistID)
	var i ArtistSetting
	err := row.Scan(
		&i.ArtistID,
		&i.StripeAccountID,
		&i.PayoutFrequency,
		&i.Currency,
		&i.DepositFlatFeeCents,
		&i.PlatformFeePayer,
		&i.AcceptingBookings,
		&i.Timezone,
		&i.GoogleCalendarEmail,
		&i.SlotIntervalMinutes,
		&i.BufferMinutes,
		&i.MinNoticeMinutes,
		&i.MaxAdvanceDays,
		&i.TermsText,
		&i.TermsShowOnBooking,
		&i.TermsShowAtDeposit,
		&i.WaiverFileURL,
		&i.WaiverRequired,
		&i.NotifyByEmail,
		&i.NotifyBySMS,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleCalendarAccessToken,
		&i.GoogleCalendarRefreshToken,
		&i.GoogleCalendarTokenExpiry,
		&i.StripeChargesEnabled,
		&i.StripePayoutsEnabled,
		&i.StripeDetailsSubmitted,
		&i.DepositRefundPolicy,
		&i.CancellationNoticeHours,
		&i.Styles,
		&i.Aftercare,
		&i.Faqs,
		&i.CurrentLocationID,
		&i.MonthlyBookingGoal,
	)
	return i, err
}

const clearStripeAccount = `-- name: ClearStripeAccount :one
UPDATE artist_settings
SET stripe_account_id        = NULL,
    stripe_charges_enabled   = false,
    stripe_payouts_enabled   = false,
    stripe_details_submitted = false,
    updated_at               = now()
WHERE artist_id = $1
RETURNING artist_id, stripe_account_id, payout_frequency, currency, deposit_flat_fee_cents, platform_fee_payer, accepting_bookings, timezone, google_calendar_email, slot_interval_minutes, buffer_minutes, min_notice_minutes, max_advance_days, terms_text, terms_show_on_booking, terms_show_at_deposit, waiver_file_url, waiver_required, notify_by_email, notify_by_sms, created_at, updated_at, google_calendar_access_token, google_calendar_refresh_token, google_calendar_token_expiry, stripe_charges_enabled, stripe_payouts_enabled, stripe_details_submitted, deposit_refund_policy, cancellation_notice_hours, styles, aftercare, faqs, current_location_id, monthly_booking_goal
`

func (q *Queries) ClearStripeAccount(ctx context.Context, artistID uuid.UUID) (ArtistSetting, error) {
	row := q.db.QueryRow(ctx, clearStripeAccount, artistID)
	var i ArtistSetting
	err := row.Scan(
		&i.ArtistID,
		&i.StripeAccountID,
		&i.PayoutFrequency,
		&i.Currency,
		&i.DepositFlatFeeCents,
		&i.PlatformFeePayer,
		&i.AcceptingBookings,
		&i.Timezone,
		&i.GoogleCalendarEmail,
		&i.SlotIntervalMinutes,
		&i.BufferMinutes,
		&i.MinNoticeMinutes,
		&i.MaxAdvanceDays,
		&i.TermsText,
		&i.TermsShowOnBooking,
		&i.TermsShowAtDeposit,
		&i.WaiverFileURL,
		&i.WaiverRequired,
		&i.NotifyByEmail,
		&i.NotifyBySMS,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleCalendarAccessToken,
		&i.GoogleCalendarRefreshToken,
		&i.GoogleCalendarTokenExpiry,
		&i.StripeChargesEnabled,
		&i.StripePayoutsEnabled,
		&i.StripeDetailsSubmitted,
		&i.DepositRefundPolicy,
		&i.CancellationNoticeHours,
		&i.Styles,
		&i.Aftercare,
		&i.Faqs,
		&i.CurrentLocationID,
		&i.MonthlyBookingGoal,
	)
	return i, err
}

const createAvailabilityWindow = `-- name: CreateAvailabilityWindow :one
INSERT INTO artist_availability_windows (artist_id, weekday, start_minute, end_minute)
VALUES ($1, $2, $3, $4)
RETURNING id, artist_id, weekday, start_minute, end_minute
`

type CreateAvailabilityWindowParams struct {
	ArtistID    uuid.UUID `json:"artist_id"`
	Weekday     int32     `json:"weekday"`
	StartMinute int32     `json:"start_minute"`
	EndMinute   int32     `json:"end_minute"`
}

func (q *Queries) CreateAvailabilityWindow(ctx context.Context, arg CreateAvailabilityWindowParams) (ArtistAvailabilityWindow, error) {
	row := q.db.QueryRow(ctx, createAvailabilityWindow,
		arg.ArtistID,
		arg.Weekday,
		arg.StartMinute,
		arg.EndMinute,
	)
	var i ArtistAvailabilityWindow
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Weekday,
		&i.StartMinute,
		&i.EndMinute,
	)
	return i, err
}

const createSessionPreset = `-- name: CreateSessionPreset :one
INSERT INTO artist_session_presets (artist_id, name, description, approx_duration_minutes, position)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, artist_id, name, description, approx_duration_minutes, position, created_at
`

type CreateSessionPresetParams struct {
	ArtistID              uuid.UUID `json:"artist_id"`
	Name                  string    `json:"name"`
	Description           string    `json:"description"`
	ApproxDurationMinutes int32     `json:"approx_duration_minutes"`
	Position              int32     `json:"position"`
}

func (q *Queries) CreateSessionPreset(ctx context.Context, arg CreateSessionPresetParams) (ArtistSessionPreset, error) {
	row := q.db.QueryRow(ctx, createSessionPreset,
		arg.ArtistID,
		arg.Name,
		arg.Description,
		arg.ApproxDurationMinutes,
		arg.Position,
	)
	var i ArtistSessionPreset
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Name,
		&i.Description,
		&i.ApproxDurationMinutes,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllAvailabilityWindows = `-- name: DeleteAllAvailabilityWindows :exec
DELETE FROM artist_availability_windows WHERE artist_id = $1
`

func (q *Queries) DeleteAllAvailabilityWindows(ctx context.Context, artistID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllAvailabilityWindows, artistID)
	return err
}

const deleteSessionPreset = `-- name: DeleteSessionPreset :exec
DELETE FROM artist_session_presets
WHERE id = $1 AND artist_id = $2
`

type DeleteSessionPresetParams struct {
	ID       uuid.UUID `json:"id"`
	ArtistID uuid.UUID `json:"artist_id"`
}

func (q *Queries) DeleteSessionPreset(ctx context.Context, arg DeleteSessionPresetParams) error {
	_, err := q.db.Exec(ctx, deleteSessionPreset, arg.ID, arg.ArtistID)
	return err
}

const ensureArtistSettings = `-- name: EnsureArtistSettings :exec
INSERT INTO artist_settings (artist_id)
VALUES ($1)
ON CONFLICT (artist_id) DO NOTHING
`

func (q *Queries) EnsureArtistSettings(ctx context.Context, artistID uuid.UUID) error {
	_, err := q.db.Exec(ctx, ensureArtistSettings, artistID)
	return err
}

const getArtistSettings = `-- name: GetArtistSettings :one
SELECT artist_id, stripe_account_id, payout_frequency, currency, deposit_flat_fee_cents, platform_fee_payer, accepting_bookings, timezone, google_calendar_email, slot_interval_minutes, buffer_minutes, min_notice_minutes, max_advance_days, terms_text, terms_show_on_booking, terms_show_at_deposit, waiver_file_url, waiver_required, notify_by_email, notify_by_sms, created_at, updated_at, google_calendar_access_token, google_calendar_refresh_token, google_calendar_token_expiry, stripe_charges_enabled, stripe_payouts_enabled, stripe_details_submitted, deposit_refund_policy, cancellation_notice_hours, styles, aftercare, faqs, current_location_id, monthly_booking_goal FROM artist_settings WHERE artist_id = $1
`

func (q *Queries) GetArtistSettings(ctx context.Context, artistID uuid.UUID) (ArtistSetting, error) {
	row := q.db.QueryRow(ctx, getArtistSettings, artistID)
	var i ArtistSetting
	err := row.Scan(
		&i.ArtistID,
		&i.StripeAccountID,
		&i.PayoutFrequency,
		&i.Currency,
		&i.DepositFlatFeeCents,
		&i.PlatformFeePayer,
		&i.AcceptingBookings,
		&i.Timezone,
		&i.GoogleCalendarEmail,
		&i.SlotIntervalMinutes,
		&i.BufferMinutes,
		&i.MinNoticeMinutes,
		&i.MaxAdvanceDays,
		&i.TermsText,
		&i.TermsShowOnBooking,
		&i.TermsShowAtDeposit,
		&i.WaiverFileURL,
		&i.WaiverRequired,
		&i.NotifyByEmail,
		&i.NotifyBySMS,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleCalendarAccessToken,
		&i.GoogleCalendarRefreshToken,
		&i.GoogleCalendarTokenExpiry,
		&i.StripeChargesEnabled,
		&i.StripePayoutsEnabled,
		&i.StripeDetailsSubmitted,
		&i.DepositRefundPolicy,
		&i.CancellationNoticeHours,
		&i.Styles,
		&i.Aftercare,
		&i.Faqs,
		&i.CurrentLocationID,
		&i.MonthlyBookingGoal,
	)
	return i, err
}

const getArtistSettingsByStripeAccount = `-- name: GetArtistSettingsByStripeAccount :one
SELECT artist_id, stripe_account_id, payout_frequency, currency, deposit_flat_fee_cents, platform_fee_payer, accepting_bookings, timezone, google_calendar_email, slot_interval_minutes, buffer_minutes, min_notice_minutes, max_advance_days, terms_text, terms_show_on_booking, terms_show_at_deposit, waiver_file_url, waiver_required, notify_by_email, notify_by_sms, created_at, updated_at, google_calendar_access_token, google_calendar_refresh_token, google_calendar_token_expiry, stripe_charges_enabled, stripe_payouts_enabled, stripe_details_submitted, deposit_refund_policy, cancellation_notice_hours, styles, aftercare, faqs, current_location_id, monthly_booking_goal FROM artist_settings WHERE stripe_account_id = $1
`

func (q *Queries) GetArtistSettingsByStripeAccount(ctx context.Context, stripeAccountID *string) (ArtistSetting, error) {
	row := q.db.QueryRow(ctx, getArtistSettingsByStripeAccount, stripeAccountID)
	var i ArtistSetting
	err := row.Scan(
		&i.ArtistID,
		&i.StripeAccountID,
		&i.PayoutFrequency,
		&i.Currency,
		&i.DepositFlatFeeCents,
		&i.PlatformFeePayer,
		&i.AcceptingBookings,
		&i.Timezone,
		&i.GoogleCalendarEmail,
		&i.SlotIntervalMinutes,
		&i.BufferMinutes,
		&i.MinNoticeMinutes,
		&i.MaxAdvanceDays,
		&i.TermsText,
		&i.TermsShowOnBooking,
		&i.TermsShowAtDeposit,
		&i.WaiverFileURL,
		&i.WaiverRequired,
		&i.NotifyByEmail,
		&i.NotifyBySMS,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleCalendarAccessToken,
		&i.GoogleCalendarRefreshToken,
		&i.GoogleCalendarTokenExpiry,
		&i.StripeChargesEnabled,
		&i.StripePayoutsEnabled,
		&i.StripeDetailsSubmitted,
		&i.DepositRefundPolicy,
		&i.CancellationNoticeHours,
		&i.Styles,
		&i.Aftercare,
		&i.Faqs,
		&i.CurrentLocationID,
		&i.MonthlyBookingGoal,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, password_hash, role, email_verified_at, created_at, updated_at, first_name, last_name, phone, phone_verified_at, username, avatar_url, instagram_url, marketing_opt_in_at, marketing_opt_in_source FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.PhoneVerifiedAt,
		&i.Username,
		&i.AvatarURL,
		&i.InstagramURL,
		&i.MarketingOptInAt,
		&i.MarketingOptInSource,
	)
	return i, err
}

const listAvailabilityWindows = `-- name: ListAvailabilityWindows :many
SELECT id, artist_id, weekday, start_minute, end_minute
FROM artist_availability_windows
WHERE artist_id = $1
ORDER BY weekday, start_minute
`

func (q *Queries) ListAvailabilityWindows(ctx context.Context, artistID uuid.UUID) ([]ArtistAvailabilityWindow, error) {
	rows, err := q.db.Query(ctx, listAvailabilityWindows, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtistAvailabilityWindow
	for rows.Next() {
		var i ArtistAvailabilityWindow
		if err := rows.Scan(
			&i.ID,
			&i.ArtistID,
			&i.Weekday,
			&i.StartMinute,
			&i.EndMinute,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlocklist = `-- name: ListBlocklist :many
SELECT id, artist_id, email, phone, note, created_at
FROM artist_blocklist
WHERE artist_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListBlocklist(ctx context.Context, artistID uuid.UUID) ([]ArtistBlocklist, error) {
	rows, err := q.db.Query(ctx, listBlocklist, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtistBlocklist
	for rows.Next() {
		var i ArtistBlocklist
		if err := rows.Scan(
			&i.ID,
			&i.ArtistID,
			&i.Email,
			&i.Phone,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDaysOff = `-- name: ListDaysOff :many
SELECT artist_id, day
FROM artist_days_off
WHERE artist_id = $1
ORDER BY day
`

func (q *Queries) ListDaysOff(ctx context.Context, artistID uuid.UUID) ([]ArtistDaysOff, error) {
	rows, err := q.db.Query(ctx, listDaysOff, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtistDaysOff
	for rows.Next() {
		var i ArtistDaysOff
		if err := rows.Scan(&i.ArtistID, &i.Day); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionPresets = `-- name: ListSessionPresets :many
SELECT id, artist_id, name, description, approx_duration_minutes, position, created_at
FROM artist_session_presets
WHERE artist_id = $1
ORDER BY position, created_at
`

func (q *Queries) ListSessionPresets(ctx context.Context, artistID uuid.UUID) ([]ArtistSessionPreset, error) {
	rows, err := q.db.Query(ctx, listSessionPresets, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtistSessionPreset
	for rows.Next() {
		var i ArtistSessionPreset
		if err := rows.Scan(
			&i.ID,
			&i.ArtistID,
			&i.Name,
			&i.Description,
			&i.ApproxDurationMinutes,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeBlocklistEntry = `-- name: RemoveBlocklistEntry :exec
DELETE FROM artist_blocklist
WHERE id = $1 AND artist_id = $2
`

type RemoveBlocklistEntryParams struct {
	ID       uuid.UUID `json:"id"`
	ArtistID uuid.UUID `json:"artist_id"`
}

func (q *Queries) RemoveBlocklistEntry(ctx context.Context, arg RemoveBlocklistEntryParams) error {
	_, err := q.db.Exec(ctx, removeBlocklistEntry, arg.ID, arg.ArtistID)
	return err
}

const removeDayOff = `-- name: RemoveDayOff :exec
DELETE FROM artist_days_off
WHERE artist_id = $1 AND day = $2
`

type RemoveDayOffParams struct {
	ArtistID uuid.UUID   `json:"artist_id"`
	Day      pgtype.Date `json:"day"`
}

func (q *Queries) RemoveDayOff(ctx context.Context, arg RemoveDayOffParams) error {
	_, err := q.db.Exec(ctx, removeDayOff, arg.ArtistID, arg.Day)
	return err
}

const setGoogleCalendarConnection = `-- name: SetGoogleCalendarConnection :one
UPDATE artist_settings
SET google_calendar_email         = $1::text,
    google_calendar_access_token  = $2::text,
    google_calendar_refresh_token = COALESCE($3::text, google_calendar_refresh_token),
    google_calendar_token_expiry  = $4::timestamptz,
    updated_at                    = now()
WHERE artist_id = $5
RETURNING artist_id, stripe_account_id, payout_frequency, currency, deposit_flat_fee_cents, platform_fee_payer, accepting_bookings, timezone, google_calendar_email, slot_interval_minutes, buffer_minutes, min_notice_minutes, max_advance_days, terms_text, terms_show_on_booking, terms_show_at_deposit, waiver_file_url, waiver_required, notify_by_email, notify_by_sms, created_at, updated_at, google_calendar_access_token, google_calendar_refresh_token, google_calendar_token_expiry, stripe_charges_enabled, stripe_payouts_enabled, stripe_details_submitted, deposit_refund_policy, cancellation_notice_hours, styles, aftercare, faqs, current_location_id, monthly_booking_goal
`

type SetGoogleCalendarConnectionParams struct {
	GoogleCalendarEmail string             `json:"google_calendar_email"`
	AccessToken         string             `json:"access_token"`
	RefreshToken        *string            `json:"refresh_token"`
	TokenExpiry         pgtype.Timestamptz `json:"token_expiry"`
	ArtistID            uuid.UUID          `json:"artist_id"`
}

func (q *Queries) SetGoogleCalendarConnection(ctx context.Context, arg SetGoogleCalendarConnectionParams) (ArtistSetting, error) {
	row := q.db.QueryRow(ctx, setGoogleCalendarConnection,
		arg.GoogleCalendarEmail,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiry,
		arg.ArtistID,
	)
	var i ArtistSetting
	err := row.Scan(
		&i.ArtistID,
		&i.StripeAccountID,
		&i.PayoutFrequency,
		&i.Currency,
		&i.DepositFlatFeeCents,
		&i.PlatformFeePayer,
		&i.AcceptingBookings,
		&i.Timezone,
		&i.GoogleCalendarEmail,
		&i.SlotIntervalMinutes,
		&i.BufferMinutes,
		&i.MinNoticeMinutes,
		&i.MaxAdvanceDays,
		&i.TermsText,
		&i.TermsShowOnBooking,
		&i.TermsShowAtDeposit,
		&i.WaiverFileURL,
		&i.WaiverRequired,
		&i.NotifyByEmail,
		&i.NotifyBySMS,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleCalendarAccessToken,
		&i.GoogleCalendarRefreshToken,
		&i.GoogleCalendarTokenExpiry,
		&i.StripeChargesEnabled,
		&i.StripePayoutsEnabled,
		&i.StripeDetailsSubmitted,
		&i.DepositRefundPolicy,
		&i.CancellationNoticeHours,
		&i.Styles,
		&i.Aftercare,
		&i.Faqs,
		&i.CurrentLocationID,
		&i.MonthlyBookingGoal,
	)
	return i, err
}

const setStripeAccount = `-- name: SetStripeAccount :one
UPDATE artist_settings
SET stripe_account_id        = $1::text,
    stripe_charges_enabled   = false,
    stripe_payouts_enabled   = false,
    stripe_details_submitted = false,
    updated_at               = now()
WHERE artist_id = $2
RETURNING artist_id, stripe_account_id, payout_frequency, currency, deposit_flat_fee_cents, platform_fee_payer, accepting_bookings, timezone, google_calendar_email, slot_interval_minutes, buffer_minutes, min_notice_minutes, max_advance_days, terms_text, terms_show_on_booking, terms_show_at_deposit, waiver_file_url, waiver_required, notify_by_email, notify_by_sms, created_at, updated_at, google_calendar_access_token, google_calendar_refresh_token, google_calendar_token_expiry, stripe_charges_enabled, stripe_payouts_enabled, stripe_details_submitted, deposit_refund_policy, cancellation_notice_hours, styles, aftercare, faqs, current_location_id, monthly_booking_goal
`

type SetStripeAccountParams struct {
	StripeAccountID string    `json:"stripe_account_id"`
	ArtistID        uuid.UUID `json:"artist_id"`
}

func (q *Queries) SetStripeAccount(ctx context.Context, arg SetStripeAccountParams) (ArtistSetting, error) {
	row := q.db.QueryRow(ctx, setStripeAccount, arg.StripeAccountID, arg.ArtistID)
	var i ArtistSetting
	err := row.Scan(
		&i.ArtistID,
		&i.StripeAccountID,
		&i.PayoutFrequency,
		&i.Currency,
		&i.DepositFlatFeeCents,
		&i.PlatformFeePayer,
		&i.AcceptingBookings,
		&i.Timezone,
		&i.GoogleCalendarEmail,
		&i.SlotIntervalMinutes,
		&i.BufferMinutes,
		&i.MinNoticeMinutes,
		&i.MaxAdvanceDays,
		&i.TermsText,
		&i.TermsShowOnBooking,
		&i.TermsShowAtDeposit,
		&i.WaiverFileURL,
		&i.WaiverRequired,
		&i.NotifyByEmail,
		&i.NotifyBySMS,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleCalendarAccessToken,
		&i.GoogleCalendarRefreshToken,
		&i.GoogleCalendarTokenExpiry,
		&i.StripeChargesEnabled,
		&i.StripePayoutsEnabled,
		&i.StripeDetailsSubmitted,
		&i.DepositRefundPolicy,
		&i.CancellationNoticeHours,
		&i.Styles,
		&i.Aftercare,
		&i.Faqs,
		&i.CurrentLocationID,
		&i.MonthlyBookingGoal,
	)
	return i, err
}

const updateArtistSettings = `-- name: UpdateArtistSettings :one
UPDATE artist_settings
SET payout_frequency       = COALESCE($1::text,       payout_frequency),
    currency               = COALESCE($2::char(3),            currency),
    platform_fee_payer     = COALESCE($3::text,     platform_fee_payer),
    accepting_bookings     = COALESCE($4::boolean,  accepting_bookings),
    timezone               = COALESCE($5::text,               timezone),
    slot_interval_minutes  = COALESCE($6::integer, slot_interval_minutes),
    buffer_minutes         = COALESCE($7::integer,      buffer_minutes),
    min_notice_minutes     = COALESCE($8::integer,  min_notice_minutes),
    terms_text             = COALESCE($9::text,             terms_text),
    terms_show_on_booking  = COALESCE($10::boolean,  terms_show_on_booking),
    terms_show_at_deposit  = COALESCE($11::boolean,  terms_show_at_deposit),
    waiver_required        = COALESCE($12::boolean,     waiver_required),
    notify_by_email        = COALESCE($13::boolean,     notify_by_email),
    notify_by_sms          = COALESCE($14::boolean,       notify_by_sms),
    deposit_refund_policy  = COALESCE($15::text,  deposit_refund_policy),
    styles                 = COALESCE($16::text[],              styles),
    aftercare              = COALESCE($17::text,              aftercare),
    faqs                   = COALESCE($18::jsonb,                  faqs),
    monthly_booking_goal   = COALESCE($19::integer, monthly_booking_goal),

    -- Nullable fields support explicit clearing via a paired boolean.
    deposit_flat_fee_cents = CASE
                                 WHEN $20::boolean THEN NULL
                                 ELSE COALESCE($21::bigint, deposit_flat_fee_cents)
                             END,
    max_advance_days       = CASE
                                 WHEN $22::boolean THEN NULL
                                 ELSE COALESCE($23::integer, max_advance_days)
                             END,
    cancellation_notice_hours = CASE
                                 WHEN $24::boolean THEN NULL
                                 ELSE COALESCE($25::integer, cancellation_notice_hours)
                             END,
    stripe_account_id      = CASE
                                 WHEN $26::boolean THEN NULL
                                 ELSE COALESCE($27::text, stripe_account_id)
                             END,
    google_calendar_email  = CASE
                                 WHEN $28::boolean THEN NULL
                                 ELSE COALESCE($29::text, google_calendar_email)
                             END,
    waiver_file_url        = CASE
                                 WHEN $30::boolean THEN NULL
                                 ELSE COALESCE($31::text, waiver_file_url)
                             END,
    updated_at             = now()
WHERE artist_id = $32
RETURNING artist_id, stripe_account_id, payout_frequency, currency, deposit_flat_fee_cents, platform_fee_payer, accepting_bookings, timezone, google_calendar_email, slot_interval_minutes, buffer_minutes, min_notice_minutes, max_advance_days, terms_text, terms_show_on_booking, terms_show_at_deposit, waiver_file_url, waiver_required, notify_by_email, notify_by_sms, created_at, updated_at, google_calendar_access_token, google_calendar_refresh_token, google_calendar_token_expiry, stripe_charges_enabled, stripe_payouts_enabled, stripe_details_submitted, deposit_refund_policy, cancellation_notice_hours, styles, aftercare, faqs, current_location_id, monthly_booking_goal
`

type UpdateArtistSettingsParams struct {
	PayoutFrequency              *string   `json:"payout_frequency"`
	Currency                     *string   `json:"currency"`
	PlatformFeePayer             *string   `json:"platform_fee_payer"`
	AcceptingBookings            *bool     `json:"accepting_bookings"`
	Timezone                     *string   `json:"timezone"`
	SlotIntervalMinutes          *int32    `json:"slot_interval_minutes"`
	BufferMinutes                *int32    `json:"buffer_minutes"`
	MinNoticeMinutes             *int32    `json:"min_notice_minutes"`
	TermsText                    *string   `json:"terms_text"`
	TermsShowOnBooking           *bool     `json:"terms_show_on_booking"`
	TermsShowAtDeposit           *bool     `json:"terms_show_at_deposit"`
	WaiverRequired               *bool     `json:"waiver_required"`
	NotifyByEmail                *bool     `json:"notify_by_email"`
	NotifyBySMS                  *bool     `json:"notify_by_sms"`
	DepositRefundPolicy          *string   `json:"deposit_refund_policy"`
	Styles                       []string  `json:"styles"`
	Aftercare                    *string   `json:"aftercare"`
	Faqs                         []byte    `json:"faqs"`
	MonthlyBookingGoal           *int32    `json:"monthly_booking_goal"`
	ClearDepositFlatFee          bool      `json:"clear_deposit_flat_fee"`
	DepositFlatFeeCents          *int64    `json:"deposit_flat_fee_cents"`
	ClearMaxAdvanceDays          bool      `json:"clear_max_advance_days"`
	MaxAdvanceDays               *int32    `json:"max_advance_days"`
	ClearCancellationNoticeHours bool      `json:"clear_cancellation_notice_hours"`
	CancellationNoticeHours      *int32    `json:"cancellation_notice_hours"`
	ClearStripeAccount           bool      `json:"clear_stripe_account"`
	StripeAccountID              *string   `json:"stripe_account_id"`
	ClearGoogleCalendar          bool      `json:"clear_google_calendar"`
	GoogleCalendarEmail          *string   `json:"google_calendar_email"`
	ClearWaiverFile              bool      `json:"clear_waiver_file"`
	WaiverFileURL                *string   `json:"waiver_file_url"`
	ArtistID                     uuid.UUID `json:"artist_id"`
}

func (q *Queries) UpdateArtistSettings(ctx context.Context, arg UpdateArtistSettingsParams) (ArtistSetting, error) {
	row := q.db.QueryRow(ctx, updateArtistSettings,
		arg.PayoutFrequency,
		arg.Currency,
		arg.PlatformFeePayer,
		arg.AcceptingBookings,
		arg.Timezone,
		arg.SlotIntervalMinutes,
		arg.BufferMinutes,
		arg.MinNoticeMinutes,
		arg.TermsText,
		arg.TermsShowOnBooking,
		arg.TermsShowAtDeposit,
		arg.WaiverRequired,
		arg.NotifyByEmail,
		arg.NotifyBySMS,
		arg.DepositRefundPolicy,
		arg.Styles,
		arg.Aftercare,
		arg.Faqs,
		arg.MonthlyBookingGoal,
		arg.ClearDepositFlatFee,
		arg.DepositFlatFeeCents,
		arg.ClearMaxAdvanceDays,
		arg.MaxAdvanceDays,
		arg.ClearCancellationNoticeHours,
		arg.CancellationNoticeHours,
		arg.ClearStripeAccount,
		arg.StripeAccountID,
		arg.ClearGoogleCalendar,
		arg.GoogleCalendarEmail,
		arg.ClearWaiverFile,
		arg.WaiverFileURL,
		arg.ArtistID,
	)
	var i ArtistSetting
	err := row.Scan(
		&i.ArtistID,
		&i.StripeAccountID,
		&i.PayoutFrequency,
		&i.Currency,
		&i.DepositFlatFeeCents,
		&i.PlatformFeePayer,
		&i.AcceptingBookings,
		&i.Timezone,
		&i.GoogleCalendarEmail,
		&i.SlotIntervalMinutes,
		&i.BufferMinutes,
		&i.MinNoticeMinutes,
		&i.MaxAdvanceDays,
		&i.TermsText,
		&i.TermsShowOnBooking,
		&i.TermsShowAtDeposit,
		&i.WaiverFileURL,
		&i.WaiverRequired,
		&i.NotifyByEmail,
		&i.NotifyBySMS,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleCalendarAccessToken,
		&i.GoogleCalendarRefreshToken,
		&i.GoogleCalendarTokenExpiry,
		&i.StripeChargesEnabled,
		&i.StripePayoutsEnabled,
		&i.StripeDetailsSubmitted,
		&i.DepositRefundPolicy,
		&i.CancellationNoticeHours,
		&i.Styles,
		&i.Aftercare,
		&i.Faqs,
		&i.CurrentLocationID,
		&i.MonthlyBookingGoal,
	)
	return i, err
}

const updateSessionPreset = `-- name: UpdateSessionPreset :one
UPDATE artist_session_presets
SET name                    = COALESCE($1::text,                  name),
    description             = COALESCE($2::text,           description),
    approx_duration_minutes = COALESCE($3::integer, approx_duration_minutes),
    position                = COALESCE($4::integer,           position)
WHERE id = $5 AND artist_id = $6
RETURNING id, artist_id, name, description, approx_duration_minutes, position, created_at
`

type UpdateSessionPresetParams struct {
	Name                  *string   `json:"name"`
	Description           *string   `json:"description"`
	ApproxDurationMinutes *int32    `json:"approx_duration_minutes"`
	Position              *int32    `json:"position"`
	ID                    uuid.UUID `json:"id"`
	ArtistID              uuid.UUID `json:"artist_id"`
}

func (q *Queries) UpdateSessionPreset(ctx context.Context, arg UpdateSessionPresetParams) (ArtistSessionPreset, error) {
	row := q.db.QueryRow(ctx, updateSessionPreset,
		arg.Name,
		arg.Description,
		arg.ApproxDurationMinutes,
		arg.Position,
		arg.ID,
		arg.ArtistID,
	)
	var i ArtistSessionPreset
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Name,
		&i.Description,
		&i.ApproxDurationMinutes,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const updateStripeAccountStatus = `-- name: UpdateStripeAccountStatus :one
UPDATE artist_settings
SET stripe_charges_enabled   = $1::boolean,
    stripe_payouts_enabled   = $2::boolean,
    stripe_details_submitted = $3::boolean,
    updated_at               = now()
WHERE artist_id = $4
RETURNING artist_id, stripe_account_id, payout_frequency, currency, deposit_flat_fee_cents, platform_fee_payer, accepting_bookings, timezone, google_calendar_email, slot_interval_minutes, buffer_minutes, min_notice_minutes, max_advance_days, terms_text, terms_show_on_booking, terms_show_at_deposit, waiver_file_url, waiver_required, notify_by_email, notify_by_sms, created_at, updated_at, google_calendar_access_token, google_calendar_refresh_token, google_calendar_token_expiry, stripe_charges_enabled, stripe_payouts_enabled, stripe_details_submitted, deposit_refund_policy, cancellation_notice_hours, styles, aftercare, faqs, current_location_id, monthly_booking_goal
`

type UpdateStripeAccountStatusParams struct {
	ChargesEnabled   bool      `json:"charges_enabled"`
	PayoutsEnabled   bool      `json:"payouts_enabled"`
	DetailsSubmitted bool      `json:"details_submitted"`
	ArtistID         uuid.UUID `json:"artist_id"`
}

func (q *Queries) UpdateStripeAccountStatus(ctx context.Context, arg UpdateStripeAccountStatusParams) (ArtistSetting, error) {
	row := q.db.QueryRow(ctx, updateStripeAccountStatus,
		arg.ChargesEnabled,
		arg.PayoutsEnabled,
		arg.DetailsSubmitted,
		arg.ArtistID,
	)
	var i ArtistSetting
	err := row.Scan(
		&i.ArtistID,
		&i.StripeAccountID,
		&i.PayoutFrequency,
		&i.Currency,
		&i.DepositFlatFeeCents,
		&i.PlatformFeePayer,
		&i.AcceptingBookings,
		&i.Timezone,
		&i.GoogleCalendarEmail,
		&i.SlotIntervalMinutes,
		&i.BufferMinutes,
		&i.MinNoticeMinutes,
		&i.MaxAdvanceDays,
		&i.TermsText,
		&i.TermsShowOnBooking,
		&i.TermsShowAtDeposit,
		&i.WaiverFileURL,
		&i.WaiverRequired,
		&i.NotifyByEmail,
		&i.NotifyBySMS,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleCalendarAccessToken,
		&i.GoogleCalendarRefreshToken,
		&i.GoogleCalendarTokenExpiry,
		&i.StripeChargesEnabled,
		&i.StripePayoutsEnabled,
		&i.StripeDetailsSubmitted,
		&i.DepositRefundPolicy,
		&i.CancellationNoticeHours,
		&i.Styles,
		&i.Aftercare,
		&i.Faqs,
		&i.CurrentLocationID,
		&i.MonthlyBookingGoal,
	)
	return i, err
}

const updateUserEmail = `-- name: UpdateUserEmail :one
UPDATE users
SET email      = $1,
    updated_at = now()
WHERE id = $2
RETURNING id, email, password_hash, role, email_verified_at, created_at, updated_at, first_name, last_name, phone, phone_verified_at, username, avatar_url, instagram_url, marketing_opt_in_at, marketing_opt_in_source
`

type UpdateUserEmailParams struct {
	Email string    `json:"email"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserEmail, arg.Email, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.PhoneVerifiedAt,
		&i.Username,
		&i.AvatarURL,
		&i.InstagramURL,
		&i.MarketingOptInAt,
		&i.MarketingOptInSource,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET first_name    = COALESCE($1::text,    first_name),
    last_name     = COALESCE($2::text,     last_name),
    username      = COALESCE($3::citext,    username),
    phone         = COALESCE($4::text,         phone),
    avatar_url    = COALESCE($5::text,    avatar_url),
    instagram_url = COALESCE($6::text, instagram_url),
    updated_at    = now()
WHERE id = $7
RETURNING id, email, password_hash, role, email_verified_at, created_at, updated_at, first_name, last_name, phone, phone_verified_at, username, avatar_url, instagram_url, marketing_opt_in_at, marketing_opt_in_source
`

type UpdateUserProfileParams struct {
	FirstName    *string   `json:"first_name"`
	LastName     *string   `json:"last_name"`
	Username     *string   `json:"username"`
	Phone        *string   `json:"phone"`
	AvatarURL    *string   `json:"avatar_url"`
	InstagramURL *string   `json:"instagram_url"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.FirstName,
		arg.LastName,
		arg.Username,
		arg.Phone,
		arg.AvatarURL,
		arg.InstagramURL,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.PhoneVerifiedAt,
		&i.Username,
		&i.AvatarURL,
		&i.InstagramURL,
		&i.MarketingOptInAt,
		&i.MarketingOptInSource,
	)
	return i, err
}
