// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stripe_events.sql

package sqlc

import (
	"context"
)

const insertStripeEvent = `-- name: InsertStripeEvent :execrows
INSERT INTO stripe_events (id, type)
VALUES ($1, $2)
ON CONFLICT (id) DO NOTHING
`

type InsertStripeEventParams struct {
	ID   string `json:"id"`
	Type string `json:"type"`
}

// Insert a Stripe event id for idempotency. Returns the number of rows inserted
// (1 = first time we've seen it, 0 = already processed → safe to skip).
func (q *Queries) InsertStripeEvent(ctx context.Context, arg InsertStripeEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertStripeEvent, arg.ID, arg.Type)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
